ostreedev/ostree

configure.ac, src/libostree/ostree-repo-checkout.c, src/libostree/ostree-repo-commit.c, src/libostree/ostree-repo.c, src/libostree/ostree-sepolicy.c, src/libostree/ostree-sysroot-deploy.c, src/libotutil/ot-fs-utils.c, src/libotutil/ot-gio-utils.c, src/libotutil/ot-unix-utils.c, src/libotutil/ot-unix-utils.h, src/libotutil/ot-variant-utils.c, src/ostree/ot-admin-builtin-os-init.c, src/ostree/ot-builtin-trivial-httpd.c
This is long overdue to make it to libgsystem.  Update our dependency.
=> Port to libgsystem errno API, hard depend on 2014.3

doc/ostree-static-delta.xml
=> doc: Manpage love for static-delta command

src/libostree/ostree-repo-commit.c, src/libostree/ostree-repo-private.h, src/libostree/ostree-repo-pull.c, src/libostree/ostree-repo.c, src/libotutil/ot-gio-utils.c, src/libotutil/ot-gio-utils.h, src/ostree/ot-builtin-pull-local.c, tests/pull-test.sh, tests/test-pull-mirror-summary.sh
Some internal refactoring to prepare for deltas, plus some pull optimizations for:
https://bugzilla.redhat.com/show_bug.cgi?id=1185106
=> Deltas prep work + pull optimizations

src/libostree/ostree-repo-pull.c, tests/test-commit-sign.sh
See https://bugzilla.gnome.org/748220
Always request detached metadata for commit objects, even if we already have the commit object.  This ensures we fetch any post facto detached metadata updates such as new GPG signatures.
Not the most elegant solution ever -- I'd say `enqueue_one_object_request()` is on the cusp of needing its own options enum -- but it seems to work.
The only weirdness I noticed is when the repo is otherwise up-to-date and you pull, you do get a metadata transfer count followed by `No upgrade available`, which to some might seem contradictory.
=> Always request detached metadata for commits

src/libostree/ostree-repo.c
I found out GPG version 2.1 and its new "keybox" file format [1] can break the `ostree remote gpg-import` command.  This is a workaround.
[1] https://gnupg.org/faq/whats-new-in-2.1.html#keybox
=> Prevent GPG keys from being imported to keybox format

src/ostree/ot-builtin-reset.c
Just a minor cleanup I noticed while reading the `ostree reset` code.
=> reset: Simplify argument checking logic

src/libostree/ostree-fetcher.c
The `GTlsInteraction` instance must be created in the session thread so it uses the correct `GMainContext`.
@miabbott reported this.  Rather urgent.
=> fetcher: Fix hung GTlsInteraction

tests/basic-test.sh, tests/test-pull-corruption.sh, tests/test-rofiles-fuse.sh
=> tests: More TAP fixups

src/libostree/ostree-repo-pull.c
We're creating the timer source and then passing ownership to the
context, but because we didn't free the pointer, we would still call
`g_source_destroy` in the exit path. We'd do this right after doing
`unref` on the context too, which would have already destroyed and
unref'ed the source.
Drop that and just restrict the scope of that variable down to make
things more obvious.
Just noticed this after reviewing #1953.
=> lib/pull: Avoid calling destroy on unref'ed GSource

src/libostree/ostree-repo-pull.c
I was hitting `SIGSEGV` when running `cosa build` and narrowed it down
to #1954. What's happening here is that because we're using the default
context, when we unref it in the out path, it may not actually destroy
the `GSource` if it (the context) is still ref'ed elsewhere. So then,
we'd still get events from it if subsequent operations iterated the
context.
This patch is mostly a revert of #1954, except that we still keep a ref
on the `GSource`. That way it is always safe to destroy it afterwards.
(And I've also added a comment to explain this better.)
=> lib/pull: Tweak update_timeout logic again

Makefile-tests.am, src/libostree/ostree-fetcher-curl.c, src/ostree/ostree-trivial-httpd.c, tests/test-pull-basicauth.sh
This has been requested a few times for people delivering
OSTree content and wanting to do access control.
=>     pull: Add support for basic auth

configure.ac, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
Nothing really big here, but let's get a release out
so some bigger things like ro-sysroot, signing, sizes can
bake in master for a bit.
=> Release 2019.6

.cci.jenkinsfile, ci/ci-commitmessage-submodules.sh
See https://github.com/jlebon/coreos-ci
This is just a start to test, cut down from the rpm-ostree version.
=> Add .cci.jenkinsfile

src/switchroot/ostree-prepare-root.c
Came up on an IRC question, docs for this are scattered around.
=> prepare-root: Add a comment about the role of this service

.cci.jenkinsfile
This one is very relevant for ostree.
=> ci: Test kola --upgrades

src/ostree/ot-admin-builtin-pin.c
This regressed in https://github.com/ostreedev/ostree/commit/2db79fb398fba2f9ab2e05c517ebccfe1834674b
I noticed this while finally getting the installed tests to run
in FCOS via kola and `ostree admin pin 0` is now aborting because
we were returning TRUE, but no error set.
I don't see a reason to try to continue on if we hit an error;
the original reporter was requesting support for multiple arguments,
but not "ignore invalid requests".
=> main/pin: Fix usage of GError

tests/kola/destructive/itest-label-selinux.sh, tests/kola/destructive/staged-deploy.sh
Now that we're actually running this in CI.
=> tests/kola: Two test fixes

src/ostree/ot-builtin-commit.c
Rework the simple cases of "commit ." and "commit argv[1]" to
generate the more general "--tree=X --tree=Y" path, so that we
only have one primary control flow here.
Prep for a future patch around loading SELinux policy from
the first argument.
=> main/commit: Rework control flow to use --tree=X path

OWNERS
He did a lot of work on signing and will continue that.
=> OWNERS: add d4s to reviewers

src/libostree/ostree-repo-pull.c
I'm mainly doing this to sanity check the CI state right now.
However, I also want to more cleanly/clearly distinguish
the "sign" code from the "gpg" code.
Rename one function to include `gpg`.
For the other...I think what it's really doing is using the remote
config, so change it to include `remote` in its name.
=> lib/pull: Two cosmetic internal function renames

docs/manual/formats.md, docs/manual/repo.md
Small docs updates which I find were missing/unclear while trying to understand the OSTree repository types/format better.
=> Doc updates

src/ostree/ot-remote-builtin-add.c, tests/test-signed-pull.sh
Per https://github.com/ostreedev/ostree/issues/2080#issuecomment-623614483
A huge benefit of ed25519 (and ECC in general) is that keys are very
short - short enough that it's completely reasonable to inline
them into a command line argument.
And I think that's a good model; it makes the keys very visible.
For example, someone could easily copy-paste a commandline
argument from a webpage (secured via TLS) that says to run
`ostree remote add --verify-ed25519=KEY`.
=> remote-add: Add --sign-verify=KEYTYPE=[inline|file]:PUBKEYREF 

tests/kola/destructive/staged-delay.sh
Attempting to reproduce
https://bugzilla.redhat.com/show_bug.cgi?id=1827712
but no dice yet.
=> tests/staged-delay.sh: New test

src/ostree/ot-remote-builtin-add.c
In https://github.com/ostreedev/ostree/pull/2092/commits/588f42e8c64183dfa1fbaa08cc92c46b691b23c4
we added a way to add keys for sign types when doing
a `remote add`, and in https://github.com/ostreedev/ostree/pull/2105
we extended `sign-verify` to support *limiting* to an explicit
set.
This PR changes the *default* for `remote add` to combine
the two - when providing an explicit `--sign-verify=type`,
we now limit the accepted types to only those.
=> remote-add: Default to explicit sign-verify backends

tests/inst/src/repobin.rs, tests/inst/src/test.rs
It's much cleaner if the Tokio stuff stays in `test.rs`, and
easier to write tests if the function is synchronous.
Prep for further tests.
=> tests/rust: Extract a with_webserver_in helper wrapper

src/ostree/ot-builtin-commit.c
I was trying to use this in some testing work and was confused for a minute.
=> commit: Note in help that --base takes an argument

tests/kolainst/libtest-core.sh, tests/test-symbols.sh
For the motivation for this see #2132.
=> tests: Check that example symbol isn't released

src/libostree/ostree-repo-static-delta-compilation.c
The "new style" code generally avoids `goto err` because it conflicts
with `__attribute__((cleanup))`.  This fixes a compiler warning.
Signed-off-by: Frédéric Danis <frederic.danis@collabora.com>
=> lib/deltas: convert ostree_repo_static_delta_generate to new style

OWNERS
I've made my affiliation public now thanks to @cgwalters:
https://github.com/ostreedev/ostree/pull/1678#issuecomment-653148139
=> OWNERS: Uncomment @wmanley

Makefile-libostree.am, configure.ac, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
A lot of stuff here, new signing API is the biggest.  Let's
get a release out.
=> Release 2020.4

.cci.jenkinsfile
Requires https://github.com/coreos/coreos-assembler/pull/1646
=> ci: add pxe-offline-install testiso scenario

configure.ac
Let's get the /var mount fix out at least.
=> Release 2020.6

src/libostree/ostree-repo-commit.c
Prep for adding `-Wshadow` fixes.
=> commit: Tighten scope of two variables

src/libostree/ostree-repo-static-delta-core.c
- Remove some unused variables
- Switch to declare-and-initialize with others
- Fix some indentation from 4 spaces to 2 (GNU style)
=> delta: Some minor code style fixups

src/libostree/ostree-repo-pull.c, src/libostree/ostree-sign.c
These are fixes for various pure bugs i found while working in the indexed-summary branch, ported to master.
=> Various fixes from the indexed-summaries branch

Makefile-libostree.am, configure.ac, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
Another release before merging big pull PRs.
=> Release 2020.7

.travis.yml, ci/travis-install.sh
In the past we've had 32 bit bugs that were caught by
the compiler, let's add this to Travis.
=> travis: Add a 32 bit build

docs/atomic-upgrades.md, docs/buildsystem-and-repos.md, docs/deployment.md, docs/formats.md, docs/repo.md, docs/repository-management.md
Fix some typos and improve the flow of some sentences.
=> docs: Fix various typos

src/ostree/ot-builtin-checkout.c
I was reading this code for unrelated reasons and noticed it
was still old style; port most (but not all) to new style.
=> bin/checkout: Port some to new style

src/libostree/ostree-repo-libarchive.c, tests/test-libarchive-import.c
If you specify an `xattr_callback` the xattrs will still be taken from
there for now.
**TODO:**
=> ostree commit --tree=tar: Import xattrs from tarballs

Makefile-libostree.am, src/libostree/ostree-repo-commit.c, src/libostree/ostree-repo-private.h, src/libostree/ostree-repo-verity.c, src/libostree/ostree-repo.c
This file will get larger when we start doing more with fsverity.
=> repo: Move fsverity bits to ostree-repo-verity.c

README.md
Since the topic of Debian+ostree-for-host comes up fairly often.
=> README.md: Also link apt2ostree

src/libostree/ostree-repo-static-delta-compilation.c
=> deltas: Fix leak of matches

README.md
Came up on #fedora-iot channel.
=> README.md: Fix contributing link, add contact section

tests/inst/src/destructive.rs, tests/inst/src/insttestmain.rs, tests/inst/src/test.rs
=> tests/inst: Fix lots of `cargo clippy` warnings

.github/workflows/tests.yml, tests/inst/src/destructive.rs, tests/inst/src/test.rs
Let's dip our toes in GH Actions (specifically aiming to migrate
away from Travis).
=> ci: Add a Github Action for Rust for tests/inst

Makefile-libostree.am, configure.ac, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
=> Release 2021.1

.cci.jenkinsfile, ci/installdeps.sh, tests/kolainst/libinsttest.sh, tests/pull-test.sh
See latest in https://github.com/coreos/fedora-coreos-tracker/blob/master/docs/ci-and-builds.md
=> cci: Update for buildroot changes

src/libostree/ostree-repo.c
Another introspection fix I hit when trying to use this in Rust.
=> repo: Fix load_variant_if_exists to return a nullable value

src/rofiles-fuse/main.c, tests/test-rofiles-fuse.sh
Enable support for setting and getting xattrs.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
=> rofiles-fuse: Enable support for setting and getting xattrs

src/libostree/ostree-core.c
I was going to add some new API and I noticed that this function
never returns an error; presumably at one point it did, but
not anymore.  It simplifies the code flow noticeably
to remove that.
=> core: Drop unused error handling from object stream helper

.travis.yml
xenial is EOL soon, let's bump to the latest LTS and the latest.
=> travis: Bump Ubuntu versions

.travis.yml
To try to catch issues that would appear on more frequently deployed 32 bit armv7.
=> Add back a travis 32 bit build

Makefile-libostree.am, configure.ac, docs/CONTRIBUTING.md, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
Going to try a coordinated "triple release" of ostree, ostree-rs, and ostree-rs-ext.
=> Release 2021.2

docs/atomic-upgrades.md
This came up a few times so let's go into more details in the docs.
=> docs: Add more details about 3-way merge

docs/atomic-upgrades.md
=> docs: typo fix for /usr/etc

ci/ci-release-build.sh
This fixes the ci-release-build.sh script to directly source
and evaluate 'package_version' from its m4 definition, without
requiring a fully configured source tree.
=> ci/release-build: evaluate package_version from m4 definition

src/libostree/ostree-sign-dummy.c, src/libostree/ostree-sysroot.c, src/ostree/ot-dump.c, tests/test-delta-sign.sh
Reported-by: Seth Arnold <seth.arnold@canonical.com>
=> A couple of Coverity fixes

src/ostree/ot-builtin-ls.c
This reworks `ostree ls` top-level logic so that cancellation
tokens and error details are plumbed through all codepaths.
It also gets rid of all previous goto jumps.
=> builtin: use GCancellable and GError everywhere

src/libostree/ostree-repo.c
This tightens up the logic for opening a file while inspecting its
xattrs. The only codepath fetching xattrs from a FD is the one
handling 'bare' mode.
It also rearranges the else-assert flow, mostly for future-proofing.
=> lib/repo: open file only if required

src/libostree/ostree-repo-libarchive.c
We're trying to debug a problem with a tar stream with hardlinks,
and I think this will be helpful.
=> lib/tar: Add some error prefixing

docs/index.md
=> Add Fedora Kinoite link to index.md also.

.github/workflows/docs.yml, .github/workflows/tests.yml
It doesn't have a new enough glib.
=> ci: Disable Ubuntu LTS

src/libostree/ostree-fetcher-curl.c
Static analyzers don't like when we only check it sometimes.
And we definitely want to know if any of these are failing.
=> fetcher/curl: Consistently check return value `curl_easy_setopt`

docs/ima.md
They have a lot of stuff there.
=> docs/ima: Also link the SUSE docs

src/libostree/ostree-bootloader-zipl.c
By design `SecureExecution` is enabled during CoreOS build. So if systems runs in non-SE mode, skip `sd-boot` generation. 
https://github.com/coreos/fedora-coreos-tracker/issues/1205
=> s390x: ensure SecureExecution is enabled before sd-boot generation

src/ostree/ot-admin-builtin-deploy.c, tests/test-admin-deploy-karg.sh
See https://github.com/ostreedev/ostree/issues/2586
=> Teach --karg-delete option to ostree admin deploy

Makefile-libostree.am, configure.ac, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
=> Release 2022.4

src/libostree/ostree-repo.c
I was looking at https://github.com/ostreedev/ostree/pull/2632
and confused at the usage of
`GVariant *value = g_variant_new ("(b@as)", TRUE, g_variant_new_strv (NULL, 0));`
which looked strange - why the empty strv?
It turns out that this is a historical legacy of the time when
ostree had pack files.  And nothing actually cares about the values
of these variants; we should have an API that returns a proper set,
and not a hash.
But...since all of these things have exactly the same value, instead
of allocating lots of redundant copies on the heap, just have
them all hold a refcount on a shared value.
This cuts the heap usage from 20MB to 13MB on a test FCOS repository
build.
=> repo: Optimize memory use of `ostree_repo_list_objects()`

src/ostree/ot-builtin-config.c, src/ostree/ot-builtin-diff.c
cli/config: Port to C99 style
General background cleanup.
---
cli/diff: Port to C99 style
General background cleanup.
---
=> cli: a few "Port to C99 style"

src/ostree/ot-builtin-gpg-sign.c, src/ostree/ot-remote-builtin-list.c, src/ostree/ot-remote-builtin-refs.c
cli/gpg-sign: Port to C99 style
General background cleanup.
---
cli/remote-list: Port to C99 style
General background cleanup.
---
cli/refs: Port to C99 style
General background cleanup.
---
=> cli: Port to C99 style (3)

tests/kolainst/destructive/staged-deploy.sh
https://github.com/coreos/coreos-assembler/pull/2921 broke this
test which is intentionally causing a systemd unit to fail.
As they say, necessity is the mother of invention.  They don't
say though that need always causes particularly *beautiful* things
to be invented...
=> tests/staged-deploy.sh: Hack around cosa systemd unit check

tests/inst/Cargo.toml, tests/inst/src/treegen.rs
=> tests/inst: Port to cap-std

Makefile-libostree.am, configure.ac, rust-bindings/tests/sign/mod.rs, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
=> Release 2022 5

src/ostree/ot-builtin-rev-parse.c
=> cli/rev-parse: Port to new code style

README.md
Adding TorizonCore as a distro using OSTree, and aktualizr as a project linking to ostree.
=> docs: Add aktualizr and TorizonCore to related projects

src/libostree/ostree-sign.c
This converts several invariant checks to asserts.
Most of the functions in this file were already using assertions, so this aligns the remaining few outliers to the rest.
=> lib/sign: convert invariant checks to assertions

README.md
Broken link for "recursive git archive" example
=> Fix recursive git archive reference

README.md
Another project in the ostree/container space.
=> README.md: Link otto

tests/readdir-rand.c
As noted in readdir(3), in the presence of long filenames it is possible for a directory entry to be larger than `sizeof (struct dirent)`. Copy the full length instead.
---
I happened to notice this while replacing `g_memdup` with `g_memdup2` for #2751.
=> readdir-rand: Copy full size of struct dirent

src/libostree/ostree-fetcher-util.c, tests/test-pull-repeated.sh
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>
Hello! This PR tries to address the issue #2747 . 
Manual testing shows that it follows the path of network retries, as other error codes:
```
OT: Should retry request (remaining: 5 retries), due to transient error: Server returned status 500: Internal Server Error
OT: starting fetch of be117dcfcf8b16c9ca2831a1dc9e6cb92944ee57d8e00adeb4cd769e95ac436e.file
OT: starting fetch of 582dda5ed1e27f82d001b220f96e43863c56d6143f0fdb930b2c808b514c45b4.dirtree
OT: fetch of 582dda5ed1e27f82d001b220f96e43863c56d6143f0fdb930b2c808b514c45b4.dirtree complete
OT: _ostree_fetcher_should_retry_request: error: 321:2 Server returned status 500: Internal Server Error, n_retries_remaining: 5
OT: Should retry request (remaining: 5 retries), due to transient …
```
=> Enabling retry for HTTP 500 internal server error

src/ostree/ot-builtin-commit.c
=> Improve a help string for ostree-commit

src/libostree/ostree-repo-pull.c, src/ostree/ot-builtin-pull-local.c, src/ostree/ot-builtin-pull.c
=> Fix a couple of small leaks

rust-bindings/src/repo_checkout_at_options/repo_checkout_filter.rs
Thanks to @shinmao for the report!
Closes: https://github.com/ostreedev/ostree/issues/2775
=> repo: Avoid potential double unwind when writing panic value

src/libostree/ostree-async-progress.c, src/libostree/ostree-checksum-input-stream.c, src/libostree/ostree-date-utils.c, src/libostree/ostree-gpg-verifier.c, src/libostree/ostree-repo-static-delta-compilation.c, src/libostree/ostree-sysroot-cleanup.c, src/libostree/ostree-sysroot-deploy.c, src/libostree/ostree-sysroot-upgrader.c
This converts a few more safety checks into either plain GErrors or hard assertions.
=> lib: assert more invariants

src/libostree/ostree-repo-pull.c
We added backoff/queueing for fetching via HTTP, but we have another queue in the metadata scanning which can also grow up to the number of outstanding objects, which can be large.
Capping the scanning operation when we have hit our operation limit will avoid potentially large amounts of allocations in the case of e.g. a slow network.
Closes: https://github.com/ostreedev/ostree/issues/2732
=> fetcher: Avoid too large queues for metadata processing

Makefile-libostree.am, configure.ac, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
=> Release  2023.1

src/libostree/ostree-fetcher-util.c
Since the value of `data->done` is not watched by the main context, the context doesn’t know to wake up from `g_main_context_iteration()` when that value is changed. The code currently relies on something else happening to wake the main context up shortly after `data->done` is set.
That doesn’t seem very reliable, so wake the main context up explicitly.
Spotted this while reading the code while trying to debug a stall with backtrace:
```
5  0x00007ffff68bbbfb in g_main_context_iteration (context=0x60f000136900, may_block=1) at ../../source/glib/glib/gmain.c:4343
6  0x00007fffdc0e50db in _ostree_fetcher_mirrored_request_to_membuf_once (fetcher=0x604001138c10, mirrorlist=0x603001df18b0, filename=0x7fffdc1049e7 "summary.sig", flags=OSTREE_FETCHER_REQUEST_OPTIONAL_CONTENT, …
```
=> lib/fetcher-util: Wake up main context when a request is complete

tests/test-basic-c.c
Closes: https://github.com/ostreedev/ostree/issues/2827
=> tests: Set size on fileinfo

configure.ac
=> Release 2023.2

tests/inst/src/treegen.rs
Since a later assertion would otherwise trigger.  We saw this happen in CI.
=> treegen: Require at least one mutation

src/libostree/ostree-sysroot-cleanup.c, src/libostree/ostree-sysroot-private.h, src/libotutil/ot-fs-utils.c, src/libotutil/ot-fs-utils.h
=> Prep patches for automatic early prune

tests/inst/src/destructive.rs
Part of https://github.com/ostreedev/ostree/issues/2857
=> tests: A bit more xshell porting

Makefile-libostree.am, configure.ac, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
=> Release 2023.4

docs/adapting-existing.md
- mention `DynamicUser=yes`
- mention the recent systemd JSON bits
- mention sysusers.doc
And briefly talk about the tradeoffs in these.
=> docs: Update user and group section

configure.ac
Mainly to get the flatpak bugfix out, but there are two other bugs.
=> Release 2023.5

src/switchroot/ostree-prepare-root.c
- Convert the current enum into a struct, using `OtTristate` and two member variables (expected signature and digest)
- Factor out a helper function to parse this config
- Clean up the logging by consistently using `composefs:` as a prefix
- Add more assertions to more strictly verify our runtime state since this is security relevant
=> prepare-root: Refactor composefs config handling

docs/composefs.md, src/switchroot/ostree-prepare-root.c
=> prepare-root: Minor clarifications

src/ostree/ot-builtin-admin.c, src/ostree/ot-remote-builtin-add.c
admin: Port to c99 style
- Drop `goto out`
- Use declare-and-initialize
---
remote-add: Port to c99 style
- Drop `goto out`
- Use declare-and-initialize
---
=> Misc c99 style

src/ostree/ot-admin-builtin-set-origin.c
=> cli/set-origin: Port to C99 style

src/ostree/ot-admin-instutil-builtin-grub2-generate.c, src/ostree/ot-builtin-init.c
cmd/init: Port to C99 style
Just keeping up momentum.
---
cmd/grub2-generate: Port to C99 style
Just keeping up momentum.
---
=> Misc c99 style 4

Makefile-tests.am, tests/test-otcore.c
This just stubs out the basic infrastructure, to be expanded upon.
=> tests: Add otcore unit tests

.github/labeler.yml, .github/workflows/labeler.yml
=> ci: Add an automatic labeler action

ci/prow/fcos-e2e.sh, tests/inst/src/composefs.rs, tests/inst/src/insttestmain.rs
Until the XFS fsverity stuff lands.
=> tests: Use ext4, re-enable composefs test

configure.ac
Closes: https://github.com/ostreedev/ostree/issues/3191
=> Release 2024.4

docs/bootloaders.md
Feedback from Alexander Larsson before Linaro Connect talk which used this diagram.
=> docs: make /ostree/root.X clearer as symlinks

Makefile-libostree.am, configure.ac, src/libostree/libostree-devel.sym, src/libostree/libostree-released.sym, tests/test-symbols.sh
Release 2024.7
---
Post-release version bump
---
=> Release 2024.7

tests/test-remote-gpg-list-keys.sh
In GPG 2.2.45, a diagnostic message about the only trusted key having already expired causes this import to produce exit status 2, but the import still succeeds (the key is still revoked).
Bug: https://dev.gnupg.org/T7351  
Bug-Debian: https://bugs.debian.org/1086140
=> tests: Work around GPG 2.2.45 error behaviour when revoking an expired key

configure.ac
Closes: https://github.com/ostreedev/ostree/issues/3360
=> Release 2024.10

tests/test-gpg-verify-result.c
Helps: https://github.com/ostreedev/ostree/issues/3386
---
This does not do anything to solve the test failure, but hopefully it makes it easier to understand.
=> test-gpg-verify-result: Show what the result was before asserting about it

rust-bindings/src/sysroot_deploy_tree_opts.rs
=> rust: Add support for `locked` option for `SysrootDeployTreeOpts`

src/boot/ostree-tmpfiles.conf, src/libostree/ostree-sysroot.c, src/libotcore/otcore.h, tests/kolainst/destructive/unlock-transient.sh
Closes: https://github.com/ostreedev/ostree/issues/3391
=> unlock: Use deployment backing dir

src/switchroot/ostree-prepare-root.c
This is prep for https://github.com/ostreedev/ostree/pull/3420
=> prep patches for: soft-reboot

docs/formats.md, docs/ima.md, docs/index.md, docs/repository-management.md, docs/var.md
=> docs: Some typo and link fixes

src/libostree/ostree-sysroot-deploy.c
Just pass the bits of the new deployment we want down into the checkout function. This lets us reuse the common helper to init a deployment which now always captures the device/inode.
Followup from previous commit.
=> deploy: Don't create deployment object before deploying

Justfile, tests-unit-container/test-prepare-root.sh
This would have caught https://github.com/ostreedev/ostree/issues/3476
=> tests: Add a test case for etc.transient

Justfile, tests-unit-container/test-prepare-root.sh
=> tests: verify /boot mount with prepare root

src/libostree/ostree-soft-reboot.c, src/libotcore/otcore-prepare-root.c, src/libotcore/otcore.h, src/switchroot/ostree-prepare-root.c
Closes: https://github.com/ostreedev/ostree/issues/3486
=> soft-reboot: Also handle /boot
