ostreedev/ostree

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot-deploy.c
- src/libotutil/ot-fs-utils.c
- src/libotutil/ot-fs-utils.h
This is just an efficiency optimization.  We're getting fairly close
to all of the hot code paths using `*at()`.
Note that we end up maintaining a half-duplicate code path set here,
because we still need to support commits from an arbitrary GFile *,
which in a possible common case is an OSTree commit.
I think it's worth it though.
> Use *at() functions for native filesystem commits

- src/libostree/ostree-fetcher.c
- src/libostree/ostree-fetcher.h
- src/libostree/ostree-metalink.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
This addresses items 1 and 2 of https://bugzilla.gnome.org/show_bug.cgi?id=740276
Not sure if we already have item 3 or what would be entailed there.  Testing this was more challenging than the patch itself, and I'm still trying to figure out a good way to induce a large pull on demand.  But from what I could tell the total objects to be downloaded didn't seem to increase once all the metadata was known.
I imagine there's some followup work to be done, but see what you think of this so far.
> Pull metadata objects before content objects

- src/libostree/ostree-core.c
- src/libostree/ostree-core.h
- src/libostree/ostree-fetcher.c
- src/libostree/ostree-fetcher.h
- src/libostree/ostree-metalink.c
- src/libostree/ostree-metalink.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo-static-delta-processing.c
- src/libotutil/ot-checksum-utils.c
- src/libotutil/ot-variant-utils.c
- src/libotutil/ot-variant-utils.h
A small prelude, then a major rework of OstreeFetcher to use dirfd-relative API, leading to a few static deltas fixes.
> fetcher and deltas cleanup

- src/libostree/ostree-gpg-verifier.c
- src/libostree/ostree-gpg-verifier.h
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
Similar to c2b01ad.  For some reason I was thinking the commit data still needed to be written to disk prior to verifying, but it's just another artifact of spawning `gpgv2` (predates using GPGME).
Makes for a nice cleanup in `fetch_metadata_to_verify_delta_superblock()` as well.
> OstreeGpgVerifier: Take the signed data as a GBytes

- src/libostree/ostree-repo.c
- src/libotutil/ot-gpg-utils.c
- src/libotutil/ot-gpg-utils.h
Snagged some handy GPG utilities from Seahorse.
https://git.gnome.org/browse/seahorse/tree/pgp/seahorse-gpgme-data.c
Found a use for `ot_gpgme_data_output()` in our `sign_data()` function, but mainly I need `ot_gpgme_data_input()` for the other GPG branch I'm working on.
> Moar GPG utils

- src/libostree/ostree-repo-pull.c
I noticed xdg-app was looping trying to fetch 1427 refs.  We
don't want to do that unless asked to.
(And also, we need to make static delta requests async)
> pull: Only fetch all refs if we're mirroring

- src/ostree/ot-builtin-commit.c
- src/ostree/ot-dump.c
Previously we were just ignoring this, which hid a bug in
an earlier commit that generated them.
Also change the `commit` program to use both APIs - this
involves extra code, but not too much.
This way, reverting the fix with this on top caused the test suite to
fail.  Adding an active test for this would need a custom test program
using the C API, or adding a cmdline flag to the client, neither of
which quite seemed worth it.
> cmdline: Fatally error if the timestamp in a commit is invalid

- src/ostree/ot-admin-instutil-builtin-grub2-generate.c
The logic for checking which bootversion to use tries to access
sysroot->bootversion if the user didn't specify an explicit bootversion
on the command-line nor through the env var. However, at that point, the
sysroot object is not yet initialized, so it will always return 0, even
when it's 1.
This would cause e.g. `grub2-mkconfig` to have no output for the BLS
entries whenever the entries were under `/boot/loader.1`.
Related: RHBZ1293986
> grub2_generate: load sysroot before using it

- Makefile-man.am
- Makefile-tests.am
- Makefile.am
- configure.ac
- man/rofiles-fuse.xml
- src/rofiles-fuse/Makefile-inc.am
- src/rofiles-fuse/README.md
- src/rofiles-fuse/main.c
- tests/test-rofiles-fuse.sh
While it's not strictly tied to OSTree, let's move
https://github.com/cgwalters/rofiles-fuse in here because:
- It's *very* useful in concert with OSTree
- It's tiny
- We can reuse OSTree's test, documentation, etc. infrastructure
One thing to consider also is that at some point we could experiment
with writing a FUSE filesystem for OSTree.  This could internalize a
better equivalent of `--link-checkout-speedup`, but on the other hand,
the cost of walking filesystem trees for these types of operations is
really quite small.
But if we did decide to do more FUSE things in OSTree, this is a step
towards that too.
> Import rofiles-fuse

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/libtest.sh
If ostree is run in a test setup where it operates as root in a tmp
directory, it might cause issues to flag the deployments as immutable.
The test harness might simply be doing an `rm -rf` (effectively the case
for gnome-desktop-testing-runner), which will then fail.
We add a new debug option to the ostree_sysroot object using GLib's
GDebugKey functionality to allow our tests to communicate to ostree that
we don't want immutable deployments.
> ostree-sysroot: add debug option to help testing

- Makefile-tests.am
- apidoc/ostree-sections.txt
- src/libostree/libostree.sym
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- src/libostree/ostree-sysroot.h
- tests/libostreetest.c
- tests/libostreetest.h
- tests/test-basic-c.c
- tests/test-sysroot-c.c
This will allow daemons like rpm-ostree to detect if there are any new
deployments efficiently, in combination with using inotify.  If there
are any changes, rpm-ostree wants publish them on DBus.
While we're here, add some changes to start doing unit C testing of
the sysroot API.
> lib: Add ostree_sysroot_load_if_changed() API

- tests/basic-test.sh
%Z only uses seconds, so it's possible that we did the commit
in the same second, which made this test racy.
- Switch to full nanosecond precision using '%.Y' so it always differs
- Fix the inverted `cmp` usage
- Add a missing `ok`
> tests/basic: Fix race in timestamp test

- Makefile-tests.am
Otherwise $(installed_testdir) is empty so we try to put content in
`/`, which I noticed when trying to build an RPM (it works works fine
`sudo make install`).
> build: Don't install test data without --enable-installed-tests

- src/libostree/ostree-repo.c
This code was always downloading the summary even for a cache hit due
to a missing else.
> repo: Fix the skip-summary-if-summary.sig-is-same cache

- README.md
- docs/CONTRIBUTING.md
- docs/manual/adapting-existing.md
- docs/manual/atomic-upgrades.md
- docs/manual/deployment.md
- docs/manual/formats.md
- docs/manual/introduction.md
- docs/manual/repo.md
I was going through the new version of the docs and noticed a few
problems.  Mostly URLs that aren't linked, extra whitespace, and a few
mis-spellings.
I ran the files through `aspell check` and made some manual changes
myself.
These changes were tested locally with `mkdocs serve`
> docs: Cleanup Markdown

- Makefile-tests.am
- tests/admin-test.sh
- tests/test-libarchive-import.c
Alex pointed me at https://anonscm.debian.org/git/collab-maint/ostree.git/tree/debian/patches - they're all fine, and should be upstream.
> Upstreaming debian patches

- src/ostree/ot-admin-builtin-switch.c
Spotted by jlebon in https://github.com/GNOME/ostree/pull/211
> admin-switch: Add missing reboot argument

- .travis.yml
This is at the moment just so that we can use Homu.  In the future I'd
like to make travis just one of multiple PR testers we use.
> Add a stub .travis.yml

- src/ostree/ot-builtin-trivial-httpd.c
I was briefly looking at building with clang mostly since it
detects unused variables with cleanup attributes, but then
I hit this fatal error.
It's a hard compile error with `-Wformat-nonliteral` since clang
doesn't know it's a format string.
> trivial-httpd: Add __attribute__((format))

- ci/build-check.sh
It may not exist in OpenShift Prow by default.
> ci: Make ${ARTIFACTS} directory

- OWNERS
I tried to balance reflecting the reality of who works on libostree
today with keeping some of the existing committers - particularly
committers from multiple organizations.
Part of switching libostree over to OpenShift Prow.
> OWNERS: New file

- src/libostree/ostree-repo-checkout.c
Got this error when trying to rebase libostree in RHEL:
```
Error: CLANG_WARNING: [#def1]
libostree-2019.2/src/libostree/ostree-repo-checkout.c:375:21: warning: Access to field 'disable_xattrs' results in a dereference of a null pointer (loaded from variable 'repo')
```
I think what's happening is it sees us effectively testing
`if (repo == NULL)` via the `while (current_repo)`.  Let's
tell it we're sure it's non-null right after the loop.
> libostree: Add an assert to pacify clang-analyzer

- Makefile-ostree.am
- Makefile.am
- ci/build.sh
- ci/travis-build.sh
- configure.ac
When building without --enable-trivial-httpd-cmdline, don't build or install
the ostree-trivial-httpd binary.
> Gate ostree-trivial-httpd on BUILDOPT_TRIVIAL_HTTPD

- .papr.yml
Same as https://github.com/coreos/rpm-ostree/pull/1923
Quoting that rationale:
> Since we're not using Homu anymore (and Tide instead looks at
> all statuses by default), let's just drop it. This brings down the
> number of statuses on PRs by one more (and so one less context to
> override when needed).
> ci: Trim PAPR config to drop required flag

- src/libostree/ostree-repo.c
In glib 2.62 this has been changed to emitting a warning. Use G_STRFUNC
instead, which has been available for a long time and is already used in
other places in ostree.
> repo: Stop using deprecated G_GNUC_FUNCTION

- Makefile-ostree.am
- Makefile.am
- ci/build.sh
- ci/travis-build.sh
- configure.ac
`--enable-trivial-httpd-cmdline` is only supposed to disable the `ostree` command, not stop build or installation of the ostree-trivial-httpd binary. Revert the changes to go back to the original behaviour.
> Revert trivial httpd changes (#1912)

- Makefile-man.am
- configure.ac
This way it's clearer the option is only about the CLI entrypoint
also living in `ostree trivial-httpd`.
Co-authored-by: Jonathan Lebon <jonathan@jlebon.com>
> build-sys: Rename internal conditionals for trivial-httpd

- tests/test-export.sh
If we are built without libarchive support, this test fails:
error: This version of ostree is not compiled with libarchive support
...
ERROR: tests/test-export.sh - too few tests run (expected 5, got 0)
ERROR: tests/test-export.sh - exited with status 1
Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
> tests/export: Guard with check for libarchive

- src/boot/grub2/grub2-15_ostree
In this case this is reverted in Fedora; I don't like carrying downstream patches.  Let's revert it here, and I added a different approach.
> Revert grub2 exit, add new grub2: Honor /boot/.grub2-bls-enabled 

- src/libostree/ostree-async-progress.c
See https://gitlab.gnome.org/GNOME/glib/commit/71973c722
> async-progress: Plug memory leak while destroying GSource

- src/libostree/ostree-sysroot-deploy.c
- tests/libtest.sh
- tests/test-admin-deploy-none.sh
To allow for FIPS mode, we need to also install the HMAC file from
`/usr/lib/modules` to `/boot` alongside the kernel image where the
`fips` dracut module will find it. For details, see:
https://github.com/coreos/fedora-coreos-tracker/issues/302
Note I didn't include the file in the boot checksum since it's itself a
checksum of the kernel, so we don't really gain much here other than
potentially causing an unnecessary bootcsum bump.
> lib/deploy: Also install HMAC file into /boot

- tests/libtest-core.sh
A number of tests expect explicit left/right single quotes in their
messages, which will never happen in the C locale. Change the fallback
to en_US.UTF-8 as the most likely next option to be present, or fail if
we can't find one of these locales.
Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
> tests/core: Fallback to en_US.UTF-8 locale

- tests/libtest-core.sh
- tests/libtest.sh
- tests/pull-test.sh
- tests/test-admin-gpg.sh
- tests/test-pull-mirrorlist.sh
When running under musl rather than glibc, the tests fail because of minor differences. There's three commits here
* the first is straightforward (handle EPIPE with some `|| true` additions)
* the second is possibly more contentious (default to C.UTF-8 as the locale command doesn't exist)
* third looks like a problem somewhere between coreutils and musl and this is simply a workaround for someone elses problem - I could see you not wanting this one...
> Fix tests with musl

- Makefile-boot.am
- Makefile-decls.am
- Makefile-switchroot.am
ostree_boot_SCRIPTS was being set on both Makefile-boot.am and
Makefile-switchroot.am, causing the first one to be replaced by the
other at the final Makefile, so declare as empty and append on both
places instead.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> Makefile: declare ostree_boot_SCRIPTS and append values

- src/libotutil/ot-keyfile-utils.c
- tests/test-keyfile-utils.c
Prep for fsverity, where I want to create a new group
`[fsverity]` in the keyfile that has default values.  We should
treat the absence of a group the same as absence of a key
in these "with defaults" APIs.
> lib/keyfile: Treat "group not found" the same as "key not found"

- buildutil/glib-tap.mk
When `--disable-dependency-tracking` is in effect with separate build
directory, the tests directory isn't created as a result of the
dependency generation, which leads to a build race for the tests
directory being created and failures:
```
Making all in .
make[2]: Entering directory 'TOPDIR/build/tmp/work/riscv64-yoe-linux-musl/ostree/2019.5-r0/build'
(echo '[Test]' > tests/test-local-pull-depth.sh.test.tmp; \
echo 'Type=session' >> tests/test-local-pull-depth.sh.test.tmp; \
echo 'Exec=env G_TEST_SRCDIR=/usr/libexec/installed-tests/libostree G_TEST_BUILDDIR=/usr/libexec/installed-tests/libostree /usr/libexec/installed-tests/libostree/test-local-pull-depth.sh' >> tests/test-local-pull-depth.sh.test.tmp; \
mv tests/test-local-pull-depth.sh.test.tmp tests/test-local-pull-depth.sh.test) …
```
> build: create tests directory for split builds

- src/libostree/ostree-kernel-args.c
- src/libostree/ostree-kernel-args.h
- tests/test-admin-deploy-karg.sh
- tests/test-kargs.c
Define an `OstreeKernelArgsEntry` structure, which holds
both the key and the value. The kargs order array stores
entries for each key/value pair, instead of just the keys.
The hash table is used to locate entries, by storing
entries in a pointer array for each key. This preserves
ordering information about each key/value pair when
appending/replacing/deleting kargs, and maintains the
same public interface.
Fixes: #1859
---
Proposing this as an approach for #1859 . `tests/test-kargs.c` worked locally. Letting `tests/test-admin-deploy-karg.sh` run in CI as a seemingly unrelated error occurred in my local container `error: Cleaning deployments: ioctl(EXT2_IOC_GETFLAGS): Bad file descriptor`. Not yet manually verified when installed with `rpm-ostree` - leaving WIP for now.
> lib/kernel-args: Store kernel args as key/value entries

- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
- src/libostree/ostree-async-progress.c
- src/libostree/ostree-async-progress.h
This allows copying the state from one OstreeAsyncProgress object to
another, atomically, without invoking the callback. This is needed in
libflatpak, in order to chain OstreeAsyncProgress objects so that you
can still receive progress updates when iterating a different
GMainContext than the one that the OstreeAsyncProgress object was
created under.
> libostree: Add ostree_async_progress_copy_state()

- tests/test-repo-finder-mount.c
This fixes running this test case inside
https://github.com/cgwalters/coretoolbox
> tests/repo-finder: Run realpath() on /tmp

- Makefile-ostree.am
When building outside of source tree it can happen that src/ostree/
does not exist (yet) when bison is called. This leads to an build
error like so:
bison: src/ostree/parse-datetime.c: cannot open: No such file or directory
Make sure that src/ostree/ exists when parse-datetime.c is built.
> Avoid race condition when building outside of source tree

- README.md
BuildStream no longer uses libostree internally (see
https://gitlab.com/BuildStream/buildstream/issues/387). It still
has first class support for interoperating with libostree repos.
> README.md: Tweak text about BuildStream

- Makefile-switchroot.am
- apidoc/ostree-sections.txt
- src/boot/ostree-remount.service
- src/libostree/libostree-devel.sym
- src/libostree/ostree-impl-system-generator.c
- src/libostree/ostree-sysroot-cleanup.c
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- src/libostree/ostree-sysroot.h
- src/ostree/ot-admin-builtin-finalize-staged.c
- src/ostree/ot-main.c
- src/switchroot/ostree-remount.c
Add a magic file and an API for consumers to tell us it's OK
for us to remount read-write (since it'll just affect our
mount namespace).
> Support mounting /sysroot (and /boot) read-only

- tests/test-switchroot.sh
When running with installed tests, ostree-prepare-root (probably) exists in /usr/lib. Add heuristics to look for it based on the directory we're running from.
> test-switchroot.sh: Find ostree-prepare-root in installed tests

- configure.ac
- tests/libtest.sh
- tests/test-switchroot.sh
If running with systemd and libmount then /var mounting is deferred for systemd. Skip the relevant tests in this case as it will always fail.
Fixes: #1983
> Skip /var test if running with systemd and libmount

- tests/libtest-core.sh
The case-ignoring regex `^(C|en_US)` will match any locale that starts
with `c`. On my system this is `ca_AD.utf8`, which breaks the test
suite. Instead, use a single regex that includes the joining `.` rather
than 2 separate regexes. This also changes `head` to use the `-n`
option, which has been preferred for at least 10 years in the coreutils
version and is supported by busybox as well.
> tests/core: Really pick C.UTF-8 locale

- ci/rpmostree.sh
The vmcheck tests in 2019.3 fail because of an SSH control socket issue
on overlayfs. This is fixed in 2019.4[1]. That has some other changes
such as using Python 3 in tests. The package dependencies have been
synced from the rpm-ostree CI for that.
Unfortunately, this is no longer a totally representative test of f29
since it has 2019.3 in updates. But that's the price you pay for
exercising someone else's CI from your own CI.
1. https://github.com/coreos/rpm-ostree/commit/c89f81c1385ef095616b0e7001926572a20057b2
> ci/rpmostree: Bump to 2019.4

- src/ostree/ostree-trivial-httpd.c
When --autoexit is used with --daemonize and --log-file, the program
never exits when the root directory is deleted. I believe what happens
is that g_file_new_for_path triggers the glib worker context to be
started to talk to GVfs. Once the program forks, the parent exits and
the thread iterating the worker context is gone. The file monitor then
never receives any events because the inotify helper also runs from the
worker context.
Move the fork earlier just after parsing and validating the command line
arguments. In order to handle setup errors in the child, a pipe is
opened and the parents waits until the child writes a status byte to it.
If the byte is 0, the parent considers the child setup successful and
exits and the child carries on as a daemon. Notably, the child doesn't
reopen …
> ostree/trivial-httpd: Fix --autoexit with --daemonize and --log-file

- Makefile-libostree.am
- configure.ac
17db0f15a798 ("configure: add option for libsystemd") exposed
--without-libsystemd to allow systemd to be disabled even if the systemd
pkgconfig script was present, introducing a new variable
with_libsystemd; there are now three, almost identical variables:
- with_libsystemd [yes, no, maybe] - controlled by --without-libsystemd,
resolved into yes/no by the initial checks
- have_libsystemd [yes, no, <undefined>] - only set if with_libsystemd
is yes/maybe, otherwise undefined
- with_systemd [yes, <undefined>] - yes if have_systemd is yes,
otherwise undefined
with_systemd is the earliest variable and was previously set by a set of
checks for dracut and mkinitcpio. These checks were changed for a
systemd check in 9e2763106be0 ("lib: Use sd_journal directly
(optionally)"). This commit also …
> build: fix systemd feature advertisement

- configure.ac
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot-deploy.c
Using [fs-verity](https://www.kernel.org/doc/html/latest/filesystems/fsverity.html) is natural for OSTree because it's file-based,
as opposed to block based (like [dm-verity](https://www.kernel.org/doc/html/latest/admin-guide/device-mapper/verity.html)).  This only covers
files - not symlinks or directories.  And we clearly need to
have integrity for the deployment directories at least.
More background on fs-verity:
- https://lwn.net/Articles/763729/
- https://lwn.net/Articles/752614/
So making this truly secure would need a lot more work.  Nevertheless,
I think it's time to start experimenting with it.  Among other things,
it does *finally* add an API that makes files immutable, which will
help against some accidental damage.
> Initial fs-verity support

- .travis.yml
There are new major LTS environments out; bump up to the latest
for each and drop the old Ubuntu trusty.  Part of cleaning up
our CI.
> travis: Update debian/ubuntu environments

- docs/manual/adapting-existing.md
The referenced fragment name has changed in the published rpm-ostree docs.
Fix it.
Also, it seems ostree's readthedocs content is out of date, b35f337dc7c
is from May 2019 but the published content doesn't contain that fix
> docs: Fix 'package layering' rpm-ostree link

- src/libostree/ostree-linuxfsutil.c
For some reason I haven't fully debugged (probably a recent
kernel change), in the case where the immutable bit isn't set,
trying to call `EXT2_IOC_SETFLAGS` without it set returns `EINVAL`.
Let's avoid calling the `ioctl()` if we don't have anything to do.
This fixes a slew of `make check` failures here in my toolbox
environment.
(kernel is `5.5.0-0.rc6.git0.1.fc32.x86_64` with `xfs`)
> deploy: Avoid trying to change immutable state unnecessarily

- man/ostree-pull.xml
Adds information into description section of `ostree pull` command about pulled refs - where they are stored and how they can be accessed in OSTree commands.
> Update ostree-pull.xml with info about pulled refs location and access

- src/libostree/ostree-core-private.h
- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo-refs.c
- src/libostree/ostree-repo-static-delta-compilation.c
- src/libostree/ostree-repo.c
For repo structure directories like `objects`, `refs`, etc... we should
be more permissive and let the system's `umask` narrow down the
permission bits as wanted.
This came up in a context where we want to be able to have read/write
access on an OSTree repo on NFS from two separate OpenShift apps by
using supplemental groups[1] so we don't require SCCs for running as the
same UID (supplemental groups are part of the default restricted SCC).
[1] https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/persistent_storage_nfs.html#nfs-supplemental-groups
> lib/repo: Create repo directories as 0775

- src/libostree/ostree-core.c
- src/libostree/ostree-core.h
- src/libostree/ostree-gpg-verify-result.h
- src/libostree/ostree-sysroot.c
These had been added assuming 2019.7 would be the next version, but now
it's 2020 and there's been a release. In the case of
`OstreeCommitSizesEntry`, I'd forgotten to move it forward from 2019.5
to 2019.7 in the time between when I started working on the feature and
it landed.
> lib: Fix Since versions for 2020.1

- configure.ac
- src/libostree/libostree-released.sym
- tests/test-symbols.sh
"Brown paper bag" release that actually sets the
`is_release_build=yes` flag and also fixes the
`Since:` on a few new functions.
> Release 2020.2

- .cci.jenkinsfile
We were using `--no-test-exit-error` for upgrade tests but weren't
actually checking for test failures after.
Instead of running kola directly, just use the `fcosKola` custom step
which automatically takes care of e.g. running tests in parallel and
archiving results.
> ci: use `fcosKola` for running kola tests

- src/ostree/ot-main.c
See https://github.com/coreos/fedora-coreos-tracker/issues/343
When we added the read-only sysroot support it broke using "raw"
`ostree pull` and `ostree refs --create` and all of the core repo
CLIs that just operate on a repo and not a sysroot.
Fixing this is a bit ugly as it "layer crosses" things even more.
Extract a helper function that works in both cases.
> main: Also automatically remount rw /sysroot for `ostree pull` etc.

- configure.ac
Let's do another release to get the `sysroot.readonly` fixes into FCOS
and unpin ostree and rpm-ostree there.
> Release 2020.3

- man/ostree-diff.xml
- src/ostree/ot-builtin-diff.c
> bin/diff: Clarify documentation around REV and DIR syntax

- src/libostree/ostree-repo-pull.c
- tests/test-local-pull-depth.sh
When pulling full parent commits via e.g. `--depth N`, we weren't
unmarking them as partial in the out path.
Closes: #2035
> lib/pull: Don't leave commits pulled by depth as partial

- src/libostree/ostree-fetcher-util.c
Add G_IO_ERROR_PARTIAL_INPUT to the list of error codes caused by
transient networking errors which lead us to retry the request. When
attempting to install the spotify flatpak you often get the error
message "Connection terminated unexpectedly" and the download of the deb
file fails. In this case, libsoup is setting G_IO_ERROR_PARTIAL_INPUT
and sometimes a subsequent download attempt is successful, so we should
treat it as transient.
Ideally we would behave as wget does in this case and retry the download
picking up where we left off in the file rather than starting over, but
that would require changes to libsoup I think.
Sadly this patch does not fix the flatpak installation of spotify in the
face of such errors, because flatpak doesn't use libostree to download
extra data, but …
> lib/fetcher-util: retry download on G_IO_ERROR_PARTIAL_INPUT

- tests/test-pull-repeated.sh
This test keeps occasionally failing in CI - as expected, because
we retry 8 times for an object but it's completely possible for
us to hit the <0.5% chance of 50% failure 8 times in a row.
Since the max errors from the server is 100, set retries to the
same thing.
> tests/pull-repeated: Bump up retries to match max fails

- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot.c
Noticed this while writing tests for a core `ostree_sysroot_load()`
entrypoint.  And decided to do the same for `ostree_repo_open()`,
and while there also noted we had a duplicate error prefixing
for the open (more recently `glnx_opendirat()` automatically
prefixes with the path).
> lib: Add error prefixing for sysroot load and repo open

- man/ostree-find-remotes.xml
- src/libostree/ostree-repo-pull.c
- src/ostree/ot-builtin-find-remotes.c
- tests/test-pull-collections.sh
Spotted this bug from reading the code; I haven't seen it in the wild.
> Don't copy summary for collection-ref mirror subset pulls

- src/libostree/ostree-sysroot.c
No functional changes; prep for a future patch
which will load the "live" deployment rather than
reading the bootloader configs.
> sysroot: Reorganize sysroot load code a bit

- src/libostree/ostree-repo-finder-avahi.c
Kind of a mild typo, but it caused the Rust bindings generator to produce broken code because the "Since" tag didn't work.
> lib: fix typo in function docs

- src/libostree/ostree-repo-deprecated.h
- src/libostree/ostree-repo.h
Just noticed these while doing a build.
> lib: Squash two gtk-doc warnings

- src/boot/grub2/grub2-15_ostree
This is another attempt to avoid having duplicated menu entries caused by
GRUB having support to parse BLS snippets and the 15_ostree script adding
menu entries as well.
The previous attempt was in commit 985a1410029 ("grub2: Exit gracefully if
the configuration has BLS enabled") but that lead to users not having menu
entries at all, due having an old GRUB version that was not able to parse
the BLS snippets.
This happened because the GRUB bootloader is never updated in the ESP as
a part of the OSTree upgrade transaction.
The logic is similar to the previous commit, the 15_ostree script exits if
able to determine that the bootloader can parse the BLS snippets directly.
But this time it will not only check that a BLS configuration was enabled,
but also that a …
> grub2: Don't add menu entries if GRUB supports parsing BLS snippets

- src/libostree/ostree-repo-pull.c
If GPG support is disabled in a build time we should to check if any of
options "gpg_verify" or "gpg_verify_summary" is set to TRUE instead
of checking if they are passed via options while pulling from remote.
Fixed the failure with assertion of `ostree find-remotes --pull --mirror`
calling (`tests/test-pull-collections.sh`) if libostree has been compiled
without GPG support.
> lib/repo-pull: fix GPG check while pulling remote

- src/libostree/ostree-repo-pull.c
- tests/test-signed-pull.sh
This code wasn't written with idiomatic GError usage; it's not standard
to construct an error up front and continually append to its
message.  The exit from a function is usually `return TRUE`,
with error conditions before that.
Updating it to match style reveals what I think is a bug;
we were silently ignoring failure to parse key files.
> pull: Update key loading function to match error style

- src/libostree/ostree-sign-dummy.c
- tests/test-signed-commit.sh
- tests/test-signed-pull-summary.sh
- tests/test-signed-pull.sh
I don't want to even have to think about people using
this in production.
> Only enable "dummy" signature type with opt-in env variable

- .cci.jenkinsfile
This was changed recently and broke us since we do explicitly call
`fcosKola` instead of implicitly via `fcosBuild`. Adapt to the new
semantics.
> ci: Adapt to use new fcosKola semantics

- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-sign-ed25519.c
- tests/test-local-pull.sh
- tests/test-signed-pull-summary.sh
- tests/test-signed-pull.sh
Rework this to use standard error handling - we fail fast if
we can't load the public keys for example.  Preserve
the semantics of accepting the first valid signature.  The
first signature error is captured, the others are currently
compressed into a `(and %d more)` prefix.
And now that I look at this more closely there's a lot of
duplication between the two code paths in pull.c for verifying;
will dedup this next.
> pull: Cleanup signature verification functions

- .cci.jenkinsfile
The goal is to test "no options" build - and eventually tests.
(We're not actually including libsodium in the cosa buildroot right
now, but we may in the future)
> ci: Build minimal without libsodium too

- configure.ac
- tests/libtest.sh
- tests/test-local-pull.sh
- tests/test-signed-commit.sh
- tests/test-signed-pull-summary.sh
- tests/test-signed-pull.sh
`libsodium` is an implementation detail.  In particular, I'd like
to consider using OpenSSL for ed25519 (if libsodium isn't configured
and openssl is).
So switch the name of the exposed feature and adjust the tests.
> Use `sign-ed25519` for the feature name

- .travis.yml
- ci/travis-Dockerfile.in
- ci/travis-build.sh
- ci/travis-install.sh
As far as I can tell we're not gating on this right now.  From
a quick glance, it looks like Debian stable has `libsodium-dev`
but only Ubuntu eoan does which we're not testing right now.
> travis: Add some libsodium coverage

- tests/test-signed-commit.sh
Commit e474033e removed the redirection of incorrect public keys
aimed to generate a lot of files without correct public signature.
Fix the test by returning back the creation of files containing
incorrect public keys for ed25519.
Signed-off-by: Denis Pynkin <denis.pynkin@collabora.com>
> tests/signed-commit: fix the test of well-known places

- src/libostree/ostree-cmdprivate.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
`ostree-repo-pull.c` is rather monstrous; I plan to split it
up a bit.  There's actually already a `pull-private.h` but
that's just for the binding verification API.  I think that one
isn't really pull specific.  Let's move it into the "catchall"
`repo.c`.
> lib: Move internal binding verification API to repo.c

- .travis.yml
- configure.ac
As follow up of #2072
Use option `--with-ed25519-libsodium` instead of
`--with-libsodium` to enable ed25519 signature engine.
This allows to use later different implementations of ed25519
signing/verification. For instance, based on openssl.
Signed-off-by: Denis Pynkin <denis.pynkin@collabora.com>
> sign: rename option for enabling ed25519

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
I've only noticed this by inspection. But I think it's possible for
`cleanup_txn_dir` to get called with the `staging-...-lock` file since
it matches the prefix.
Make the checking here stronger by verifying that it's a directory. If
it's not a directory (lockfile), then follow the default pruning expiry
logic so that we still cleanup stray lockfiles eventually.
> lib/commit: Check that dirent is a directory before cleaning 

- Makefile-libostree.am
- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull-verify.c
- src/libostree/ostree-repo-pull.c
`ostree-repo-pull.c` is huge; separate some of the GPG/signing
verification functions into their own file so they're more easily seen.
>  lib: Move gpg/signapi bits into ostree-repo-pull-verify.c

- .cci.jenkinsfile
- Makefile-tests.am
- src/ostree/ot-admin-builtin-deploy.c
- tests/test-admin-deploy-nomerge.sh
All of the underlying libostree APIs have supported passing `NULL`
for a merge deployment for...a long time.  But we never plumbed
it up into the CLI.
Add a `--no-merge` option to aid people who want to do a "factory reset":
https://github.com/ostreedev/ostree/issues/1793
> deploy: Add --no-merge

- src/boot/ostree-finalize-staged.service
Same motivation as
https://github.com/coreos/rpm-ostree/pull/2060
I tried `InaccessiblePaths=/var` first and was very sad to find
out we have one tiny exception that breaks it.  Otherwise it'd
be so elegant.  Maybe in the future we split out that one thing
to a separate `ostree-finalized-stage-var.service` that's just
`ExecStart=/bin/rm -vf /var/.updated` and is otherwise
`ProtectSystem=strict` etc.
> finalize-staged: Add ProtectHome=yes and ReadOnlyPaths=/etc

- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
Explicitly expose functions for querying the metadata format
and key name used by OstreeSign object:
- ostree_sign_metadata_format
- ostree_sign_metadata_key
This allows to use the same metadata format and key name
by 3-rd party applications using signapi.
I thought there is no need to use them externally but we have at least one case then it helps to avoid duplication of name and format in code.
> signapi: expose metadata format and key

- tests/kola/destructive/staged-deploy.sh
I'm using [cosa build-fast](https://github.com/coreos/coreos-assembler/pull/1371)
and this test doesn't like starting out with two deployments.  Clean
things up to one at the start just to simplify things.
> tests/staged-deploy: Cleanup initial state

- src/libostree/ostree-sign.c
- src/libostree/ostree-sign.h
- src/ostree/ot-builtin-commit.c
- src/ostree/ot-builtin-sign.c
- src/ostree/ot-builtin-summary.c
Using `#define` or constants instead of strings helps avoid
typos and encourages documentation.
> signing: Add #define OSTREE_SIGN_NAME_ED25519

- src/ostree/ot-builtin-commit.c
- tests/basic-test.sh
I think we should encourage removing the writable bits from
executables.  This has happened to me:
https://thomask.sdf.org/blog/2019/11/09/take-care-editing-bash-scripts.html
And not having the writable bit may help prevent hardlink
corruption with OSTree in some cases.
We can't do this by default, but add a convenient CLI flag
for it.
> commit: Add --mode-ro-executables

- src/boot/ostree-prepare-root.service
With just `After=` we'll still try to run in the scenario
where `sysroot.mount` fails because the rootfs didn't appear.
And this will end up spewing an error which can confuse people
into thinking something is wrong at the ostree level.
This has come up numerous times w/{Fedora,RHEL} CoreOS, most
recently while looking at
https://bugzilla.redhat.com/show_bug.cgi?id=1803130
> ostree-prepare-root: Requires=sysroot.mount

- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
- src/libostree/ostree-repo-pull-verify.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-sign.c
- src/libostree/ostree-sign.h
This cleans up the verification code; it was weird how
we'd get the list of known names and then try to create
an instance from it (and throw an error if that failed, which
couldn't happen).
> signing: Change API to create instances directly

- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull-verify.c
- src/libostree/ostree-repo-pull.c
Previously in the pull code, every time we went to verify
a commit we would re-initialize an `OstreeSign` instance
of each time, re-parse the remote configuration
and re-load its public keys etc.
In most cases this doesn't matter really because we're
pulling one commit, but if e.g. pulling a commit with
history would get a bit silly.
This changes things so that the pull code initializes the
verifiers once, and reuses them thereafter.
This is continuing towards changing the code to support
explicitly configured verifiers, xref
https://github.com/ostreedev/ostree/issues/2080
> pull: Further cleanup signapi verification

- src/boot/ostree-finalize-staged.service
In https://bugzilla.redhat.com/show_bug.cgi?id=1827712
some OpenShift CI is seeing `/boot` being unmounted before
`ostree-finalize-staged.service` runs or completes.
We finally tracked this down to a bug elsewhere, but
I think we should add this because it clearly shows
our requirements.
> finalize: Add RequiresMountsFor=/boot too

- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-sysroot-upgrader.c
- src/ostree/ot-builtin-pull.c
- tests/admin-test.sh
- tests/pull-test.sh
The way `timestamp-check` works might be too restrictive in some
situations. Essentially, we need to support the case where users want to
pull an older commit than the current tip, but while still guaranteeing
that it is newer than some even older commit.
This will be used in Fedora CoreOS. For more information see:
https://github.com/coreos/rpm-ostree/pull/2094
https://github.com/coreos/fedora-coreos-tracker/issues/481
> lib/pull: Add `timestamp-check-from-rev`

- .cci.jenkinsfile
- Makefile-tests.am
- tests/kola/Makefile
This builds on
https://github.com/coreos/coreos-assembler/pull/1441
to install our tests rather than running them from the source
directory.  This model will more cleanly allow us to ship
our tests along with a test container or elsewhere, separate
from the source directory.
Also prep for https://github.com/ostreedev/ostree/pull/2048
> ci: Install kola tests

- src/libostree/ostree-repo-pull.c
- src/ostree/ot-builtin-pull-local.c
- tests/test-local-pull.sh
There's a lot of historical baggage associated with GPG verification
and `ostree pull` versus `ostree pull-local`.  In particular nowadays,
if you use a `file://` remote things are transparently optimized
to e.g. use reflinks if available.
So for anyone who doesn't trust the "remote" repository, you should
really go through through the regular
`ostree remote add --sign-verify=X file://`
path for example.
Having a mechanism to say "turn on signapi verification" *without*
providing keys goes back into the "global state" debate I brought
up in https://github.com/ostreedev/ostree/issues/2080
It's just much cleaner architecturally if there is exactly one
path to find keys: from a remote config.
So here in contrast to the GPG code, for `pull-local` we explictily
disable signapi validation, and …
> pull: Only have API to disable signapi for local pulls

- tests/admin-test.sh
- tests/libtest.sh
I saw `tests/test-admin-deploy.none.sh` fail in one CI run, and
I want to check if it was because of clock skew, so fail
fast if we detect that.
xref https://github.com/ostreedev/ostree/pull/2099#issuecomment-629805375
> ci: Test for clock skew

- tests/admin-test.sh
In a CI run I think one of these `ostree show` commands is failing.
While that output would be useful, the actual `err.txt` usually
has what we want too.
> admin-test: Show err.txt on unexpected failure

- tests/admin-test.sh
Otherwise the new check we added there to verify that upgrading without
`--allow-downgrade` fails itself fails.
See: https://github.com/ostreedev/ostree/pull/2099#issuecomment-629805840
> tests/admin-test: Ensure that commits are 1s apart

- src/switchroot/ostree-remount.c
We're hitting issues with the read-only remounts racing with various
services coming up. Let's neuter it for now until we rework how it
works.
See: https://github.com/coreos/fedora-coreos-tracker/issues/488
> switchroot/remount: Neuter sysroot.readonly for now

- tests/admin-test.sh
We were doing a check to verify that `ostree admin upgrade` wouldn't
accept a downgrade without `--allow-downgrade`. However, there's no
guarantee that the commit it's upgrading from is older than HEAD^ (what
we're upgrading to). Specifically, if the test runs fast enough, the
timestamps could be equal, since the lowest resolution is seconds.
Rework the test so that we first upgrade to HEAD, which we're sure is at
least 1 second apart from HEAD^, and *then* check that downgrade
protection is enforced.
We also can't use `rev-parse testos/buildmaster/x86_64-runtime` as a way
to know what commit the host is sitting on since the ref might've gone
ahead. Instead, just use `ostree admin status | head -n1`. (I played
with using the `ostree/I/J/K` refs, but those depend on what the …
> tests/admin-test: Fix --allow-downgrade check

- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull-verify.c
- src/libostree/ostree-repo-pull.c
- tests/test-signed-pull.sh
The goal here is to move the code towards a model
where the *client* can explicitly specify which signature types
are acceptable.
We retain support for `sign-verify=true` for backwards compatibility.
But in that configuration, a missing public key is just "no signatures found".
With `sign-verify=ed25519` and no key configured, we can
explicitly say `No keys found for required signapi type ed25519`
which is much, much clearer.
Implementation side, rather than maintaining `gboolean sign_verify` *and*
`GPtrArray sign_verifiers`, just have the array.  If it's `NULL` that means
not to verify.
Note that currently, an explicit list is an OR of signatures, not AND.
In practice...I think most people are going to be using a single entry
anyways.
> pull: Add support for sign-verify=<list>

- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root.c
- src/switchroot/ostree-remount.c
We recently disabled the read-only /sysroot handling:
https://github.com/ostreedev/ostree/pull/2108/commits/e35b82fb891daee823fcce421ae8f1442b630ea2
The core problem was that a lot of services run early in the
real root and want write access to things like `/var` and `/etc`.
In trying to do remounts while the system is running we introduce
too many race conditions.
Instead, just make the `/etc` bind mount in the initramfs right
after we set up the main root.  This is much more natural really,
and avoids all race conditions since nothing is running in the
sysroot yet.
The main awkward part is that since we're not linking
`ostree-prepare-root` to GLib (yet) we have a hacky parser
for the config file.  But, this is going to be fine I think.
In order to avoid parsing the config twice, pass …
> Move ro /sysroot bind mount of /etc into initramfs

- src/libostree/ostree-repo-pull.c
One OpenShift user saw this from rpm-ostree:
```
client(id:cli dbus:1.583 unit:machine-config-daemon-host.service uid:0) added; new total=1
Initiated txn UpdateDeployment for client(id:cli dbus:1.583 unit:machine-config-daemon-host.service uid:0): /org/projectatomic/rpmostree1/rhcos
Txn UpdateDeployment on /org/projectatomic/rpmostree1/rhcos failed: File header size 4294967295 exceeds size 0
```
which isn't very helpful.  Let's add some error
prefixing here which would at least tell us which
object was corrupted.
> lib: Add error prefixing with specific object when loading

- rust/.gitignore
- rust/src/bupsplit.rs
Let's use the standard rustfmt style.
Also remove unused parenthesis which rust-analyzer was complaining
about.
Also add a `.gitignore`.
> bupsplit: rustfmt(*)

- man/ostree-checkout.xml
- src/ostree/ot-builtin-checkout.c
This merge request adds all missing options to the checkout man page. There is actually one mistake which really confused me (`-u` for `--user-mode`) which I kept in a separate commit.
> Improve checkout man page

- src/libostree/ostree-core.h
Add a standard key for this.  We actually had a case in OpenShift
builds recently where a ppc64le image was pushed over an `x86_64`
one and this started failing at runtime with a not immediately
obvious error.
I'll probably end up changing rpm-ostree at least to use
the RPM architecture for this key and fail if it doesn't match
the booted value.
Possibly that should live in ostree but it would involve adding
architecture schema here, which gets into a big mess.  Let's
just standardize the key.
> core: Add OSTREE_COMMIT_META_KEY_ARCH

- src/libostree/ostree-sign-ed25519.c
- tests/test-pre-signed-pull.sh
- tests/test-signed-commit.sh
- tests/test-signed-pull-summary.sh
To aid debuggability, when we find a commit that isn't signed
by our expected key, output a specific error message with the
key.
(And then add code to switch to just printing the count beyond 3
because the test suite injects 100 keys and hopefully no one
ever actually does that)
> sign/ed25519: Output failed signatures in error message

- src/libostree/ostree-sign-ed25519.c
Small fixes for case if file with public keys doesn't contain correctly formatted keys.
Allow to return the correct error instead of aborting.
> Fix abort on verify

- src/libostree/libostree-devel.sym
This should have been removed when we added symbols to this list.
> libostree-devel.sym: Remove nonexistent stub symbol

- src/libostree/ostree-sysroot.h
This came in with 5af403be0cc64df50ad21cef05f3268ead256d6d but
was never implemented.
I noticed this now because the Rust ostree bindings generate a
wrapper for it which the linker tries to use.
> sysroot: Remove unimplemented ostree_sysroot_lock_with_mount_namespace

- src/libostree/ostree-core.c
Working on some rpm-ostree bits and was going to pass
this to the `chrono` crate and I forgot the format, went
to look at the docs.  Oops.
> core: Add documentation for ostree_commit_get_timestamp()

- tests/kolainst/destructive/staged-delay.sh
- tests/kolainst/destructive/staged-deploy.sh
- tests/kolainst/destructive/var-mount.sh
- tests/kolainst/libinsttest.sh
See https://github.com/coreos/coreos-assembler/pull/1528
I think we can drop the old cosa reboot APIs after this,
though I've already forgotten where else I might have written
tests using it.
> tests: Port to Debian autopkgtest reboot API

- src/libostree/ostree-bootloader-uboot.c
- src/libostree/ostree-sysroot-deploy.c
- tests/test-admin-deploy-uboot.sh
Add support for a devicetree directory at /usr/lib/modules/$kver/dtb/.
In ARM world a general purpose distribution often suppports multiple
boards with a single operating system. However, OSTree currently only
supports a single device tree, which does not allow to use the same
OSTree on different ARM machines. In this scenario typically the boot
loader selects the effective device tree.
This adds device tree directory support for the new boot artefact
location under /usr/lib/modules. If the file `devicetree` does not
exist, then the folder dtb will be checked. All devicetrees are hashed
into the deployment hash. This makes sure that even a single devicetree
change leads to a new deployment and hence can be rolled back.
The loader configuration has a new key "devicetreepath" which contains …
> deploy: support devicetree directory

- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull-verify.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-sign-dummy.c
- src/libostree/ostree-sign-dummy.h
- src/libostree/ostree-sign-ed25519.c
- src/libostree/ostree-sign-ed25519.h
- src/libostree/ostree-sign.c
- src/libostree/ostree-sign.h
- src/ostree/ot-builtin-sign.c
- tests/test-signed-commit.sh
This is the dual of https://github.com/ostreedev/ostree/pull/2129/commits/1f3c8c5b3de978f6e069c24938967f823cce7ee8
where we output more detail when signapi fails to validate.
Extend the API to return a string for success, which we output
to stdout.
This will help the test suite *and* end users validate that the expected
thing is happening.
In order to make this cleaner, split the "verified commit" set
in the pull code into GPG and signapi verified sets, and have
the signapi verified set contain the verification string.
We're not doing anything with the verification string in the
pull code *yet* but I plan to add something like
`ostree pull --verbose` which would finally print this.
> signapi: Change API to also return a success message

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo.c
If `glnx_make_lock_file` falls back to `flock`, on NFS this uses POSIX
locks (`F_SETLK`). As such, we need to be able to handle `EACCES` as
well as `EAGAIN` (see `fnctl(2)`).
I think this is what coreos-ostree-importer has been hitting, which runs
on RHEL7 in the Fedora infra and does locking over an NFS share where
multiple apps could concurrently pull things into the repo.
> lib/repo: Handle EACCES for POSIX locking

- .cci.jenkinsfile
- ci/libbuild.sh
- tests/kolainst/nondestructive/itest-payload-link.sh
- tests/kolainst/nondestructive/itest-pull.sh
The default `_NPROCESSORS_ONLN` heuristic we have isn't cgroups aware.
So it thinks it has e.g. 40 CPUs when running in a k8s pod. This can
then blow through our allocated resource limits.
Declare some modest amount of RAM and CPU resources and override `make`
parallelism.
This matches what rpm-ostree now does in
https://github.com/coreos/rpm-ostree/pull/2155.
> ci: Constrain parallel build jobs

- src/libostree/ostree-repo-pull.c
- tests/pull-test.sh
This is very useful information that we get from the transaction
stats.  Append it to the final display if we're not inheriting
the transaction.
> pull: Also append bytes written

- man/ostree.repo-config.xml
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
- src/ostree/ot-builtin-pull-local.c
- src/ostree/ot-builtin-pull.c
- tests/pull-test.sh
This is the opposite of
https://github.com/ostreedev/ostree/issues/1184
Motivated by OpenShift seeing etcd performance issues during
OS updates: https://github.com/openshift/machine-config-operator/issues/1897
Basically, if we switch to invoking `fsync()` as we go, it makes
ostree performance worse (in my tests, 31s to write 2G versus 7s if we
delay sync) but it avoids *huge* outliers in `fsync()` time for etcd.
> pull: Add --per-object-fsync

- .cci.jenkinsfile
Make sure we don't break the FCOS live image.  PXE is probably sufficient, but also test the ISO image for good measure.
> ci: test FCOS PXE and ISO install

- man/ostree-commit.xml
- man/ostree.xml
This mainly adds a basic glossary to define some literals commonly used. Writing them down helps to understand the man pages better and picking the right term/literal when adding features. There are probably some cases where the "wrong" literal has been used, but once we have a clear definition of the literals, it will become easier to harmonize their usage.
> Improve man pages

- src/ostree/ot-admin-builtin-switch.c
- src/ostree/ot-builtin-admin.c
- src/ostree/ot-builtin-commit.c
- src/ostree/ot-builtin-log.c
- Use `REV` instead of `REF` in places where we meant it.
- Fix `commit --parent` actually taking a commit checksum and not a ref.
- Fix `ostree admin switch` using `REF` instead of `REFSPEC`.
> app: Fix various CLI metavariable names

- .cci.jenkinsfile
Regression from
https://github.com/ostreedev/ostree/pull/2158/commits/5d7f897908dbf7f471ddfdbd6c29a84ac6bc0bda
I'm not sure how (or if) this passed before, the job logs have
been GC'd.
This is a bit confusing but basically right now ostree/rpm-ostree's
CI jobs don't use `/srv/fcos` - it might make sense to port
these to `fcosBuild` but that needs investigation.
> ci: Fix ISO testing

- tests/test-repo-finder-config.c
- tests/test-repo-finder-mount.c
We were committing the whole tempdir, which seems to fail
in Travis because the GPG agent Unix domain socket ends up there too,
and ostree refuses to commit sockets.
> tests/repo-finder: Explicitly commit empty dir

- src/switchroot/ostree-remount.c
Regression from https://github.com/ostreedev/ostree/pull/2113/commits/35642259175973617da937f3cab6ce5f13c95077
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1862568
We still need to remount writable if it's not configured on;
because it may need OS adjustments it needs to be opt-in.
> remount: Still remount /sysroot writable if not configured ro

- src/ostree/ot-dump.c
This is useful for ostree log on client side where often not the
full history of a branch is available. It is also helpful for
ostree show to show if a particular commit has a parent.
> Show commit checksum of parent, if present

- ci/build.sh
Since it's just not a sane thing to do and will cause various
failures in our test suite.
>  ci: Barf on unset umask

- src/libostree/ostree-repo-pull.c
These allow the `summary` and `summary.sig` files to be cached at a
higher layer (for example, flatpak) between related pull operations (for
example, within a single flatpak transaction). This avoids
re-downloading `summary.sig` multiple times throughout a transaction,
which increases the transaction’s latency and introduces the possibility
for inconsistency between parts of the transaction if the server changes
its `summary` file part-way through.
In particular, this should speed up flatpak transactions on machines
with high latency network connections, where network round trips have a
high impact on the latency of an overall operation.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
> pull: Add summary-{,sig-}bytes options to ostree_repo_pull()

- src/boot/dracut/ostree.conf
Without reproducible images, a rebuild of the initrd will create a
different image file (due to things like creation time of the files in
the cpio archive) even if the actual contents in it are exactly the
same, adding an unnecessary download during updates.
Adding 'reproducible=yes' avoids this and creates the same image files
for the same content.
> dracut: Create reproducible images

- src/libostree/ostree-sysroot-cleanup.c
- src/libostree/ostree-sysroot-deploy.c
See individual commit messages.
> Miscellaneous patches split out of #2155

- configure.ac
Mainly to get https://github.com/ostreedev/ostree/pull/2160 out.
> Release 2020.5

- tests/inst/Cargo.toml
Updating our tests to the latest ostree crate is so deliciously
circular.
> tests/inst: Bump to latest ostree and gtk-rs

- src/libostree/ostree-bootloader-syslinux.c
- src/libostree/ostree-bootloader-uboot.c
- src/libostree/ostree-sysroot-deploy.c
- tests/bootloader-entries-crosscheck.py
We use a similar trick to having a `sysroot -> .` symlink on the real root
here to support both /boot on root as well as on a separate filesystem.  No
matter how it's mounted `/boot/xyz` will always refer to the file you'd
expect.
This is nicer than my previous attempts at this because there's no
configuration nor auto-detection required.
Fixes #1452
Replaces #1404, #1914 and #2145
> sysroot: Support /boot on root or as seperate filesystem for syslinux and u-boot

- src/ostree/ot-admin-builtin-pin.c
- tests/test-admin-deploy-2.sh
Validate that we're parsing a number; we want to guard
against typos.
Closes: https://github.com/ostreedev/ostree/issues/2171
> admin/pin: Enforce that index is a number

- configure.ac
We missed this during the post-release version bump.
> configure.ac: Set is_release_build=no

- src/boot/mkinitcpio/ostree
`ostree-prepare-root.service` may race with systemd failing to determine if `/sysroot` is valid because of `/etc/os-release` not being available yet.
Tested this under Arch Linux on multiple systems with different some having SSDs and some having HDDs.
Related: #1759
> Fix mkinitcpio with newer systemd versions

- tests/inst/Cargo.toml
- tests/inst/src/destructive.rs
- tests/inst/src/repobin.rs
- tests/inst/src/sysroot.rs
- tests/inst/src/test.rs
- tests/inst/src/treegen.rs
I cleaned up my fork of commandspec (see git log) and am
planning to publish to crates.  Port to the new API in prep
for that.
> tests/inst: Port to new sh-inline repo

- tests/inst/Cargo.toml
- tests/inst/src/destructive.rs
- tests/inst/src/repobin.rs
- tests/inst/src/test.rs
- tests/inst/src/treegen.rs
And I made a few more API tweaks, such as supporting `Path`
objects directly and also not needing e.g. `commit = commit`, see
- https://github.com/cgwalters/rust-sh-inline/commit/cfa7c71126f23545a7d4782cad650eab60e74204
- https://github.com/cgwalters/rust-sh-inline/commit/679bce4cc7ce65641e0c9bd33654510575583de8
> tests/inst: Update to published sh-inline crate

- .cci.jenkinsfile
- src/switchroot/ostree-prepare-root.c
- src/switchroot/ostree-remount.c
```
commit 1e5d53fcb6826d070798c3b680da1d0a07a0de5d
Date:   Fri Aug 28 12:35:28 2020 -0400
ostree-prepare-root: Fix /etc bind mount
We were bind-mounting the initramfs' `/etc` instead of the target
deployment. Since we're already `chdir`'ed into it, we can just drop the
leading slash.
commit 2a68463bdae0ba688d517b1240330f4a7cc726f6
Date:   Fri Aug 28 12:35:29 2020 -0400
ostree-remount: Remount /etc rw if needed
When we remount `/sysroot` as read-only, we also make `/etc` read-only.
This is usually OK because we then remount `/var` read-write, which also
flips `/etc` back to read-write... unless `/var` is a separate
filesystem and not a bind-mount to the stateroot `/var`.
Fix this by just remounting `/etc` read-write in the read-only sysroot
case.
Eventually, I think we should rework this …
```
> Fix read-only /etc when using sysroot=readonly and a separate /var mount

- .cci.jenkinsfile
Merged in https://github.com/coreos/fedora-coreos-config/pull/586
> ci: Drop var mount test

- src/libostree/ostree-sysroot-deploy.c
Looking at
https://github.com/coreos/coreos-assembler/issues/1703
a user is getting a bare:
`error: fsetxattr: Permission denied`
I don't think it's these code paths since a deploy
isn't happening but on inspection I noticed we didn't
have error prefixing here.
> deploy: Add some error prefixing around xattr setting

- src/libostree/libostree-devel.sym
- src/libostree/libostree-released.sym
- src/libostree/ostree-core.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo-static-delta-core.c
- src/libostree/ostree-repo-static-delta-private.h
- src/libostree/ostree-repo.c
- src/libotutil/ot-checksum-utils.c
- src/libotutil/ot-checksum-utils.h
- src/libotutil/otutil.h
- tests/test-symbols.sh
I'm currently working on scalability issues with the summary files, but the changes there are kinda large. I'd like to land this preparatory work separately so that those become easier to review. If you're interested, that works starts with the #2188, and then continues in https://github.com/alexlarsson/ostree/tree/indexed-summaries.
This PR fixes some bugs:
* Correct the file type check in the static delta listing code
* Fix leak when signing
* Actually mmap the summary files (old fix for this just mmaped the signatures)
And additionally it cleans things up by breaking out things into helper functions and moving things around. Mostly this is because the helper functions will be reused later by my new code, but sometimes it also removes duplication of code in the existing code. I think …
> Preparatory cleanup for summary work

- configure.ac
- src/libostree/ostree-fetcher-curl.c
- src/libostree/ostree-repo-finder-avahi-parser.c
- src/libostree/ostree-repo-finder-mount.c
- src/libostree/ostree-repo-finder-override.c
- src/libostree/ostree-repo-libarchive.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
- src/libostree/ostree-soup-uri.c
- src/libostree/ostree-sysroot-deploy.c
- src/ostree/ot-admin-builtin-set-origin.c
- src/ostree/ot-builtin-checkout.c
- src/ostree/ot-builtin-commit.c
- src/ostree/ot-builtin-config.c
- src/ostree/ot-builtin-gpg-sign.c
- src/ostree/ot-builtin-pull.c
- src/ostree/ot-builtin-sign.c
- src/ostree/ot-remote-builtin-add.c
- tests/repo-finder-mount.c
- tests/test-repo-finder-config.c
- tests/test-repo-finder-mount.c
This should help with code readability.
Fixes https://github.com/ostreedev/ostree/issues/2194
> Avoid shadowing local variables

- src/libostree/ostree-repo-checkout.c
- tests/test-basic-user.sh
The extreme special case of "zero mode" files like `/etc/shadow`
comes up again.  What we want is for "user mode" checkouts to
override it to make the file readable; otherwise when operating
as non-root without `CAP_DAC_OVERRIDE` it becomes very difficult
to work with.
Previously, we were hardlinking these files, but then it intersects
with *another* special case around zero sized files, which is
*also* true for `/etc/shadow`.
Trying to avoid hardlinking there unveiled this bug - when
we go to do a copy checkout, we need to override the mode.
> checkout: Ensure copies of unreadable usermode checkouts are readable

- Makefile-tests.am
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/test-osupdate-dtb.sh
When support for devicetree was added, it created a problem
because old and new ostree versions would compute different
checksums for the "boot data".  The scenario here is:
- Have system with ostree < 2020.4
- Reboot into system with ostree 2020.5
- Try to perform an operation that would retain
that previous booted deployment (common)
Currently ostree iterates over all the deployments
that will be retained and calls `install_deployment_kernel()`,
even for the booted one (which is a bit silly), but
just to verify that all boot data for the targeted
deployments are installed.
This then re-computes the checksum and we'd trip this
assertion.
In practice though, we don't strictly require them to match;
the only thing that will happen if they don't is that we'll
end up with another copy of the …
>  deploy: Remove deployment bootcsum assertion

- Makefile-libostree.am
- src/libostree/libostree-devel.sym
- src/libostree/libostree-released.sym
- src/libostree/ostree-repo-static-delta-core.c
- tests/test-symbols.sh
```
commit 75342035d5902f299be53d7b541724407463d62c
Date:   Fri Sep 25 14:59:45 2020 -0400
Makefile-libostree.am: Uncomment BUILDOPT_IS_DEVEL_BUILD conditional
We shouldn't have to toggle the conditional itself during release
builds. It should only evaluate to true during devel builds.
commit 68489f647832e3ab9f3856513e459a0cc296ef84
Date:   Fri Sep 25 15:01:09 2020 -0400
lib: Minor versioning related fixes
Fix/add the `Since` marker to the new static delta APIs, and update the
symbol versioning templates/comments.
```
> Various minor versioning related tweaks

- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
- src/ostree/ot-dump.c
- tests/test-summary-view.sh
Fixes #2165. See that and the commit messages for details.
This doesn’t need additional changes in flatpak for it to be used there too. It does require repositories to regenerate their `summary` files before the non-fallback code path is taken in clients, though. That’ll happen soon enough naturally.
> Avoid need to download remote config when pulling

- README.md
- docs/CONTRIBUTING.md
- docs/README-historical.md
- docs/_config.yml
- docs/_sass/color_schemes/coreos.scss
- docs/adapting-existing.md
- docs/atomic-upgrades.md
- docs/buildsystem-and-repos.md
- docs/contributing-tutorial.md
- docs/deployment.md
- docs/formats.md
- docs/index.md
- docs/introduction.md
- docs/related-projects.md
- docs/repo.md
- docs/repository-management.md
The goal here is to replace the manually updated readthedocs documentation website by an automatically updated website using GitHub Pages.
Preview: https://travier.github.io/ostree/
Fixes: https://github.com/ostreedev/ostree/issues/2206
> docs: Add GitHub Pages support

- man/ostree-checkout.xml
- src/libostree/ostree-repo-checkout.c
- src/ostree/ot-builtin-checkout.c
- tests/basic-test.sh
- tests/test-libarchive.sh
Alternative to https://github.com/ostreedev/ostree/pull/2197
Python's (usually) zero-sized `__init__.py` files can provoke
us hitting the hardlink limits on some filesystems (`EMLINK`).
At least one Fedora rpm-ostree user hit this.
The benefits of hardlinking here are quite marginal; lots
of hardlinks can behave suboptimally in particular filesystems
like BTRFS too.
This builds on prior code which made this an option, introduced
in https://github.com/ostreedev/ostree/commit/673cacd633f9d6b653cdea530657d3e780a41bbd
Now we just do it uncondtionally.
Also this provoked a different bug in a very obscure user mode checkout
case; when the "real" permissions were different from the "physical"
permissions, we would still hardlink.  Fix the test case for this.
> checkout: Don't hardlink zero sized files

- .packit.yaml
This is a basic `.packit.yaml` integration file which will allow us have
continuous builds of OSTree in cosa and upstream CI. If things go well,
we'll likely deploy this in other build tools like rpm-ostree.
Prompted by wanting to get #2155 out to unblock
https://github.com/coreos/rpm-ostree/pull/2170.
> Add Packit integration

- src/libostree/ostree-sysroot-deploy.c
Likely the root of https://bugzilla.redhat.com/show_bug.cgi?id=1886149.
> lib/deploy: Don't leak fd when checksumming dtbs

- .packit.yaml
We don't really carry "Fedora-only" patches in dist-git. So we want to
nuke all the patches which exist there.
Follow-up to #2210.
> ci: Make Packit ignore downstream patches

- src/libostree/ostree-sysroot-deploy.c
GI complains.  And in general one needs to assume that file
descriptors aren't stolen.
> deploy: Remove (transfer none) from fd arg

- src/switchroot/ostree-prepare-root.c
This matches what systemd does and should work fine on all platforms.
Possibly resolves: bugzilla.redhat.com/show_bug.cgi?id=1888436
> ostree-prepare-root: print st_dev and st_ino as 64-bit ints

- src/libostree/ostree-fetcher-curl.c
The timeout timer should always be one-shot, so let's just always
destroy it in the callback. The main context has its own ref on it, so
it won't be freed behind its back.
This *should* fix a leak that was brought up in
https://bugzilla.redhat.com/show_bug.cgi?id=1891761.
Reported-by: Milan Crha <mcrha@redhat.com>
> lib/fetch-curl: Unref timeout source

- man/ostree.repo-config.xml
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot.c
- tests/bootloader-entries-crosscheck.py
These are some refactorings I made a little while ago in preparation for adding a new bootloader class, but the new bootloader wasn't necessary after all.  I think the refactorings still have value though.
I'm raising this now so it can be used in the `OstreeBootloaderRpi` implementation.  See discussion on #2223.
> Bootloader probing and construction refactoring

- src/libostree/ostree-repo.c
I got:
src/libostree/ostree-repo.c:5232: Warning: OSTree: ostree_repo_gpg_sign_data: unknown parameter 'out_signature' in documentation comment, should be 'out_signatures'
> ostree_repo_gpg_sign_data: Fix API doc argument name

- src/libostree/ostree-repo-static-delta-compilation.c
Without this you can't create a scratch delta from GI. While here,
switch the deprecated allow-none annotations to nullable.
> lib/deltas: Annotate from checksum as nullable

- src/libostree/ostree-repo-pull.c
The cache shouldn't be affected by the user passing in some other
summary as it may not be the "official one".
I ran into this in flatpak where the passed summary was correct, but
the re-saving of the cache updated the mtime of the cached file which
led to later http If-Modified-Since calls failing to update.
> pull: Don't save into cache passed in GByte summaries

- src/libostree/ostree-diff.h
- src/libostree/ostree-enumtypes.c.template
- src/libostree/ostree-fetcher-soup.c
- src/libostree/ostree-remote-private.h
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-sysroot-upgrader.c
As detailed in
https://gitlab.gnome.org/GNOME/glib/-/issues/600#note_877282, volatile
isn't actually needed in these contexts because the atomic operations
already give us strong enough guarantees. In GCC 11, this triggers a
diagnostic due to the volatile qualifier getting dropped anyway.
There is a WIP to do the same in glib:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1719
This obsoletes this downstream patch:
https://src.fedoraproject.org/rpms/ostree/c/b8c5a6fb
> Drop use of `volatile`

- src/libostree/ostree-sysroot.c
Hit `ostree_sysroot_repo()` shouldn't be nullable while using
the ostree Rust bindings.
> sysroot: Fix up some GI nullable annotations

- .travis.yml
This removes the old pinned distro (Ubuntu Trusty 14.04) from Travis,
moving to the newer default distro (Ubuntu Xenial 16.04).
> ci/travis: move to newer base distro

- src/libostree/ostree-sysroot.c
Since that's a common case; hit this while working on rpm-ostree
code using the ostree-rs bindings.
> deployment: Ensure query_deployments_for returns nullable values

- src/libostree/ostree-deployment.c
We were missing docs for these, also add some nullability annotations.
Motivated by using these from the Rust bindings.
> deployment: Add a bunch of docs and fix annotations

- .github/workflows/release.yml
- ci/ci-release-build.sh
This adds a GitHub action in order to run ci-release-build.sh on
release PRs (detected via the `kind/release` label).
> ci: run ci-release-build.sh on GitHub

- .github/workflows/release.yml
This adds an additional condition in order to sanity check all
PRs starting with `Release` (case-insensitive).
Ref: https://github.com/ostreedev/ostree/pull/2239#discussion_r524422740
/cc @jlebon
> workflows/release: pattern-match on PR title

- Makefile-libostree.am
- configure.ac
- src/libostree/libostree-devel.sym
- src/libostree/libostree-released.sym
- tests/test-symbols.sh
This release mostly contains scalability improvements and bugfixes.
Caching-related HTTP headers are now supported on summaries and signatures, so that they do not have to be re-downloaded if not changed in the meanwhile.
Summaries and delta have been reworked to allow more fine-grained fetching.
It is now possible to store deltas in detached metadata outside of summary files, so that only relevant ones can be pulled when downloading a particular commit.
In particular, deltas can now be stored in a separate directory indexed by target commit, thus grouping the subset of deltas affecting it. These indexes are updated when the summary is updated and the in-summary delta index would normally be updated.
Related to the above, a new core option has been added to drop the deltas from the …
> Release 2020.8

- .github/workflows/release.yml
This tweaks the release GH workflow further so that it only triggers
when the `configure.ac` file (which owns the version) changes.
Plus it properly checkouts the PR branch to avoid wrongly looking
at a synthetic merge commit.
Ref: https://github.com/ostreedev/ostree/pull/2241#issuecomment-728989765
/cc @jlebon
> workflow/release: further refinements

- .github/ISSUE_TEMPLATE/release-checklist.md
- cfg.mk
- configure.ac
- docs/CONTRIBUTING.md
This collects all release steps in a release-checklist template.
Ref: https://github.com/ostreedev/ostree/pull/2239#discussion_r524428941
> templates: add release-checklist

- tests/test-pull-summary-sigs.sh
If this is not done, the test can fail when the temporary directory is
a tmpfs: for example this happens during build-time testing with /var/tmp
on tmpfs or TEST_TMPDIR pointing to a tmpfs, or installed-tests with
gnome-desktop-testing-runner allocating the test directory on a tmpfs.
In particular, many of Debian's official autobuilders now do the entire
build and test procedure in a chroot hosted on a tmpfs, to improve build
performance and prevent fsync overhead.
In this situation, it appears that overwriting summary.sig with a copy
of summary.sig.2 is not sufficient for the web server to tell the
libostree client that it needs to be re-downloaded. I'm not completely
sure why, because tmpfs does appear to have sub-second-resolution
timestamps, but forcing a distinct mtime is certainly …
> test-pull-summary-sigs: Set timestamps to serve expected files

- bash/ostree
- man/ostree-pull-local.xml
- man/ostree-pull.xml
- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull.c
- src/ostree/ot-builtin-pull-local.c
- src/ostree/ot-builtin-pull.c
- tests/test-pull-collections.sh
In some cases such as backups or mirroring you may want to pull commits
from one repo to another even if there commits that have incorrect
bindings. Fixing the commits in the source repository to have correct
bindings may not be feasible, so provide a pull option to disable
verification.
For Endless we have several repositories that predate collection IDs and
ref bindings. Later these repositories gained collection IDs to support
the features they provide and ref bindings as the ostree tooling was
upgraded. These repositories contain released commits that were valid to
the clients they were targeting at the time. Correcting the bindings is
not really an option as it would mean invalidating the repository
history.
> pull: Allow disabling commit binding verification

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- src/libotutil/otutil.h
- src/ostree/ot-main.c
The recent change in https://github.com/coreos/fedora-coreos-config/pull/659
broke some of our tests that do `mount -o remount,rw /sysroot` but
leave `/boot` read-only.
We had code for having `/boot` read-only before `/sysroot` but
in practice we had a file descriptor for `/sysroot` that we opened
before the remount that would happen later on.
Clean things up here so that in the library, we also remount
`/boot` at the same time we remount `/sysroot` if either are readonly.
Second, adapt the client side code to check for either being
readonly to enable the mount namespace.  Now honestly we could
almost certainly just set this unconditionally - the original
client code here is just being excessively conservative.  But
I'd like to make that cleanup independently of this fix.
> sysroot: Handle ro /boot but rw /sysroot

- src/libostree/ostree-repo.c
Hit this when trying to use the Rust bindings.
> repo: Make ostree_repo_create_at take nullable options

- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull.c
- tests/test-local-pull-depth.sh
- tests/test-pull-depth.sh
Here are a couple fixes I found when trying to do a `pull-local --depth=-1`. My use case is that I'm trying to merge 2 repos together locally but the repos have truncated histories due to pruning.
> Pull depth fixes

- tests/inst/src/destructive.rs
- tests/inst/src/rpmostree.rs
This enhances external-tests logic, ensuring that destructive tests
have some retries and context to pinpoint failures, and that failed-state services
are reset between iterations.
> tests/ext/destructive: enhance test logic

- ci/build-check-sanitized.sh
- configure.ac
- tests/libtest.sh
It's cleaner if this is an build option rather than being
kludged into the CI layer.
Notably we can't use `LD_PRELOAD` anymore with ASAN, so update
our tests to check for `ASAN_OPTIONS`.
> Add --enable-sanitizers, fix `make check` with it

- docs/repository-management.md
Came up with a user hitting ratelimiting from S3.
> docs: Describe using scratch/empty deltas for initial fetches

- src/libostree/ostree-repo-refs.c
We have an `allow_noent` boolean that controls this, but
were missing the `(nullable)` annotation, so the Rust bindings
panic when the ref doesn't exist instead of being `Option<GString>`.
> refs: Make ostree_repo_resolve_rev{,_ext}() use (nullable)

- src/libostree/ostree-sysroot-deploy.c
- tests/kolainst/destructive/staged-deploy.sh
To help debug an issue we've seen where `/boot` isn't
in sync with the `/ostree/boot` dir, let's log to the journal
what we're doing.
> deploy: Add subbootversion to journal

- src/libostree/ostree-sysroot.c
Was looking at this code more closely today to investigate issues
related to bootlink mismatches (#2283).
> lib/sysroot: Add comments and debug statements around sysroot parsing

- docs/index.md
- docs/related-projects.md
The Torizon platform, includin the TorizonCore OS, the TorizonCore
Builder Tool and the Torizon OTA, use OSTree as a base for update the
host OS, while the user focus on application development using Docker.
Add TorizonCore to the list of Operating systems and distributions using
OSTree.
Add Torizon and its components to the list of related projects.
> docs: Add Torizon to related projects and OS

- src/libostree/ostree-repo-pull.c
Currently if a file path contains a special character such as '\', and
that character is encoded into a file:// URI that is passed to
ostree_repo_pull_with_options(), the percent encoding will remain in the
path passed to g_file_new() (in the case of backslash %5C) and the pull
will then fail with a file not found error. This is an important edge
case to handle because by default on many Linux distributions a
filesystem with no label is mounted at a path based on its UUID, and
this is then passed to systemd-escape by Flatpak (when
--enable-auto-sideloading was used at compile time) to create a symbolic
link such as this which contains backslashes:
$ ls -l /run/flatpak/sideload-repos/
total 0
lrwxrwxrwx 1 mwleeds mwleeds 55 Mar  9 14:21 …
> Fix translation of file:// URIs into paths

- configure.ac
- src/libostree/ostree-bootloader-grub2.c
GRUB starting with version 2.02 permits the use of the standard `linux` and `initrd` commands for both EFI boot in *-efi installations, as well as 32-bit BIOS boot in i386-pc installations.
This makes the use of the -16 and -efi suffixes for BIOS and EFI boot obsolete in modern distros (The efi suffix is a RHEL/Fedora-ism anyway that doesn't apply to distros not based on these).
Additionally, booting the kernel in real-mode on x86 BIOS systems with the linux16/initrd16 commands should be an exception and not the default.
All modern distros, including RHEL and Fedora versions starting with RHEL 8 and Fedora 28, include or are based on a grub >2.02 release, so I think moving forward ostree should drop these suffixes for generated grub configurations.
Closes: #1009
> Add configure option for unsuffixed GRUB2 commands linux/initrd

- src/libostree/ostree-repo-pull.c
I think these are the paths involved in the error message at
https://github.com/coreos/rpm-ostree/issues/2250.
> lib/pull: Add some error-prefixing in dirtree scanning

- Makefile-boot.am
It's still so tempting to switch to `git archive` to ship sources.
Closes: https://github.com/ostreedev/ostree/issues/2312
> build-sys: Include all mkinitcpio bits

- manual-tests/upgrade-loop.js
- src/libostree/ostree-core.c
manual-tests: Fix unused variables
lgtm.com harshly makes our JS grade "D" due to these unused
variables.
---
repo: Refactor ostree_repo_remote_list() to decl-and-init style
Mostly doing this to tickle lgtm.com's detection of C/C++ changes.
---
> Two lgtm.com analysis test commits

- .cci.jenkinsfile
- Makefile-libostree.am
- Makefile-ostree.am
- Makefile-tests.am
- apidoc/Makefile.am
- apidoc/ostree-sections.txt
- configure.ac
- tests/libtest.sh
- tests/test-symbols.sh
It was added for the collections bits, but we made that stable.
It's now just cruft and we're very unlikely to reuse the infrastructure
again.
Motivated by a unit test failure when running from a tarball:
https://github.com/ostreedev/ostree/issues/2313
> build-sys: Remove --enable-experimental-api

- tests/inst/Cargo.toml
- tests/inst/src/destructive.rs
- tests/inst/src/test.rs
tests: Drop openat override
No longer needed.
---
tests/inst: Update ostree crate
---
tests/inst: Update rpm-ostree client
---
tests/inst: Update tokio, hyper and nix
---
> Various patches for tests/inst

- tests/test-libarchive-import.c
We can't mix `goto` and `__attribute__((cleanup))`.
> tests: Silence a gcc warning

- .travis.yml
- ci/travis-install.sh
Currently the Ubuntu builds are stuck waiting for an answer on what
timezone to use. That could be fixed, but generally the way to do these
types of installs is to set the DEBIAN_FRONTEND environment variable to
`noninteractive` so that debconf just chooses a default. This is what
debootstrap does, for instance. I tested installing tzdata on a local
focal container this way and it just chooses `Etc/UTC` as the timezone.
> travis: Don't ask any debconf questions when installing packages

- Makefile-libostree.am
- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
- src/libostree/ostree-content-writer.c
- src/libostree/ostree-content-writer.h
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.h
- tests/test-core.js
- tests/test-repo.c
This API is push rather than pull, which makes it much more
suitable to use cases like parsing a tar file from external
code.
Now, we have a large mess in this area internally because
the original file writing code was pull based, but static
deltas hit the same problem of wanting a push API, so I added
this special `OstreeRepoBareContent` just for writing regular
files from a push API.
Eventually...I'd like to deprecate the pull based API,
and rework things so that for regular files the push API
is the default, and then `write_content_object()` would
be split up into archive/bare cases.
In this world the `ostree_repo_write_content()` API would
then need to hackily bridge pull to push and it'd be
less efficient.
Anyways for now due to this bifurcation, this API only
works on non-archive …
> repo: Add ostree_repo_write_regfile

- tests/libtest.sh
If we fail as a result of `set -x`, It's often not completely obvious
which command failed or how. Use a trap on ERR to show the command that
failed, and its exit status.
> libtest: On failure, make it clearer what has happened

- src/libostree/ostree-repo.c
- tests/libtest.sh
- tests/test-pull-summary-caching.sh
- tests/test-pull-summary-sigs.sh
- tests/test-signed-pull-summary.sh
Several tests generate summaries and then expect to use the generated
summary immediately. However, this can cause intermittent test failures
when they inadvertantly get a cached summary file. This typically
happens when the test is run on a filesystem that doesn't support user
extended attributes. In that case, the caching code can only use the
last modified time, which only has 1 second granularity. If tests don't
carefully manage the summary modification times or the repo cache then
they are likely subject to races in some test environments.
This introduces an environment variable `OSTREE_SKIP_CACHE` that
prevents the repo from using a cache directory. This is enabled by
default in tests and disabled for tests that are a explicitly trying to
test the caching behavior.
Fixes: #2313 …
> tests: Test without a cache directory by default

- src/libostree/ostree-fetcher-uri.c
- src/libostree/ostree-fetcher.h
- src/libostree/ostree-repo-pull.c
- tests/pull-test.sh
Previous to this we'd trip an assertion `abort()` deep in the curl code if e.g.
a user did `ostree remote add foo htttp://...` etc.
Motivated by considering supporting "external remotes" where code outside
ostree does a pull, but we want to reuse the signing verification infrastructure.
> pull: Cleanly error out on unknown schemes

- .github/workflows/tests.yml
Since we now have a toplevel workspace, just use that.
> ci: Fix GH action for rustfmt

- .github/workflows/docs.yml
- Makefile.am
- docs/Gemfile
- docs/README.md
- docs/_config.yml
- docs/index.md
- docs/prep-docs.sh
This adds a GitHub workflow to build the Jekyll docs with Jekyll Actions and push it to the `gh-pages` rather than use GitHub's fully automated flow. The reason to do this is to build the gtk-doc API docs and then include them into the Jekyll static site.
I'm no jekyll or github pages expert, but it seems to work correctly as you can see it at the following pages:
https://dbnicholson.github.io/ostree/
https://dbnicholson.github.io/ostree/#api-reference
https://dbnicholson.github.io/ostree/reference/
In order to put this in place the ostree repo Pages settings would need to be changed to use `gh-pages` as the branch with the root directory.
Fixes: #2362
> Publish libostree API docs

- .github/workflows/docs.yml
The ostree repo has read permissions set for workflows, which prevents
the documentation job from pushing the built docs to the gh-pages
branch. Raise the job's permissions to write for repo contents to allow
that.
> workflow/docs: Give token write permission to push gh-pages

- tests/kolainst/destructive/staged-delay.sh
Yeah, we should stop parsing the text; I need to dig at that
at some point.
> ci: Fix staged-delay to work with newer systemd

- tests/test-gpg-signed-commit.sh
In gnupg 2.3.0[1], if a primary key is expired and a subkey does not
have an expiration or its expiration is older than the primary key, the
subkey's expiration will be reported as the primary's. Previously a
subkey without an expiration would not report one that regardless of the
primary key's expiration.
This caused a regression in a test setting an expiration on a primary
key. The test was checking that the subkey was not expired by asserting
that there was no `Key expired` line in the signature verification
output. With gnupg 2.3.0+, it will show as expired, causing the test to
fail.
Remove the assertion since it's not consistent across gnupg versions. In
practice we don't care whether the subkey is considered expired or not
as long as the signature verification fails when the primary …
> tests/gpg: Don't assert subkey expiration when only primary expired

- src/libostree/ostree-repo.c
GSlice is effectively deprecated and has little to no advantage over
using the system allocator on Linux.
This was discussed in https://github.com/ostreedev/ostree/pull/2348#discussion_r645864806. I started swapping out all the GSlice usage tree-wide, but I wasn't totally sure if that was wanted. If you prefer, I can finish that off.
> repo: Use g_new for OstreeRepoAutoLock

- src/libostree/ostree-sysroot-deploy.c
- tests/kolainst/destructive/deployment-lint
This will be ignored, so let's make it very clear
people are doing something wrong.  Motivated by a bug
in a build pipeline that injected `/var/lib/rpm` into an ostree
commit which ended up crashing rpm-ostree because it was an empty db
which it wasn't expecting.
It *also* turns out rpm-ostree is incorrectly dumping content in the
deployment `/var` today, which is another bug.
> deploy: Warn if we find content in the deployment's /var

- src/libostree/ostree-sysroot.c
Stumbled upon it while reading about deployments.
> Fix small typo in ostree-sysroot.c

- configure.ac
- src/libostree/ostree-impl-system-generator.c
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/kolainst/destructive/staged-deploy.sh
We struggled for a long time with enablement of our "internal units",
trying to follow the philosophy that units should only be enabled
by explicit preset.
See https://bugzilla.redhat.com/show_bug.cgi?id=1451458
and https://github.com/coreos/rpm-ostree/pull/1482
etc.
And I just saw chat (RH internal on a proprietary system sadly) where
someone hit `ostree-remount.service` not being enabled in CentOS8.
Thinking about this more, I realized we've shipped a systemd generator
for a long time and while its only role until now was to generate `var.mount`,
but by using it to force on our internal units, we don't require
people to deal with presets anymore.
Basically we're inverting things so that "if ostree= is on the kernel
cmdline, then enable our units" and not "enable our units, but have
them …
> Use generator to enable ostree-remount.service and ostree-finalize-staged.path

- README.md
Freenode appears to be imploding.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
> docs: Change IRC channel to libera.chat from freenode

- src/libostree/ostree-impl-system-generator.c
In configure the systemd unit path is optional, but in the code it's
assumed to be defined. Add an `#ifdef` that throws an error when it's
not defined like the handling of `HAVE_LIBMOUNT` below it.
> Don't fail build when systemd unit path not defined

- tests/kolainst/libtest-core.sh
If this PR and containers/bubblewrap#433 are both accepted, then `libtest-core.sh` will be identical in both projects. Maintainers of both projects, like @cgwalters, are probably in the best position to make this happen.
* libtest-core: Add assert_files_equal
From: @alexlarsson 
[Originally from bubblewrap commits c5c999a7 "tests: test --userns"
and 3e5fe1bf "tests: Better error message if assert_files_equal fails";
separated into this commit by Simon McVittie.]
* libtest-core: On failure, make it clearer what has happened
If we fail as a result of `set -x`, It's often not completely obvious
which command failed or how. Use a trap on ERR to show the command that
failed, and its exit status.
* libtest-core: Update URL of rpm-ostree
* libtest-core: Mention bubblewrap as a user of this file
> libtest-core: Add some improvements from bubblewrap

- tests/libtest.sh
Since #2377 was merged, this is in libtest-core.sh, which is sourced by
libtest.sh.
> libtest.sh: Remove duplicate ERR trap and report_err()

- Makefile-tests.am
- src/libostree/ostree-repo-commit.c
- tests/test-commit-timestamp.sh
This tweaks `ostree_repo_write_commit` so that it checks for the
envinroment variable `SOURCE_DATE_EPOCH` as a way to override
the current time, which is used as the commit timestamp.
Ref: https://reproducible-builds.org/docs/source-date-epoch/
Ref: https://reproducible-builds.org/specs/source-date-epoch/
Closes: https://github.com/ostreedev/ostree/issues/2385
> lib/commit: respect SOURCE_DATE_EPOCH for commit timestamp

- .github/workflows/tests.yml
- ci/gh-build.sh
- ci/gh-install.sh
This changes the existing Debian and Ubuntu configurations to use the release stage tags instead of the codename tags. A Debian testing build is added while the Ubuntu groovy build is changed from groovy to hirsute via the `rolling` tag. An Alpine Linux build is added, too.
CC @smcv
> Update GitHub Tests workflow configurations

- src/boot/ostree-remount.service
The `systemd-rfkill.*` service falls in the category of early things
that need write access to `/var`, so we need to make sure we run before
or it might hit the read-only sysroot.
The long-term fix for this is
https://github.com/ostreedev/ostree/issues/2115.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/746
> ostree-remount: Order before systemd-rfkill.*

- Makefile-libostree.am
- configure.ac
- src/libostree/libostree-devel.sym
- src/libostree/libostree-released.sym
- tests/test-symbols.sh
This release adds new repository-locking methods to the API, in order to make lock handling more granular and better suited for multi-threaded consumers of the library.
Several bugs have been fixed related to service unit ordering and enablement. Pulling from remotes with unknown schemes now produces more friendly error messages.
API documentation is now automatically published to <https://ostreedev.github.io/ostree/reference/>.
By default, commit timestamps now respect the 'SOURCE_DATE_EPOCH' environment flag, improving support for reproducible outputs.
On the community side, the default git development branch has been renamed to 'main' and the IRC channel moved to the libera.chat network.
---
```
Alexander Larsson (1):
libtest-core: Add assert_files_equal
Benjamin Gilbert (1):
OWNERS: …
```
> Release 2021.3

- man/ostree-commit.xml
A statoverride file written in the obvious way will produce incorrect results for two independent reasons.  Document them.
> man: improve statoverride description

- ci/gh-build.sh
- tests/libtest.sh
Some distributions set this during build in order to have reproducible
builds from the same source code: for example, Debian uses the date
from debian/changelog.
However, some of our tests assume that `ostree commit` will result in
a commit with the current date/time, and SOURCE_DATE_EPOCH breaks that
assumption. Unset it for our build-time tests.
Resolves: https://github.com/ostreedev/ostree/issues/2405
> tests: Unset SOURCE_DATE_EPOCH

- src/ostree/ot-main.c
Pointer command is dangerous if there is no assignment
Log: Avoid wild pointers
> fix: Avoid wild pointers

- src/ostree/ot-builtin-commit.c
- tests/basic-test.sh
This explicitly checks for commit command options asking for both
non-zero UID/GID and canonical permissions at the same time,
which are incompatible.
> builtins/commit: check for conflicting permissions options

- src/ostree/ot-builtin-commit.c
This reduces the usage of goto cleanup logic by porting the commit
modifier pointer to autoptr.
> builtins/commit: move commit modifier to auto-cleanup

- src/libostree/ostree-core.c
- src/libostree/ostree-core.h
- src/libostree/ostree-repo-checkout.c
- tests/basic-test.sh
- tests/test-basic-user-only.sh
This adds a new `OSTREE_CHECKSUM_FLAGS_CANONICAL_PERMISSIONS`
checksumming flag, which is needed in bare-user-only mode
to ignore local IDs.
It also automatically enables canonical permissions for checkouts in
bare-user-only mode.
> lib/checkout: use canonical permissions in bare-user-only mode

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo.h
- tests/basic-test.sh
- tests/test-basic-user-only.sh
This tweaks commit logic to detect bare-user-only repositories and
canonicalize permissions automatically.
> lib/commit: autofix permissions for bare-user-only

- src/libostree/ostree-diff.c
This fixes the logic to detect whether xattrs should be automatically
ignored when diffing.
---
Context: I was skimming through this code; unless I misread something, the comment and the current code do not agree.
This should fix the code to match the logic described in the comment.
> lib/diff: ignore xattrs if disabled on either repos

- src/libostree/ostree-diff.c
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo.h
- src/ostree/ot-builtin-commit.c
- tests/basic-test.sh
- tests/test-basic-user-only.sh
This is the second half of https://github.com/ostreedev/ostree/pull/2412.
It detects `bare-user-only` mode and automatically skip xattrs for commit and diff.
Closes: https://github.com/ostreedev/ostree/issues/2410
> commit: automatically skip xattrs in bare-user-only mode

- tests/basic-test.sh
- tests/libtest.sh
This tweaks the testsuite in order to fix unprivileged `make check`,
specifically around bare mode.
There is one case of a broken `ostree fsck` which I previously introduced
in a testcase without realizing it wasn't actually passing; I've left it commented
as a FIXME for now as I didn't get to the bottom of the issue.
After this, unprivileged `make check` should be green again.
Closes: https://github.com/ostreedev/ostree/pull/2423
> tests: fix bare mode unprivileged 'make check'

- man/ostree-admin-upgrade.xml
- src/libostree/ostree-sysroot-upgrader.c
- src/libostree/ostree-sysroot-upgrader.h
- src/ostree/ot-admin-builtin-upgrade.c
- tests/kolainst/destructive/staged-deploy.sh
We're waaay overdue for this, it's been the default
in rpm-ostree for years, and solves several important bugs
around not capturing `/etc` while things are running.
Also, `ostree admin upgrade --stage` (should) become idempotent.
Closes: https://github.com/ostreedev/ostree/issues/2389
> upgrade: Stabilize deployment staging

- src/libostree/ostree-repo-pull.c
Hello ostreedev maintainers
When trying to do a pull form a remote with the --require-static-delta flag set after a previous attempt was aborted it would always indicate that everything was already pulled. But doing an deploy of the commit afterwards would throw an error that files are missing.
Investigating the problem i found out that the legacy_transaction_resuming flag was not considered in the delta-path, so it would always mark an legacy_transaction as done/not partial, even if files were missing. Using the commitstate_is_partial function will correctly assess which deltaparts are missing and redownload the missing parts.
With regards
RBuddel
> repo-pull: legacy_transaction_resuming flag ignored

- man/ostree.repo-config.xml
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
- src/ostree/ot-remote-builtin-add.c
- tests/pull-test.sh
This will be helpful for the "ostree native container" work in
https://github.com/ostreedev/ostree-rs-ext/
Basically in order to reuse GPG/signapi verification, we need
to support adding a remote, even though it can't be used via
`ostree pull`.  (At least, not until we merge ostree-rs-ext into ostree, but
even then I think the principle stands)
> Add support for "custom remotes"

- tests/kolainst/libtest-core.sh
- tests/pull-test.sh
- tests/test-admin-deploy-etcmerge-cornercases.sh
tests/pull-test: Avoid duplicating test numbers
We do this in other places; avoids touching two numbers when
adding tests.  Let computers do the addition.
---
tests: Add new TAP APIs
Having to touch a global test counter when adding tests is
a recipe for conflicts between PRs.
The TAP protocol allows *ending* with the expected number of
tests, so the best way to do this is to have an explicit
API like our `tap_ok` which bumps a counter, then end with `tap_end`.
I ported one test as a demo.
---
> two small unit test patches

- src/ostree/ot-builtin-commit.c
- tests/kolainst/destructive/itest-label-selinux.sh
The logic for `--selinux-policy` ended up in the `--tree=dir`
path, but there's no reason for that.  Fix the imported
labeling with `--tree=tar`.  Prep for use with containers.
> bin/commit: Fix --tree=tar with --selinux-policy

- tests/inst/Cargo.toml
- tests/inst/src/destructive.rs
- tests/inst/src/sysroot.rs
This updates to the modern glib 0.14 and paves the way for
some reverse dependency testing by using ostree-ext's code.
> tests: Use ostree-ext 0.3.0

- src/ostree/ot-builtin-fsck.c
There's a general Unix philosophy that "silence is golden".
However, when one is explicitly invoking an error check it's nice
to see explicit success.
We already print various statistics, so ending with a happy
note has no extra cost.
> fsck: Print a success message

- Makefile-libostree.am
- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-sepolicy.c
- src/libostree/ostree-sepolicy.h
This is part of `OstreeCommitModifier`, but I'm not using
that in some of the ostree-ext Rust code.
It just makes more sense as a direct policy API, where it should
have been in the first place.  There's already support for
setting a policy object on a commit modifier, so that's all the
old API needs to do now.
> repo: Add an API to init `OstreeSePolicy` from commit directly

- src/libostree/ostree-sysroot-deploy.c
- tests/kolainst/destructive/staged-deploy.sh
- tests/test-admin-deploy-etcmerge-cornercases.sh
https://bugzilla.redhat.com/show_bug.cgi?id=1945274 is an issue where a privileged
kubernetes daemonset is writing a socket into `/etc`.  This makes ostree upgrades barf.
Now, they should clearly move it to `/run`.  However, one option is for us to
just ignore it instead of erroring out.  Some brief investigation shows that
e.g. `git add somesocket` is a silent no-op, which is an argument in favor of ignoring it.
Closes: https://github.com/ostreedev/ostree/issues/2446
> deploy: Ignore sockets, fifos in /etc during merge

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot-cleanup.c
This enhances the auto-transaction logic, augmenting the scope of a
transaction guard.
It allows committing or aborting a transaction through its guard.
It also supports tracking the completion status of a transaction
guard, avoiding double commits/aborts, while retaining the auto-cleanup
logic.
Ref: https://github.com/ostreedev/ostree/issues/2413#issuecomment-930327836
> repo/private: allow committing/aborting through a transaction guard

- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
- src/libostree/ostree-mutable-tree.c
- src/libostree/ostree-mutable-tree.h
- src/ostree/ot-builtin-commit.c
lib: Add an API to construct a `MutableTree` from a commit
This is nicer than having the caller parse the commit
object, or indirect via the `OstreeRepoFile*` object of the root.
Will be used in ostree-rs-ext around tar parsing.
---
> lib: Add an API to construct a MutableTree from a commit

- tests/test-commit-sign.sh
`test-commit-sign-sh-ext` isn't installed, so it can't be run as an installed-test.
(Or it could be installed and run from `${test_builddir}`, if you'd prefer.)
> test-commit-sign.sh: Skip a unit test when running as an installed-test

- src/switchroot/ostree-prepare-root.c
This moves read-only sysroot checks upfront, so that they are not
intermixed with mount operations.
It has no immediate side-effects, but allow these check to be
independent from the rest of the mounting logic (and future changes
to it).
> prepare-root: check for read-only sysroot status early on

- src/switchroot/ostree-prepare-root.c
Let's ensure things are right from the start in the initramfs;
this closes off various race conditions.  Followup to
https://github.com/ostreedev/ostree/pull/2113/commits/35642259175973617da937f3cab6ce5f13c95077
Closes: https://github.com/ostreedev/ostree/issues/2115
> prepare-root: Set up sysroot readonly in initramfs

- src/libostree/ostree-repo-checkout.c
In Glib, since commit 3a6e8bc8876e149c36b6b14c6a25a718edb581ed,
`g_file_get_child` does not accept absolute path as paramater anymore.
The broken assertion was encountered during `ostree admin deploy`
command for the checkout of subpath `etc`.
Example of error log:
```
(ostree admin deploy:1640): GLib-GIO-CRITICAL **: 03:42:00.570: g_file_get_child: assertion '!g_path_is_absolute (name)' failed
(ostree admin deploy:1640): GLib-GIO-CRITICAL **: 03:42:00.570: g_file_query_info: assertion 'G_IS_FILE (file)' failed
**
OSTree:ERROR:src/ostree/ot-main.c:232:ostree_run: assertion failed: (success || error)
Bail out! OSTree:ERROR:src/ostree/ot-main.c:232:ostree_run: assertion failed: (success || error)
```
> lib: Fix a bad call to g_file_get_child

- ci/gh-install.sh
This was previously pulled in indirectly, but it looks like we need
to require it explicitly in newer Ubuntu.
> ci: Require `libcap2-bin` for `capsh`

- src/libostree/ostree-repo-static-delta-core.c
- src/libostree/ostree-sign-ed25519.c
Otherwise, this will segfault when callers don't need any exact errors.
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
> lib: Avoid dereferencing NULL error values

- src/libostree/ostree-repo-prune.c
`repo_prune_internal` was deserializing each object and passing the
components to `maybe_prune_loose_object`, which promptly reserialized
it.
I noticed this while thinking about prune memory usage in #2483.
> lib/prune: Avoid unnecessary object serialization

- src/ostree/ot-main.c
We should only try to remount `/sysroot` if we're actually handling the
sysroot repo and the repo isn't writable. We already have public APIs to
check each of those, so let's use them.
Closes: #2485
> app: Only remount /sysroot if needed

- configure.ac
This is a bugfix release.
Most of the fixes are related to warnings highlighted by `gcc -fanalyzer` static source analysis.
Performance of pruning logic has been improved, avoiding unnecessary trips through redundant serialization (#2484).
A regression has been fixed so that `ostree` is properly behaving again when used from the initramfs, at a point where `/sysroot` may not be mounted yet (#2486).
A race condition related to `sysroot.readonly` has been addressed by directly setting up sysroot readonly in initramfs (#2187).
---
```
Colin Walters (14):
Remove OstreeTlsCertInteraction bits from introspection
remote: Fix gcc `-fanalyzer` warning
deployment: Fix gcc `-fanalyzer` warning
sysroot: Fix gcc `-fanalyzer` warning
fetcher/soup: Fix gcc `-fanalyzer` warning
static-delta: Fix probably …
```
> Release 2021.6

- src/libostree/ostree-fetcher-curl.c
- src/libostree/ostree-repo-commit.c
- tests/test-commit-sign-sh-ext.c
This fixes a few warnings from coverity, none of which really
interesting.
> lib: misc static analysis fixes

- src/libostree/ostree-repo.c
This is trying to address:
https://pagure.io/fedora-iot/issue/48
Basically we changed rpm-ostree to start doing a shared lock during
commit by default, but this broke because pungi is starting a process
doing a commit for each architecture, and then trying to regenerate
the summary after each one.
This patch is deleting a big comment with a rationale for why
summary regeneration should be exclusive.  Point by point:
> This makes sure the commits and deltas don't get
> deleted while generating the summary.
But prune operations require an exclusive lock, which means that
data still can't be deleted when the summary grabs a shared lock.
> It also means we can be sure refs
> won't be created/updated/deleted during the operation, without having to
> add exclusive locks to those operations …
> repo: Change locking for summary regeneration to be shared

- src/libostree/ostree-repo.c
This tweaks a few invariant checks, turning them into safer assertions instead.
For more details on each, see individual commits.
One of them came up through casual code reading, so I did also check the rest of the file while at it.
> lib/repo: fix problematic invariant checks

- tests/libostreetest.c
I added this locally while looking into https://github.com/ostreedev/ostree/issues/2495 to make sure the environment was sane.
Current status looks ok with regards to that, but leaving these assertions may help future investigation crossing that same codepath.
---
This adds a couple of string assertions to make sure that the test run is sane.
> tests: assert mandatory values are present

- Makefile-tests.am
- src/ostree/main.c
- src/ostree/ot-main.c
- src/ostree/ot-main.h
- tests/test-cli-extensions.sh
This adds some logic to detect and dispatch unknown subcommands to
extensions available in `$PATH`. Additional commands can be
implemented by adding relevant `ostree-$verb` binaries to the system.
As an example, if a `/usr/bin/ostree-extcommand` extension is provided,
the execution of `ostree extcommand --help` will be dispatched to that
as `ostree-extcommand extcommand --help`.
Closes: https://github.com/ostreedev/ostree/issues/2480
> main: add support for CLI extensions via external binaries

- tests/test-cli-extensions.sh
This updates the test logic for CLI extensions, actually checking
for functional output from the subcommand.
It also cleans up some environmental leftover.
Ref: https://github.com/ostreedev/ostree/pull/2500
> tests/cli-extensions: tweak test logic

- src/libostree/ostree-soup-uri.c
- tests/test-commit-sign-sh-ext.c
soup-uri: Fix clang-analyzer warning
Fixes `Argument with 'nonnull' attribute passed null`.
(In upstream libsoup this code is gone, it uses `GUri` from glib,
which we probably could now too, but one thing at a time)
---
tests: Fix clang-analyzer not seeing through `g_error()`
Basically due to the glib structured logging rework we lost the
`noreturn` attribute on `g_error()`.
This is fixed in glib as of https://gitlab.gnome.org/GNOME/glib/-/commit/f97ff20adf4eb7b952dd83e2c13046fe9e282f50
But we might as well just throw an error here.
---
> two minor clang-analyzer fixes

- Makefile-libostree-defines.am
- src/libostree/ostree.h
This installs and exposes the content of `ostree-content-writer.h`,
so that library consumers can properly reference symbols defined
in that header.
Fixes: https://github.com/ostreedev/ostree-rs/issues/8
> lib: use ostree-content-writer header

- src/libostree/ostree-repo-static-delta-processing.c
This makes sure that a populated GError is returned when bsdiff
patching fails. The human-friendly label also helps in debugging.
> lib/static-delta: throw a proper error on bspatch failure

- .github/workflows/tests.yml
- ci/gh-install.sh
- configure.ac
- src/rofiles-fuse/main.c
This adds build-time configuration logic to automatically detect
and switch between libfuse 2.x and 3.x.
Fixes: https://github.com/ostreedev/ostree/issues/1881
Signed-off-by: Simon McVittie <smcv@collabora.com>
Co-authored-by: Luca BRUNO <luca.bruno@coreos.com>
> rofiles-fuse: Build using FUSE 3 if possible, falling back to FUSE 2

- configure.ac
New year, new ostree version!
This release adds transparent support for external sub-commands on the `ostree` binary. Custom binaries present in PATH in the form of `ostree-<subcmd>` will be now used as a fallback for sub-commands that are not natively implemented.
For example, this means that a custom `/usr/bin/ostree-my-command` binary can be used to transparently provide `ostree my-command`.
Build logic has been updated to support both libfuse 2.x and 3.x. Auto-detection is performed at configuration time, and the 3.x library is preferred from now on. Legacy 2.x support will be deprecated and removed in the future. 
Several fixes and safety improvements have been merged, also addressing some static analysis warnings. The git submodule for `bsdiff` has been updated to latest upstream …
> Release 2022.1

- src/libostree/ostree-sepolicy.c
- src/ostree/ot-main.c
- tests/libostreetest.c
- tests/test-gpg-verify-result.c
- tests/test-rollsum-cli.c
- tests/test-varint.c
This adds proper return-value checks on g_setenv calls.
It fixes a static analysis warning highlighted by Coverity.
> ostree: check g_setenv return value

- configure.ac
- src/libostree/ostree-1.pc.in
- src/ostree/ot-main.c
- tests/kolainst/destructive/basic-misc.sh
- tests/test-cli-extensions.sh
In fixing https://github.com/coreos/rpm-ostree/pull/3323
I felt that it was a bit ugly we're installing `/usr/bin/ostree-container`.
It's kind of an implementation detail.  We want users to use
`ostree container`.
Let's support values outside of $PATH too.
For example, this also ensures that TAB completion for `ost` expands
to `ostree ` with a space.
> main: Also support CLI extensions in `/usr/libexec/libostree/ext`

- src/libostree/ostree-sepolicy.c
This removes a 'g_setenv()' call, which could potentially be unsafe
in a multi-thread context.
The current libselinux codebase does not seem to check for
`LIBSELINUX_DISABLE_PCRE_PRECOMPILED`, so I think this has no effects
nowadays.
Additionally, I could not find any reference to it in libselinux
git history, so I'm not sure if it ever played any role at all.
My current understanding is that this is coming from version
incompatibilities between an older libselinux in the build environment
and a newer policy (with precompiled regexs) in the target.
But from the ML discussion I found, I think it eventually got
solved in a different way, possibly by avoiding the policy binary
caches.
Refs:
* https://www.spinics.net/lists/selinux/msg14822.html
* …
> libostree/sepolicy: get rid of a g_setenv() call

- src/libostree/ostree-sysroot.c
- src/libostree/ostree-sysroot.h
- src/ostree/ot-admin-builtin-finalize-staged.c
- src/ostree/ot-main.c
This is public API.  Motivated by
https://github.com/coreos/rpm-ostree/pull/3325/files#diff-56528694f6f3213d6fb88d872f77291412dceec263b57166519843b13eca9a4dR30
> sysroot: Add a public `#define OSTREE_PATH_BOOTED`

- .github/workflows/tests.yml
The ubuntu-latest VMs are currently based on 20.04 (focal). In focal,
libseccomp2 doesn't know about the close_range syscall[1], but
g_spawn_sync in impish tries to use close_range since it's defined in
glibc. That causes libseccomp2 to return EPERM as it does for any
unknown syscalls. g_spawn_sync carries on silently instead of falling
back to other means of setting CLOEXEC on open FDs. Eventually it causes
some tests to hang since once side of a pipe is never closed. Remove
this when libseccomp2 in focal is updated or glib in impish handles the
EPERM better.
1. https://bugs.launchpad.net/ubuntu/+source/libseccomp/+bug/1944436
Fixes: #2495
> github: Workaround glib/seccomp issue on Ubuntu impish

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
https://bugzilla.redhat.com/show_bug.cgi?id=2003532
Basically there's a systemd bug where it's losing the `_netdev`
aspect of Ceph filesystem mounts.  This means the network is taken
down before Ceph is unmounted.  In turn, our invocation of `sync()`
blocks on Ceph, which won't succeed.
And this in turn manifests as a failure to transition to the new
deployment.
I initially did this patch to just rip out the global `sync()`.  I
am pretty sure we don't need it anymore.  We've been doing individual
`syncfs()` on `/sysroot` and `/boot` for a while now, and those
are the only filesystems we should be touching.  But *proving* that
is a whole other thing of course.
To be conservative, let's instead just add a timeout of 5s on
our invocation of `sync()`.  It doesn't return any information on …
> deploy: Add a 5s max timeout on global filesystem `sync()`

- src/libostree/ostree-sysroot-deploy.c
We do implicitly have this data because we log timings via structured
metadata in a later journal entry, but it's quite common to lose
the structured metadata because a lot of tooling just grabs the default
syslog-compatible text from `journalctl`.
Let's be louder when we hit this case as a general rule too; I think
most people shipping ostree systems want to see if it's happening.
> deploy: Also log to journal if we time out global sync()

- src/libotutil/ot-variant-builder.c
When we clean up from an error, for example copy_file_range() failing
while we generate a static delta (perhaps caused by
https://gitlab.gnome.org/GNOME/libglnx/-/issues/3 or by a
genuine write error), we might free a variant builder that has a
non-null parent. Previously, this caused infinite recursion and a stack
overflow, repeatedly freeing the same object, but Luca Bruno suggested
that the intention here appears to have been to free the parent object.
Partially resolves https://github.com/ostreedev/ostree/issues/2525
(the other bug reported in that issue needs to be resolved by updating
libglnx to a version where libglnx#3 has been fixed).
cc @alexlarsson @lucab @oleid 
---
This resolves half of #2525 (#2530 is the other half).
> libotutil: Avoid infinite recursion during error unwinding

- src/libostree/ostree-repo-commit.c
This aligns all the assertion in the module. In particular, it gets
rid of all `g_return_val_if_fail` instances which may fail without
properly setting GError to the caller.
> lib/commit: clean up assertions

- .copr/Makefile
- ci/libbuild.sh
- ci/make-git-snapshot.sh
I'd like to enable auto-builds of this repo to
[copr.fedorainfracloud.org/coprs/g/CoreOS/continuous](https://copr.fedorainfracloud.org/coprs/g/CoreOS/continuous/) so it could
eventually feed into
https://github.com/coreos/fedora-coreos-tracker/issues/910.
> Add COPR integration Makefile

- man/ostree-summary.xml
- src/libostree/ostree-core.h
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- src/ostree/ot-dump.c
- tests/test-summary-view.sh
The commit metadata `version` key is well established but getting it for
a remote commit is cumbersome since the commit object needs to be
fetched and loaded. Including it in the summary additional metadata
allows a much more convenient view of what each of the remote refs
represents.
I was working on our release process at Endless and thought it would be so much easier to query the current OS version. I think the `version` metadata is well established enough to warrant inclusion in the summary.
> lib/repo: Add commit version metadata to summary metadata

- src/libostree/ostree-gpg-verify-result-dummy.c
- src/libostree/ostree-gpg-verify-result.c
I think I'm hitting issues due to this while using the Rust bindings:
https://github.com/coreos/rpm-ostree/pull/3406#issuecomment-1033084956
The bindings for those APIs use `from_glib_full` which says:
> Because ownership can only be transferred if something is already
> referenced, this is unsuitable for floating references.
> lib/gpg-verify-result: Add missing floating annotation

- Makefile-libostree.am
- src/libostree/ostree-bootloader-zipl.c
- src/libostree/ostree-bootloader-zipl.h
- src/libostree/ostree-bootloader.c
- src/libostree/ostree-bootloader.h
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/s390x-se-luks-gencpio
This enables Secure Execution. 
System could be installed (or qcow2 image used) with an ignition config, which provides `ibm-z-hostkey(s)`, and later used with SecureExecution. Upgrades, LUKS (key stored only within `sd-boot` encryped image), modification of initramfs/kargs are supported and were tested on `s390x zKVM` environment.
Requires - https://github.com/coreos/fedora-coreos-config/pull/1353
> s390x: add secure-execution support

- src/libostree/ostree-core.c
So I can drop an unnecessary use of `unwrap()` in Rust.
> core: Mark `ostree_create_directory_metadata` as `(not nullable)`

- src/libostree/ostree-bootloader-zipl.c
- src/libotutil/otutil.h
This needs to use the helper so that USE_LIBSYSTEMD still works as
expected.
> lib/bootloader: use ot_journal_print() instead of sd-journal

- configure.ac
This is failing for me as of recently but only when I build
without optimization.  I don't think we've ever written any
code that returned a large structure by value.
Let's just drop this one.
> build-sys: Drop `-Werror=aggregate-return`

- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo-refs.c
This patch makes it so that we mark the .commit file from a static delta
as partial before writing the commit to the staging directory. This
exactly mirrors what we do in meta_fetch_on_complete() when writing the
commit on that codepath, which should lend some credibility to the
correctness of this patch.
I have checked that this fixes an issue Flatpak users have been
encountering (https://github.com/flatpak/flatpak/issues/3479) which
results in error messages like "error: Failed to install
org.freedesktop.Sdk.Extension.texlive: Failed to read commit
c7958d966cfa8b80a42877d1d6124831d7807f93c89461a2a586956aa28d438a: No
such metadata object
8bdaa943b957f3cf14d19301c59c7eec076e57389e0fbb3ef5d30082e47a178f.dirtree"
Here's the sequence of events that lead to the error:
1. An install operation …
> Fix marking static delta commits as partial

- src/libostree/ostree-mutable-tree.c
mtree: Use declare-and-initialize style
Prep for further work.
---
mtree: Load traversed subdirs when creating parents
I'm working on enhancing the ostree-rs-ext test suite and I hit
a bug where walking a mtree and creating a parent would fail to
load lazy intermediate directories, e.g.:
/ -> usr -> bin
If we walked we'd load `/` but keep `usr` lazy, and then invalidation
would crash because it wasn't loaded.
If we're going to mutate a subdir, we need to have all the parents
loaded.
I know this is missing tests, but...it's a bit tedious to do with
the existing C tests.  Eventually soon we'll execute on merging
all 3 repos, and better share test suites.
---
>  mtree: Load traversed subdirs when creating parents

- Makefile-libostree.am
- configure.ac
- src/libostree/libostree-devel.sym
- src/libostree/libostree-released.sym
- tests/test-symbols.sh
A usual collection of bugfixes and smaller enhancements.  There is at least one bugfix worth calling out, which is https://github.com/ostreedev/ostree/pull/2549 that affects reliability of pulls with static deltas.  It's a nicely self contained change, and if you aren't in a position to update to this latest release, we suggest cherry picking it.
On the feature side, there's a new `ostree prune --commit-only` which allow decoupling deleting unreachable (or undesired) commits from actually deleting the referenced objects, so object garbage collection can be delayed for a later time, or amortized.
The summary file now contains version information, which can help avoid fetching commits just to display that (often desired) metadata.
Another notable feature is initial read side support for the …
> Release 2022.2

- apidoc/ostree-docs.xml
This fixes some missing sections in API reference, adding all the
relevant includes.
> apidoc: add missing page includes

- src/libostree/s390x-se-luks-gencpio
* s390x-se-luks-gencpio: Fix shebang syntax
An indented `#!` is technically meaningless, although many shells will
run text files with the shell if asked to execute them.
* s390x-se-luks-gencpio: Use interoperable path for bash
On OSs that do not consistently merge /usr/bin with /bin, the path to
bash has traditionally been /bin/bash.
---
New installations of Debian 11 are merged-/usr by default, but existing installations that were not already merged-/usr are not automaticlly merged. Debian 12 is meant to require merged-/usr, but the automatic migration path isn't yet in place, and individual packages in Debian 12 will still need to cope with non-merged-/usr to avoid over-constraining upgrade paths.
Users of entirely non-FHS OSs like NixOS might ask you to use `/usr/bin/env bash` instead …
> Fix shebang in s390x-se-luks-gencpio

- tests/test-prune.sh
If we use head(1) to take only the first two lines, then cut(1) and
earlier pipeline entries are killed by SIGPIPE (if they have not already
terminated), and that's flagged as an error under `set -o pipefail`.
Use an equivalent sed command to take exactly the second line, but
without SIGPIPE.
---
The fact that I need to know this does not say great things about the Unix pipeline philosophy.
> test-prune: Read to the end of cut(1) output

- src/libostree/ostree-repo-pull.c
Like every other error return path in this function, jump to the `out`
label on error here. Returning directly will cause leaks.
Spotted by reading the code, not actually necessarily encountered in the
wild.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
> ostree-repo-pull: Take correct out path on error

- README.md
According to the description on https://gitlab.com/fkrull/ostree-rs/ the repository is now moved to https://github.com/ostreedev/ostree-rs
> README.md: update ostree-rs language binding link

- src/boot/ostree-tmpfiles.conf
- tests/inst/src/sysroot.rs
This is referenced by https://github.com/ostreedev/ostree-rs-ext/blob/9645cee4f29786ba51ae9d62a52eeef9230146fd/lib/src/globals.rs#L16
specifically used for the (container image) pull secret in
`/run/ostree/auth.json`.
Let's pre-create the directory so users don't have to.
Motivated by https://github.com/openshift/machine-config-operator/pull/3007#discussion_r824172564
> tmpfiles: Create `/run/ostree`

- tests/test-cli-extensions.sh
On systems where `coreutils` are built with `--enable-single-binary=symlinks` like Nix, `/usr/bin/env` is symlinked to `/usr/bin/coreutils` and uses `argv[0]` to determine which program to run. Since the `test-cli-extensions.sh` created a new symlink named `ostree-env`, coreutils would be confused about the utility to choose, so running it would fail:
ostree-env: unknown program ‘ostree-env’
Try 'ostree-env --help' for more information.
Fixes: https://github.com/ostreedev/ostree/issues/2553
> tests/test-cli-extensions: Fix with single-binary coreutils

- ci/gh-install.sh
- src/libostree/ostree-sysroot-deploy.c
Whenever the user has SELinux enabled and has any local
modules/modifications installed, it is necessary to rebuild the policy
in the final deployment, otherwise ostree will leave the binary policy
files unchanged from last deployment as it detects difference against
the base content (in rpm-ostree case this is the RPM content).
To avoid the situation where the policy binaries go stale once any local
customization of the policy is made, try to rebuild the policy as part
of sysroot_finalize_deployment(). Use the special
--rebuild-if-modules-changed switch, which detects if the input module
files have changed relative to last time the policy was built and skips
the most time-consuming part of the rebuild process if modules are
unchanged (thus making this a relatively cheap operation if the …
> deploy: Try to rebuild policy in new deployment if needed

- src/libostree/ostree-repo-libarchive.c
The `archive_entry_symlink()` API can definitely return `NULL`,
reading through the libarchive sources.
I hit this in the wild when using old ostree-ext to try to unpack
a chunked archive.
I didn't try to characterize this more, and sorry no unit test right
now.
> libarchive: Handle `archive_entry_symlink()` returning NULL

- .github/workflows/docs.yml
- Makefile-man.am
- configure.ac
- docs/_config.yml
- docs/index.md
- docs/prep-docs.sh
- man/html.xsl
- man/index.xml
- man/ostree.xml
I'm sure this could be polished more (the systemd setup is a solid reference), but this publishes the manpages in the hosted ostree docs. I'm a little unsure the build system integration is the best. Right now it requires a separate configure option and is part of a normal automake target, but I also have a much simpler version that just adds the custom `manhtml` target.
> Publish man pages

- tests/kolainst/destructive/staged-deploy.sh
Our CI started falling over because coreos-assembler checks
for units stuck activating as of https://github.com/coreos/coreos-assembler/pull/2810
Really need to centralize the code for this and fix the root
problem, but...not today.
xref https://github.com/coreos/coreos-assembler/pull/2814
> ci: Mask zincati for synthetic update

- docs/ima.md
Now that the fixed code for `ima-sign` landed in
https://github.com/ostreedev/ostree-rs-ext/pull/283
> docs: Add new IMA document

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
* repo: Factor out _ostree_repo_auto_transaction_new()
This will allow the direct allocation in
ostree_repo_prepare_transaction() to be replaced with a call to this
function, avoiding breaking encapsulation.
* repo: Correctly initialize refcount of temporary transaction
Previously, the reference count was left uninitialized as a result of
bypassing the constructor, and the intended abort-on-error usually
wouldn't have happened.
Fixes: 8a9737a "repo/private: move OstreeRepoAutoTransaction to a boxed type"
Resolves: https://github.com/ostreedev/ostree/issues/2592
> Fix abort-on-error behaviour of transactions

- configure.ac
Release 2022.3
---
---
Closes: https://github.com/ostreedev/ostree/issues/2595
> Release 2022.3

- .github/workflows/docs.yml
See https://github.com/actions/checkout/issues/760
> ci: Work around GH actions `container:` + git + security bug

- .github/workflows/rust.yml
- deny.toml
Copied from https://github.com/ostreedev/ostree-rs-ext/pull/291
Part of unifying our CI.
> ci: use cargo-deny

- .cci.jenkinsfile
- ci/build.sh
- src/libostree/ostree-sysroot.c
sysroot: Quiet one gcc `-fanalyzer` warning
I don't think this can happen in practice, but add an assertion
to verify it.
---
ci: Drop gcc `-fanalyzer` by default
There's a pile of new warnings in GCC 12 from F36, I dug into
them but most of them seem inscrutable - I am not seeing the bugs.
For now to unblock further work, stop using this flag.
---
> ci: Drop gcc `-fanalyzer` by default

- .cci.jenkinsfile
- .github/workflows/tests.yml
- ci/ci-commitmessage-submodules.sh
Part of general momentum to leave heavy lifting (e.g. VM tests)
to Jenkins and Prow and use the cheaper/faster GH actions for
plain builds.
> ci: Move codestyle and min build to GH actions

- src/libostree/ostree-bootloader-zipl.c
- src/libostree/s390x-se-luks-gencpio
SE-qcow2 image comes with extra partition for `sd-boot`.  
Required by: https://github.com/coreos/coreos-assembler/pull/2822
> s390x: generate sd-boot at its own partition

- man/ostree.repo-config.xml
- src/libostree/ostree-sysroot-deploy.c
We want to parse a new "bls-append-except-default" key from ostree config. The
key-value pairs specified by this key will be added to the generated
BLS fragments of non-default deployments. They must follow the format
"key1,value1;key2,value2" and so on.
This change will allow us to land GRUB password support in FCOS.
closes: https://github.com/ostreedev/ostree/issues/2591
> ostree-systroot-deploy: parse bls-append-except-default key

- man/ostree-admin-instutil.xml
`<term><cmdsynopsis>` is not valid, causing the command to not be rendered
correctly.
Create one `<variablelist>` per `<cmdsynopsis>`. Inelegant but maintains
desired formatting.
Output of `xsltproc -o ~/test.html ./html.xsl ostree-admin-instutil.xml` attached.
Closes #2581
> man: Fix ostree-admin-instutil subcommands

- .cci.jenkinsfile
ci: Drop libsoup build in jenkins
GH actions is fast zero cost system that covers these build matrix
things well.  Let's keep our Fedora CI system doing more of the
qemu heavy lifting.
---
> ci: Drop libsoup build in jenkins

- src/libostree/ostree-mutable-tree.c
(nullable) and (optional) were missing on lookup()'s out parameters, which caused the rust bindings for the function to not work. Due to the missing (nullable), it would return a `Result<(GString, MutableTree), _>`, not a `Result<(Option<GString>, Option<MutableTree>), _>`, which led to panics.
> Fix annotations on ostree_mutable_tree_lookup()

- src/libostree/ostree-version.h.in
It inherently depends on the individual build, and can't
really be an official stable API for introspection users.
I've noticed the value of this flip flop when doing local builds.
I'm fairly certain no one is trying to use it from a higher level
language.
It'd probably make sense to even drop from the official C API,
but I'm trying to be conservative with that.
> Drop `OSTREE_BUILT_FEATURES` from introspection

- .github/workflows/rust.yml
- Cargo.toml
- rust-bindings/sys/Cargo.toml
There were some changes to the sys API for introspection fixes.
And add a feature for the current release, which is something
I'll add to the checklist for releases.
> rust: Bump semver, add feature for current release

- .github/workflows/rust.yml
In https://github.com/ostreedev/ostree/pull/2633 I realized
that our CI only builds git of libostree or git of rust-bindings,
not git of both.  And we definitely want to test the latter too,
so e.g. the Rust tests *also* become tests for changes to the C code.
> ci: Add a flow that does a git libostree + git rust-bindings

- src/libostree/ostree-repo-prune.c
I missed the second prune path when working on
https://github.com/ostreedev/ostree/pull/2635
> prune: Also use object set API in `ostree_repo_prune_from_reachable()`

- Cargo.toml
rust-bindings: Fix repository reference
Since the repo merge.
---
rust-bindings: use correct README.md
I noticed at https://crates.io/crates/ostree/0.14.0
that the `README.md` was wrong...
---
rust-bindings: Update cargo package list
When we did the merger, it turns out cargo by default is basically
going to include all of stuff in the git repository root directory
which is "libostree".  We just want the stuff in `rust-bindings/`.
I initially tried adding `include = "rust-bindings/"` but
according to
https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields
specifying `include` means that `exclude` is
ignored, which is kind of annoying.  Further, doing so *also*
turns off the cargo automatic rules for handling e.g. `gitignore`.
So for now I went with the …
> Rust bindings cargo updates

- tests/inst/Cargo.toml
In the interest of cross-testing and keeping things up to date.
Hmm, I think we need to set up dependabot here.
> tests/inst: Bump the version of ostree-ext

- src/libostree/ostree-repo.c
- src/ostree/ot-builtin-fsck.c
repo: Document non-obvious way to list all commits
I was going to add an API for this and then realized the empty
string does it.
---
fsck: Don't load all object names into memory
We recently discovered `list_objects()` is inefficient with memory.
The more efficient `list_objects_set()` API isn't yet public, but
this fsck code actually just skips over non-commit objects, and
we already have an API to list just those.
---
>  fsck: Don't load all object names into memory

- src/ostree/ot-builtin-fsck.c
Followup to https://github.com/ostreedev/ostree/pull/2644
---
fsck: De-indent loop
Could have done this in the previous change, but wanted to avoid
excessive diff noise.
---
fsck: Move most commit processing into helper function
The inner loop was way too long; split out most of the heavy
lifting around backrefs and tombstones into a helper function.
---
fsck: Use `load_variant_if_exists`
This cleans up error handling here.
---
> fsck: A few more cleanups

- Cargo.toml
- rust-bindings/tests/util/mod.rs
Because the source is in a subdirectory, we lose out on cargo target
autodiscovery.
I noticed this when I edited one of the tests in a way that
should have failed, but didn't...
> rust-bindings: Wire up `tests/`

- .github/workflows/rust.yml
- Cargo.toml
- rust-bindings/src/object_name.rs
- rust-bindings/sys/Cargo.toml
- tests/inst/Cargo.toml
- tests/inst/src/destructive.rs
- tests/inst/src/treegen.rs
rust: Switch to 2021 edition
No real changes.
```
$ cargo fix --edition
note: Switching to Edition 2021 will enable the use of the version 2 feature resolver in Cargo.
This may cause some dependencies to be built with fewer features enabled than previously.
More information about the resolver changes may be found at https://doc.rust-lang.org/nightly/edition-guide/rust-2021/default-cargo-resolver.html
When building the following dependencies, the given features will no longer be used:
libc v0.2.126 removed features: extra_traits
The following differences only apply when building with dev-dependencies:
getrandom v0.2.6 removed features: std
```
which looks OK to me.
---
ci: Bump MSRV
To match what's in ostree-rs-ext.
---
rust: Use inline `format!` variables in a few places
Since our MSRV …
> rust: Switch to 2021 edition, bump MSRV, a few `format!` updates

- src/ostree/ot-admin-builtin-os-init.c
- src/ostree/ot-admin-builtin-undeploy.c
- src/ostree/ot-admin-builtin-unlock.c
cli/os-init: Port to C99 style
General background cleanup; motivated by a recent PR which
was using pre-C99 code as a base.
---
cli/undeploy: Port to C99 style
General background cleanup.
---
cli/unlock: Port to C99 style
General background cleanup.
---
> cli: a few "Port to C99 style"

- tests/test-basic-c.c
Not all filesystems support extended attributes. This test uses
/var/tmp to try to get an extended-attributes-capable filesystem,
but that might not succeed.
---
Some Debian autobuilders operate entirely from (very large) tmpfs filesystems, to avoid disk I/O and `fsync()` overhead. On those systems, not even `/var/tmp` has extended attributes available.
> test-basic-c: Don't assert that extended attributes are available

- tests/inst/src/destructive.rs
It was removed from FCOS:
https://github.com/coreos/fedora-coreos-tracker/issues/770
> tests/inst/destructive: stop disabling fedora-coreos-pinger

- .github/workflows/rust.yml
- Cargo.toml
- rust-bindings/src/repo.rs
ci/rust: Enable `cap-std-apis` in default build, add a no-feature build
Our CI was missing coverage of `cap-std-apis`.
---
ci/rust: Change MSRV to `cargo check`
No reason to codegen just to throw it away.  We could test here too,
but eh.
---
Fix clippy lint in cap-std bits
---
rust: Bump semver to 0.15
Prep for some breaking changes.
---
Bump to cap-std 0.25 and io-lifetimes 0.7
Prep for bumping ostree-rs-ext, which will help bump rpm-ostree,
which will get it out of having two copies of rustix.
---
> rust: Bump semver to 0.15 && bump cap-std 0.25

- src/libostree/ostree-bootloader-zipl.c
same name is used by `coreos-installer`
> s390x: rename sd-boot to sdboot

- src/libostree/ostree-repo-prune.c
- src/libostree/ostree-repo.h
After landing the new --commit-only functionality, we still noticed
exceedingly long pruning times in large repos. Lets add an optimization
that will only retrieve commit objects when --commit-only flag is used.
> lib/prune: speed up pruning by retrieving only commits

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-upgrader.c
It's falliable, and in one place we were actually ignoring
the error and leaving a `NULL` repo object which is just a trap
for people coming along later since it's rarely nullable.
Quite a while ago we switched to loading the repo at the same time
as the sysroot; convert callers in the library to use this infallible
accessor.
Prep for another patch which will use the repo object.
> lib: Stop using old `ostree_sysroot_get_repo()` API

- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot-deploy.c
This PR is followup from https://github.com/coreos/coreos-assembler/pull/2863
Summary of changes:
- Moved bls-append-except-default parsing logic to `reload_sysroot_config()`
- Made sure heap allocated memory is being free'd
> ostree-repo: bls-append-except-default followup

- deny.toml
This extends the license set basically and ignores private repos
(which we don't have any yet).
> deny: Sync with rpm-ostree

- README.md
ostree-rs was merged into ostree, so link to the rust bindings within this repository.
> Fix link to rust bindings

- src/libostree/ostree-sysroot-deploy.c
These places are all safe, but it would catch bugs in the future
more clearly to trip an assertion here.
> sysroot: Add a few more assertions about `boot_fd`

- src/libostree/ostree-sysroot.c
For historical reasons we have a fair bit of distinct sysroot
initialization going on.  A lot of code is calling *just* the new
`ensure_writable()` API, which does basically what you'd expect...
except if we're not using a mount namespace.
Which is the case in unit tests and legacy setups.
Change this API to also ensure the sysroot is fully initialized
even in those cases.  Specifically we'll have `self->sysroot_fd`.
For now, callers that need `/boot` also need to separately
call `_ensure_boot_fd()`.
> sysroot: Have `ensure_writable` also always initialize

- deny.toml
This is used by the unicode crate now and is definitely a compatible
FOSS license.
> deny.toml: Add `Unicode-DFS-2016`

- src/libostree/ostree-linuxfsutil.c
- src/libostree/ostree-linuxfsutil.h
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-sysroot-deploy.c
- src/ostree/ot-main.c
Remove unused `linux/fs.h` includes
Prep for fixing conflicts introduced by newer glibc.
cc https://github.com/ostreedev/ostree/issues/2685
---
Move FIFREEZE/FITHAW ioctl invocations into linuxfsutil.c
Should help avoid conflicts between glibc and linux headers.
Closes: https://github.com/ostreedev/ostree/issues/2685
---
> Handle conflicts between newer glibc and kernel headers

- tests/inst/Cargo.toml
- tests/inst/src/insttestmain.rs
- tests/inst/src/test.rs
I just released [a new version of libtest-mimic](https://github.com/LukasKalbertodt/libtest-mimic/releases/tag/v0.5.0). This is one of the bigger projects using it, so as a sanity check whether the new version still works for real world users, I just did this update. It allowed to remove some of the code here as the API changed a bit.
Two things to note:
- `libtest-mimic` requires Rust 1.58. 
- I do not know about this project at all and did not test anything. Please review carefully and/or test.
> Update to `libtest-mimic` 0.5.0

- src/libostree/ostree-repo-commit.c
- tests/kolainst/destructive/staged-deploy.sh
The idea of payload linking is to reflink between objects where
possible. Instead of relying on `glnx_regfile_copy_bytes` to hit the
`FICLONE` path, just call `FICLONE` directly. At that point in the code,
we've already established that the source and dest repos are on the same
filesystem and that it supports `FICLONE`.
Related: https://gitlab.gnome.org/GNOME/libglnx/-/merge_requests/41
Related: https://github.com/ostreedev/ostree/pull/2684#issuecomment-1204068437
> lib/commit: Directly use FICLONE for payload link

- man/ostree-rev-parse.xml
- src/ostree/ot-builtin-rev-parse.c
- tests/basic-test.sh
cli/rev-parse: Add `--single` option
In the current "ostree native container" flow, we're inserting
a commit object into the repo but with no refs.
We have hacks in a few places to find the commit digest via e.g.
`find repo/objects -name *.commit` but that's a horrible hack.
Add `ostree rev-parse --single` which will print the single commit,
and error out if there is not exactly one commit.
>  cli/rev-parse: Add `--single` option

- src/libostree/ostree-sysroot-deploy.c
This fixes a typo in the `allow-none` annotation on
`ostree_sysroot_deployment_set_kargs_in_place` argument.
> libostree: fix a typo in annotation

- src/libostree/ostree-bootloader-zipl.c
- src/libostree/s390x-se-luks-gencpio
```
commit 14a7c0c74bc080bbe8529c8645b895c118b83d9a
Author: Nikita Dubrovskii <nikita@linux.ibm.com>
Date:   Thu Jun 23 15:54:04 2022 +0200
s390x: rename sd-boot to sdboot
Signed-off-by: Nikita Dubrovskii <nikita@linux.ibm.com>
commit 972f00e4835053b5c000937be2847da658f005dd
Author: Nikita Dubrovskii <nikita@linux.ibm.com>
Date:   Fri May 27 09:13:18 2022 +0200
s390x: do not unpack existing initrd, just append LUKS keys to its copy
Signed-off-by: Nikita Dubrovskii <nikita@linux.ibm.com>
commit b03fa626f1c3242cbf5555a885f69ac03563c95f
Author: Nikita Dubrovskii <nikita@linux.ibm.com>
Date:   Tue May 24 19:30:35 2022 +0200
s390x: fail on error during reading of SecureExecution sysfs flag
commit d0005698596ff3e434a3e4ddd4aea8d4c618079f
Author: Nikita Dubrovskii <nikita@linux.ibm.com>
Date: …
```
> Backport Secure Execution enablement from 2022.5

- src/libostree/ostree-sign-ed25519.c
This is the backport of https://github.com/ostreedev/ostree/commit/83e6357186be11fb8f2a6b66fab3730c44ee59dd for the `rhel-8` branch.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2119444
---
The ed25519 signature verification code does not
check that the signature is a minimum/correct length.
As a result, if the signature is too short, libsodium will end up
reading a few bytes out of bounds.
Reported-by: Demi Marie Obenour <demi@invisiblethingslab.com>
Co-authored-by: Demi Marie Obenour <demi@invisiblethingslab.com>
Closes: https://github.com/ostreedev/ostree/security/advisories/GHSA-gqf4-p3gv-g8vw
> sign/ed25519: Verify signatures are minimum length

- src/libostree/ostree-repo-commit.c
Commit 540e60c3 introduced _ostree_repo_auto_transaction_new(), a
private constructor to OstreeRepoAutoTransaction, by factoring out
some code from _ostree_repo_auto_transaction_start(). This factored
code increased the refcount of the 'repo' variable.
Subsequent commit 71304e854c made ostree_repo_prepare_transaction()
use ths newly introduced constructor. However, in this function, the
happy path assumed no ref was taken, and therefore did not unref it.
Commit 71304e854c didn't add the corresponding unref either.
This leaks a reference to OstreeRepo when calling
ostree_repo_prepare_transaction().
Plug this leak by using g_clear_object() to clear the repo field
of OstreeRepoAutoTransaction, instead of simply setting it to NULL.
Closes https://github.com/flatpak/flatpak/issues/4928
> lib/commit: Unref repo on success

- .github/workflows/tests.yml
I didn't deep dive into debugging this but I'm pretty sure it's
https://gitlab.gnome.org/GNOME/glib/-/issues/2580
which is us having an older Docker in the middle here.
---
> ci: Also drop seccomp on debian testing

- docs/deployment.md
I was explaining staged deployments to someone today and was looking for
a doc but we didn't have any. Fix that.
> docs: Add section about staged deployments

- buildutil/glibtests.m4
configure scripts need to be runnable with a POSIX-compliant /bin/sh.
On many (but not all!) systems, /bin/sh is provided by Bash, so errors
like this aren't spotted. Notably Debian defaults to /bin/sh provided
by dash which doesn't tolerate such bashisms as '=='.
This retains compatibility with bash.
Fixes configure warnings/errors like:
```
checking whether to build static libraries... no
./configure: 14795: test: unexpected operator
```
Signed-off-by: Sam James <sam@gentoo.org>
> buildutil/glibtests.m4: fix bashism

- rust-bindings/conf/ostree.toml
- rust-bindings/src/repo.rs
- rust-bindings/tests/repo/mod.rs
rust: Bind `ostree_repo_list_commits_starting_with`
I wanted to use this as a fallback for
https://github.com/ostreedev/ostree-rs-ext/pull/351/commits/30dee81c22ad5cb90e77198d3ddbcc25d388afb5
---
>  rust: Bind `ostree_repo_list_commits_starting_with`

- src/libostree/ostree-sysroot-deploy.c
- tests/kolainst/destructive/kargs-edit-in-place.sh
This is to support pending deployments instead of rasing assertion.
For example:
```
$ sudo rpm-ostree kargs --append=foo=bar
$ sudo ostree admin kargs edit-in-place --append-if-missing=rw
```
After reboot we get both `foo=bar rw`.
Fix https://github.com/ostreedev/ostree/issues/2679
> Fix `ostree admin kargs edit-in-place` assertion when deployments are pending

- Makefile-boot.am
- src/boot/ostree-finalize-staged-hold.service
- src/boot/ostree-finalize-staged.service
- src/ostree/ot-admin-builtin-finalize-staged.c
- src/ostree/ot-main.c
- src/ostree/ot-main.h
- tests/inst/src/destructive.rs
- tests/kolainst/destructive/boot-automount.sh
If `/boot` or `/sysroot` are automounts, then the unit will be stopped
as soon as the automounts expire. That's would defeat the purpose of
using systemd to delay finalizing the deployment until shutdown. This is
not uncommon as `systemd-gpt-auto-generator` will create an automount
unit for `/boot` when it's the EFI System Partition and there's no fstab
entry.
Instead of relying on systemd to run the command via `ExecStop` at the
appropriate time, have `finalize-staged` open `/boot` and `/sysroot` and
then block on `SIGTERM`. Having the directories open will prevent the
automounts from expiring, and then we presume that systemd will send
`SIGTERM` when it's time for the service to stop. Finalizing the
deployment still happens when the service is stopped. The difference is
that the process …
> finalize-staged: Ensure /boot and /sysroot automounts don't expire

- src/ostree/ot-admin-builtin-finalize-staged.c
Followup from discussion in
https://github.com/ostreedev/ostree/pull/2544#discussion_r958840936
This is more efficient; no need to have the kernel context switch
us in at shutdown time just so we can turn around and call
`exit()`.
> finalize-staged: Don't listen to `SIGTERM`, just let kernel exit us

- src/libostree/ostree-fetcher-curl.c
https://github.com/flatpak/flatpak/pull/5074
> ostree-fetcher-curl: check for HTTP2 support before trying to use it

- src/libostree/ostree-bootconfig-parser.c
- src/libostree/ostree-bootloader.c
This tweaks some invariants checks into full assertions, in order
to avoid returning to the caller in case of known invalid states.
> lib/bootloader: assert invariants

- src/libostree/ostree-mutable-tree.c
This drops several NULL checks against filename input argument.
Those checks are both redundant (as filename validation already checks for that) and dangerous (as they return early without setting an error value).
> lib/mtree: drop redundant name checks

- src/libostree/ostree-repo-static-delta-compilation.c
- src/libotutil/ot-variant-builder.c
This enhances a bunch of helpers related to GVariant building, in
order to properly handle errors and avoid some potential cases of
unexpected NULL results.
> otutil: add error handling to variant builders

- src/libostree/ostree-repo-pull.c
The documented option is incorrect and has been since it's introduction in 2c55bc6997.
> lib/pull: Fix max-metadata-size documentation

- src/libostree/ostree-repo.c
This initializes a boolean variable that was previously left uninitialized.
It was detected by a RHT internal static analyzer.
> lib/repo: properly initialize boolean variable

- src/libostree/ostree-sysroot-deploy.c
This explicitly ignores the results of two optional variant lookups, in order to pacify a RHT internal static analyzer.
> lib/sysroot-deploy: explicitly handle `g_variant_lookup` results

- .github/workflows/tests.yml
- Makefile-tests.am
- bash/ostree
- man/ostree-checkout.xml
- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-repo.h
- src/libostree/ostree-sysroot-deploy.c
- src/ostree/ot-builtin-checkout.c
- tests/archive-test.sh
- tests/basic-test.sh
- tests/kolainst/data-shared/libtest-core.sh
- tests/libtest.sh
- tests/test-admin-deploy-whiteouts.sh
Introduces an intermediate format for overlayfs storage, where
.wh-ostree. prefixed files will be converted into char 0:0
whiteout devices used by overlayfs to mark deletions across layers.
Related-Issue: #2712
> Support overlayfs whiteouts on checkout

- configure.ac
This release contains a collection of bugfixes and enhancements. Notable fixes concern `finalize-staged`, which should now better support automounted partitions and skip waiting for termination signal.
A file descriptor leak has been fixed in the commit logic. The codebase has also been fixed to avoid conflicting declarations when building with latest `glibc` (>=  2.36). Thanks @GeorgesStavracas for both fixes!
On the feature side, there is now basic support for handling overlayfs whiteouts on checkout through a new `--process-passthrough-whiteouts` flag. This is useful for users that need to carry container storage embedded into ostree commits. Thanks @mangelajo for that!
The `ostree rev-parse` command gained a new `--single` flag to better support repositories containing exactly one …
> Release 2022.6

- .copr/Makefile
Recent git became more strict wrt git repos in parent dirs owned by other users. This broke our COPR builds due to the git checkout being created by a different user and mounted in. We need to explicitly mark the repo as safe.
For more information, see:
https://github.com/actions/checkout/issues/760
(cherry picked from commit 2e564aef074aa0ba39b2ba768dd06fe65858b3df)
> [rhel8] copr: mark git checkout as safe

- ci/make-git-snapshot.sh
It turns out COPR is buggy and does:
$ git clone --recursive
$ git switch `<branch>`
This results in the submodules not being initialized for the target branch.  Work around this by always re-initializing submodules.
> make-git-snapshot: Always run `git submodule init`

- src/libostree/ostree-repo-checkout.c
This fixes a typo in an error message, resulting in a GID vs UID mixup.
It was detected by RH internal static checks.
> lib/repo-checkout: fix typo in error message

- src/libostree/ostree-bootloader-zipl.c
This adds a missing error check when opening an initrd in s390x Secure Execution (SE) logic.
It was detected by RH internal static checks.
> lib/bootloader-zipl: check for errors when opening initrd

- rust-bindings/tests/repo/generate_static.rs
- rust-bindings/tests/repo/mod.rs
- src/libostree/ostree-repo-static-delta-compilation.c
This enhances the logic handling GVariant parameters within
`ostree_repo_static_delta_generate()`.
Several of those entries are expected to be zero-terminated values,
and this implicit assumption has been observed to be an hidden trap
in languages where strings and arrays may not carry a terminator value
(e.g. Rust).
In order to improve the situation, this makes the documentation more
explicit and actively tries to catch invalid input parameters.
Closes: https://github.com/ostreedev/ostree/issues/2728
---
[Original PR text below here]
This commit adds a test for the rust interface.
It should test the static-delta generation into a specified file.
Unfortunately it does not work because the ostree-lib throws an error:
```
---- repo::generate_static::should_generate_static_delta_at stdout …
```
> lib/static-delta: document and check parameters format

- .cci.jenkinsfile
We're hitting memory limits when running the reprovisioning tests.
We should investigate why we need 1Gi of overhead, but for now to get unblocked let's just bump it.
> ci: bump cosaPod memory requirement to 5Gi

- src/libostree/ostree-sign-ed25519.c
This converts several invariant checks to asserts.
Most of the functions in this file were already using assertions, so this aligns the remaining few outliers to the rest.
> lib/sign-ed25519: convert invariant checks to assertions

- src/libostree/ostree-repo-refs.c
This tweaks a logic check in order to return a proper error value when the related condition is not satisfied.
> lib/repo-refs: properly return an error value

- .github/workflows/rust.yml
- rust-bindings/src/repo_checkout_at_options/repo_checkout_filter.rs
- rust-bindings/src/sysroot_deploy_tree_opts.rs
- rust-bindings/src/sysroot_write_deployments_opts.rs
This bumps the Rust toolchain for clippy/rustfmt to 1.64.
> ci/rust: bump linting toolchain to latest stable (1.64)

- .github/workflows/rust.yml
A late CI update with a followup for https://github.com/ostreedev/ostree/pull/2742.
> ci/rust: test from git using latest feature

- Cargo.toml
- rust-bindings/sys/Cargo.toml
This prepares for a new release of both crates, now using the gtk-rs 0.15 stack.
Ref: https://github.com/ostreedev/ostree/pull/2743
> cargo: prepare ostree 0.16.0 and ostree-sys 0.11.0

- src/libostree/ostree-sysroot-deploy.c
Basically, it should not be necessary - the policy should be up-to-date.  We don't want to force on continual policy rebuilds.
Even trying to run bwrap when we're *not* in a booted root can cause failures in nested containerization scenarios.
Closes: https://github.com/ostreedev/ostree/issues/2758
> deploy: Don't rebuild selinux policy on first deployment

- .copr/Makefile
This adds a tag filter to the logic which emits version labels for COPR build, so that it avoids mistakenly picking up tags belonging to the Rust bindings.
> copr: only use libostree tags

- .cci.jenkinsfile
It seems likely that we're allocating more RAM here.  What we really need to do is for cosa to express the necessary RAM requirements declaratively, then we compute pod requirements from that.
> ci: Bump memory for ISO testing flow

- Cargo.toml
This was one source of our semver bumps; let's switch to 1.0.
> rust: Update to cap-std 1.0

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-sign-ed25519.c
- src/libotutil/ot-checksum-utils.c
- src/libotutil/ot-variant-utils.c
- tests/test-commit-sign-sh-ext.c
* Update submodule: libglnx
- Backport g_memdup2 (see #2751)
* Replace calls to g_memdup() with g_memdup2()
g_memdup() is subject to an integer overflow on 64-bit machines if the
object being copied is larger than UINT_MAX bytes. I suspect none of
these objects can actually be that large in practice, but it's easier
to replace all the calls than it is to assess whether we need to
replace them.
A backport in libglnx is used on systems where GLib is older than 2.68.x.
> Replace calls to g_memdup() with g_memdup2()

- Cargo.toml
- rust-bindings/tests/repo/checkout_at.rs
We can use cap-std in our tests.
> rust: Drop `openat` dependency

- Makefile-libostree.am
- apidoc/ostree-sections.txt
- rust-bindings/sys/src/lib.rs
- src/libostree/libostree-devel.sym
- src/libostree/ostree-kernel-args.c
- src/libostree/ostree-kernel-args.h
Check if an argument is present in OstreeKernelArgs. This is a way to make easier idempotent append and delete operations.
Closes #2329
Signed-off-by: Rafael Garcia Ruiz <rafael.garcia@collabora.com>
> ostree_kernel_args_contains for OstreeKernelArgs

- apidoc/ostree-sections.txt
- rust-bindings/sys/src/lib.rs
- src/libostree/libostree-devel.sym
- src/libostree/ostree-kernel-args.c
- src/libostree/ostree-kernel-args.h
ostree_kernel_args_delete_if_present checks if an argument is present in OstreeKernelArgs and delete it.
#2329 
Signed-off-by: Rafael Garcia Ruiz <rafael.garcia@collabora.com>
> Idempotent delete operation for  OstreeKernelArgs

- .cci.jenkinsfile
We can't override host binaries in this case.  We'll need to watch carefully and verify we're still testing things.
> ci: Fix case where cosa != buildroot

- .github/workflows/rust.yml
- Cargo.toml
This bumps MSRV to 1.63, in order to prepare for the next version of gtk-rs stack.
Refs:
* https://gtk-rs.org/blog/2022/10/18/new-release.html
* https://github.com/ostreedev/ostree/issues/2750
> cargo: bump minimum Rust version to 1.63

- ci/Makefile.dist-packaging
- ci/make-git-snapshot.sh
Another attempt at fixing logic for version detection in COPR.
Followup to https://github.com/ostreedev/ostree/pull/2762.
> ci: adjust git tags filtering

- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
- src/libostree/ostree-sysroot.c
- src/libostree/ostree-sysroot.h
- src/ostree/ot-main.c
This lowers down into the C library some logic we
have in the binary/app logic, in prep for having more Rust-native CLI code in https://github.com/ostreedev/ostree-rs-ext/pull/412
Basically we want to *ensure* a mount namespace by invoking `unshare()` if necessary, instead of requiring our callers to do this dance.
This also helps fix e.g.
Closes: https://github.com/ostreedev/ostree/issues/2769
> sysroot: Add an API to initialize with mountns

- tests/libtest.sh
- tests/test-basic-bare-split-xattrs.sh
- tests/test-repo-finder-mount-integration.sh
IMO, tools invoking `sudo` automatically is a huge anti-pattern. Require this to be opt-in.
In practice also...these tests really want to be *integration* and not unit tests because involving `sudo` alongside uninstalled binaries just creates a giant mess.
Closes: https://github.com/ostreedev/ostree/issues/2761
> tests: Require OSTREE_TEST_SUDO to be set to use `sudo`

- tests/inst/Cargo.toml
- tests/inst/src/sysroot.rs
- tests/inst/src/treegen.rs
tests/inst: Update to latest ostree-ext
---
tests/inst: Drop nix dependency
It has various semver bumps and we were literally just using
it to duplicate what's already in `libc`.
---
tests/inst: Update cap-std-ext to 1.0
---
tests/inst: Update sh-inline
---
> Testinst updates

- .github/workflows/tests.yml
Today it's just the Jenkins flow which builds our Rust integration tests.  Let's add a flow to the GH actions which does this, and also runs inside a (privileged) container.
Prep for doing more testing of the ostree-container path here.
> ci: Add a flow that combines C build and Rust integration tests

- Makefile-libostree.am
- configure.ac
- src/libostree/libostree-devel.sym
- src/libostree/libostree-released.sym
- tests/test-symbols.sh
Nothing critical, but a fair number of smaller fixes in the last month.
Closes: https://github.com/ostreedev/ostree/issues/2785
> Release 2022.7

- Cargo.toml
- rust-bindings/sys/Cargo.toml
We switched gio and cap-std versions, so we need to bump our own semver.
> rust: Bump to 0.17

- configure.ac
- src/libostree/ostree-repo.c
This tweaks autoconf logic in order to use pkg-config for gpgme and gpg-error when available.
Recent versions of gpgme directly provide threaded support, and gpg-error started shipping a .pc file. Thus on recent distributions it is possible to directly use pkg-config for both. On older environments, the legacy logic is kept in place.
> configure: use pkg-config with newer gpgme and gpg-error

- src/libostree/ostree-core-private.h
ALLPERMS is glibc specific, add a definition for musl.
Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
> lib/repo-checkout: Add ALLPERMS for musl

- tests/test-commit-timestamp.sh
musl uses "Result not representable" for ERANGE, support this in addition to glibc's "Numerical result out of range".
Signed-off-by: Alex Kiernan <alex.kiernan@gmail.com>
> tests: Handle musl's ERANGE mapping

- Makefile-libostree.am
- rust-bindings/sys/src/lib.rs
- src/libostree/ostree-bootloader-aboot.c
- src/libostree/ostree-bootloader-aboot.h
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot.c
aboot is special in that it packages kernel, initrd, cmdline dtb and signature one combined image (similar to upcoming unified kernel images). This is then loaded as an image into an aboot partition.
This image is signed by the OS vendor and covers everything in the image. So locally on the deployed system it should not be possible to boot an unsigned image (unless signature checking is turned off).
We call a shell script aboot-deploy when it is required to write a new image to the aboot partition (a file typically starting with aboot and ending in .img extension). This shell script may also read some configurations from a .cfg file.
Signed-off-by: Eric Curtin <ecurtin@redhat.com>
> bootloader: Add an aboot (Android) bootloader backend

- tests/inst/Cargo.toml
Due to some vulnerabilities[1][2], all versions prior to 0.9.4 have been yanked from crates.io. There have been some API changes since 0.6.0, but none of them affect the simple `hyper_staticfile::Static` usage here.
1. https://rustsec.org/advisories/RUSTSEC-2022-0069.html
2. https://rustsec.org/advisories/RUSTSEC-2022-0072.html
> tests/inst: Update hyper-staticfile to 0.9.4

- Makefile-tests.am
- bash/ostree
- man/ostree-find-remotes.xml
- man/ostree-pull.xml
- man/ostree-refs.xml
- man/ostree-remote.xml
- man/ostree-show.xml
- src/ostree/ot-builtin-refs.c
- src/ostree/ot-builtin-show.c
- src/ostree/ot-builtin-summary.c
- src/ostree/ot-dump.c
- src/ostree/ot-dump.h
- src/ostree/ot-remote-builtin-refs.c
- src/ostree/ot-remote-builtin-summary.c
- tests/basic-test.sh
- tests/test-pull-summary-sigs.sh
- tests/test-refs.sh
- tests/test-remote-refs.sh
- tests/test-signed-pull-summary.sh
- tests/test-summary-update.sh
Often I want to quickly inspect local and remote repos to see what's currently in them. While it's often better to write something that uses the API to get the precise desired information, the CLI is very handy for quickly assessing the situation. This adds some options to various CLI builtins to expose or improve that information.
> Various CLI improvements

- src/libostree/ostree-sysroot-deploy.c
Current FCOS emits a warning:
```
[root@cosa-devsh ~]# journalctl -b -1 -u ostree-finalize-staged --grep=deprecated
Nov 01 20:21:21 cosa-devsh ostree[2481]: The --rebuild-if-modules-changed option is deprecated. Use --refresh instead.
[root@cosa-devsh ~]#
```
> deploy: Use `semodule --refresh` if available

- tests/libtest.sh
On Debian systems, by default only root has /{usr/,}sbin in PATH.
---
Similar to containers/bubblewrap#228. This should give us test coverage for rofiles-fuse on Ubuntu's autopkgtest infrastructure; previously that wasn't tested.
> tests: Ensure non-root users have access to libcap tools

- src/libostree/ostree-bootconfig-parser.c
- src/libostree/ostree-deployment.c
- src/libostree/ostree-kernel-args.c
- src/libostree/ostree-mutable-tree.c
- src/libostree/ostree-ref.c
- src/libostree/ostree-ref.h
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-file.c
- src/libostree/ostree-repo-pull-verify.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
- src/libostree/ostree-sepolicy.c
- src/libostree/ostree-sysroot-deploy.c
Increase the coverage of the GObject Introspection annotation and most notably replace the use of "allow-none" with "out" parameters to "nullable" or "optional" as the previous annotation is deprecated and ambiguous.
> libostree: Enhance the annotation coverage

- src/libostree/ostree-repo-commit.c
The small buffer size results in really bad performance under any FUSE-based filesystems with round-trips.
> Increase buffer size for create_regular_tmpfile_linkable_with_content

- tests/kolainst/nondestructive/itest-pull-space.sh
XFS now seems to want filesystems larger than 300MB, so switch to ext4.  Also use `20MiB` so we align to 512b sectors to squash a `losetup` warning.
Also tweak some of the numbers to still work.
> itest-pull-space: Use mkfs.ext4, align to at least 512b

- src/libostree/ostree-core.c
A recent [change in glib](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3261) requires that the appropriate attribute be available when calling getters. ostree core only sets this attribute on regular files, and frequently triggers the critical warning. Solve this by setting standard::size to zero for non-regular files.
Fixes https://github.com/ostreedev/ostree/issues/2827
> core: Ensure glib standard::size attribute is always set

- src/libostree/ostree-core.c
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot-deploy.c
- src/libotutil/ot-fs-utils.c
- tests/test-repo-finder-mount.c
Based on #2822.
* Use g_steal_fd() in preference to glnx_steal_fd()
g_steal_fd() exists in GLib since 2.70, and libglnx has a backport for
older GLib versions, equivalent to the libglnx-specific glnx_steal_fd().
> Use g_steal_fd() in preference to glnx_steal_fd()

- Makefile-libostree.am
- configure.ac
This leads to private symbols being exported.
Also specify the single C header, this relies on the gir_C_INCLUDES make variable,
which was introduced in gobject-introspection 1.51.5.
> build: Do not include private headers in the introspection

- .cci.jenkinsfile
The `skipMetal4k` and `skipMultipath` parameters no longer do anything. Instead use `--denylist-test` which is interpreted directly by the new `kola testiso` code.
This will run more tests than before. We'll likely cut down tests we consider redundant soon, but that should be transparent to this code.
> ci: update for new kolaTestIso()

- ci/build-check.sh
- ci/build.sh
- ci/libbuild.sh
ci: Turn off errors for deprecated-declarations
Having `-Werror` on in CI only by default has generally worked OK,
but I don't think it's worth trying to immediately scramble to port
when they deprecate APIs.
Motivated in this case by
```
src/libostree/ostree-fetcher-curl.c: In function 'initiate_next_curl_request':
src/libostree/ostree-fetcher-curl.c:876:3: error: 'CURLOPT_PROTOCOLS' is deprecated: since 7.85.0. Use CURLOPT_PROTOCOLS_STR [-Werror=deprecated-declarations]
876 |   rc = curl_easy_setopt (req->easy, CURLOPT_PROTOCOLS, (long)(CURLPROTO_HTTP | CURLPROTO_HTTPS | CURLPROTO_FILE));
|   ^~
```
---
ci: Drop workaround for fedora-release-container
I think this isn't necessary anymore, and is now actively broken
with f38.
---
> ci: two fixes

- src/libostree/ostree-fetcher-soup.c
This will help with debugging stalled requests in future, such as issue #605.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
Helps: #605
> lib/fetcher: Add some debugging messages to the libsoup request path

- Cargo.toml
Since a dependency `winnow` bumped to this in a recent update.
> rust: Bump MSRV to 1.64

- tests/inst/Cargo.toml
- tests/inst/src/treegen.rs
I've deprecated sh-inline; in the end I think it is better to minimize the amount of bash code we have.  xshell solves the core convenience problem of taking local variables and mapping them to command arguments.
A full port would be nontrivial; this just starts the ball rolling.
> tests/inst: Add xshell and use it in one place

- configure.ac
Release 2023.3
NOTE: As usual, some of these commits are actually for the Rust bindings,
which are versioned and released separately.
```
Colin Walters (14):
treegen: Require at least one mutation
ci: Turn off errors for deprecated-declarations
ci: Drop workaround for fedora-release-container
rust: Bump MSRV to 1.64
build-sys: Squash automake conditional warning re `.PHONY`
Add clang formatting infrastructure
lib: clang-format `ostree.h`
tree-wide: Fix various include ordering issues
lib: Fix one include
clang-format: Don't align backslashes
tree-wide: Run clang-format
ci: Validate clang-format
tests/inst: Add xshell and use it in one place
Dan Nicholson (3):
tests: Ensure real GIO backends aren't used
ci: Add test configuration with soup3 …
```
> Release 2023.3

- src/switchroot/ostree-prepare-root.c
Main motivation is prep for composefs in
https://github.com/ostreedev/ostree/pull/2640
In the interest of that, we add a `bool using_composefs` but it's currently always `false`.
> prepare-root: Move sysroot.tmp creation earlier

- src/libostree/ostree-sysroot-deploy.c
If the requested size is 0 then of course we have enough room 🙂
This avoids the fallocate call returning an EINVAL.
Closes: #2869
> lib/deploy: skip fallocate call when requested size is 0

- .github/workflows/tests.yml
- .gitmodules
- Makefile-libostree.am
- Makefile-switchroot.am
- Makefile.am
- autogen.sh
- configure.ac
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-composefs.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-verity.c
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- src/libotutil/ot-keyfile-utils.c
- src/libotutil/ot-keyfile-utils.h
- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root.c
- src/switchroot/ostree-remount.c
- src/switchroot/ostree-system-generator.c
This is some work in progress for supporting composefs in ostree.
The initial version just supports checking out a commit to a composefs image.
> Add initial composefs integration

- src/libostree/ostree-fetcher-util.h
In an installation environment (like a live ISO) we may not have significant space outside of the target installation repository.
There's no reason not to always open a linkable tempfile.  In the future we should fix the pull path to verify the checksum and then just directly link in the object instead of copying.
Closes: https://github.com/ostreedev/ostree/issues/2571
> fetcher: Always open tmpfiles in repo location

- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root.c
- src/switchroot/ostree-system-generator.c
Some kernel images are delivered in a signed kernel + cmdline + initramfs + dtb blob. When this is added to the commit server side, only after this do you know what the cmdline is, this creates a recursion issue. To avoid this, in the case where we have ostree=aboot karg set, create a symlink after deploy to the correct ostree target in the rootfs, as the cmdline can't be malleable and secured client-side at the same time.
> Add ostree=aboot for signed Android Boot Images

- src/libostree/ostree-repo-composefs.c
- src/libostree/ostree-sysroot-deploy.c
- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root.c
Currently we generate a signature for the actual composefs image, and
then we apply that when we enable fsverity on the composefs
image. However, there are some issues with this.
First of all, such a signed fs-verity image file can only be read if
the corresponding puiblic keyring is loaded into the fs-verity
keyring. In a typical secure setup we will have a per-commit key that
is loaded from the initrd. Additionally, the keyring is often sealed
to avoid loading more keys later.
This means you can only ever mount (or even look at) composefs images
from the current boot. While this is not a huge issue it is something
of a pain for example when debugging things.
Secondly, and more problematic, during a deploy we can't enable
fs-verity on the newly created composefs file, because and at that …
> composefs: Change how we do signatures

- src/libostree/ostree-core.h
- tests/test-basic-c.c
- tests/test-pull-large-metadata.sh
Flathub has hit the 10MB limit in 2022, and we had to drop some CPU architectures from the main summary to subsummaries, effectively cutting off users running too old Flatpak version. Despite that, the main summary containing only x86_64 is already at 7MB. As this is eventually going to happen to subsummaries as well, preemptively bump the limit 12 times.
It takes between 2 and 3 years for a change like this to roll out across Linux distibutions so the best time for this was yesterday.
fixes #2715
> Increase the metadata size limit to 128MB

- tests/test-concurrency.py
I think there's never been a real race condition here.  Instead the problem is:
- We have a timeout on the lock, after which we error out (30s)
- This test actually *lowers* the timeout
Looking through the failures for test-concurrency what I see is
`error: Locking repo exclusive failed: Resource temporarily unavailable` which is us hitting the timeout.
Hardcoded timeouts are just going to be subject to race conditions. I understand not wanting to block forever in some cases, but any arbitrary timeout is just going to get hit in real world conditions too.
Anyways for now, stop shooting ourselves in the foot and at least keep the timeout at the default.
Closes: https://github.com/ostreedev/ostree/issues/2038
> test-concurrency: Don't lower timeout

- src/libostree/ostree-repo-pull.c
I got a bug report with the bare error
```
error: Invalid checksum of length 0 expected 32
```
And I'm pretty sure it's from here.  Add error prefixing so we know exactly which metadata object was corrupt.
> pull: Add error prefixing for corrupt checksums

- configure.ac
was added this symbol comes from libgpg-error however, therefore its needed to add -lgpg-error to cmdline to resolve this symbol especially with gold and lld linker. Fixes
aarch64-yoe-linux-ld.lld: error: undefined reference due to --no-allow-shlib-undefined: gpg_strerror_r
>>> referenced by ./.libs/libostree-1.so
> fix build with lld linker

- src/libostree/ostree-core.c
- src/libostree/ostree-repo-pull.c
I've got more debug information in the error case that motivated https://github.com/ostreedev/ostree/pull/2884/commits/bae4347abeaa2a66d213758f790058f42cb71fd1 "pull: Add error prefixing for corrupt checksums"
where the sole error is
`error: Invalid checksum of length 0 expected 32`
This must be coming from the pull code in the case where we've already fetched the commit object.
- Add some error prefixing here in the core commit validation code
- Ensure that we do the validation immediately after loading, including of the parent commit reference where I think this error must be coming from
- Then the pull code can just safely call `ostree_commit_get_parent` which already does the hex conversion etc.
> Add more error prefixing when parsing commit objects

- src/libostree/ostree-fetcher-curl.c
Currently, trying to disable HTTP2 with `ostree config get` doesn't work as HTTP2 is actually used anyway (see https://gitlab.apertis.org/infrastructure/apertis-issues/-/issues/349 for the context).
The current logic to select the HTTP version to be use relies on the fact that curl don't use by default HTTP2. This assumption seems wrong with recent versions of curl. To fix this option, this PR adds a specific check if HTTP2 is disabled and explicitely switch to HTTP1.1 in this case.
> ostree-fetcher-curl: explicitly use HTTP1.1 when HTTP2 is disabled

- docs/composefs.md
- man/ostree.repo-config.xml
Let's describe the state of things at a high level, independent of the tracking issue which has a lot more detail (and hence noise).
This document keeps things at a high level and describes how to enable things today.
> composefs: Add some basic docs

- src/libostree/ostree-repo-composefs.c
The interaction of `iter_loop` and autofree is way too subtle; I happened to be reading this code and noticed we did the NULL reset in one path but not another.
The real fix is Rust...
> composefs: Avoid double unref

- ci/prow/Dockerfile
- ci/prow/fcos-e2e.sh
- tests/inst/src/composefs.rs
- tests/inst/src/insttestmain.rs
tests: Add a sanity check for composefs
Prep for adding some coverage of this flow when booting with
composefs.
---
ci: Sync prow config with rpm-ostree, enable composefs there
I want to gain testing over the composefs path; but without
yet changing the main Jenkins build.  Because we have duplicate/overlapping
CI systems, we can take advantage of this by testing the composefs
flow via Prow.
Sync the Prow build scripts with what's in coreos/rpm-ostree
right now.
Then let's test the composefs flow a bit more e2e there.
---
> ci: Add some composefs testing

- src/libostree/ostree-sysroot-deploy.c
Not clear why this was __off_t which is the sole appearance in the code base, but it breaks musl builds.
> lib/deploy: Use off_t not __off_t

- src/switchroot/ostree-prepare-root.c
This fixes a regression from the latest composefs submodule update in 1582edd1d4a6b26874d3897de8a5586f979a0715. In composefs commit 7560a4fd388481f479c0b3fc2e6d20c6321d9b74 the struct field was changed from the generic `expected_digest` with the thought that there may be other signatures or digests in the future.
> prepare-root: Adjust to composefs mount struct changes

- src/libostree/ostree-fetcher-util.h
This reverts commit f7f6f87c513c9f35bc24f35e909779c19cb49d3a.
This seems to have broken flatpak, so we'll revert and then investigate.
Closes: https://github.com/ostreedev/ostree/issues/2900
> Revert "fetcher: Always open tmpfiles in repo location"

- src/libostree/ostree-bootloader-aboot.c
aboot-deploy must know where the next root filesystem to boot is to set up a symlink /ostree/root.a or /ostree/root.b , this location is in the ostree= part of these passed in options.
> bootloader: Pass "options" to aboot bootloader backend

- .github/workflows/tests.yml
- Makefile-switchroot.am
> ci: Add "it compiles" coverage for --with-static-compiler

- ci/prow/Dockerfile
Our `install` target doesn't depend on `all` unlike the rpm-ostree version; not doing so is arguably better, so let's explicitly build before installing.
> ci/prow: Build tests before trying to install

- tests/test-composefs.sh
I am not sure why this is failing on older Debian systems, but I'm wildly guessing that something being done in `libtest.sh` is setting up automake in a way that we need.  This is done in other tests.
> tests: Source libtest before exiting

- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root.c
- src/switchroot/ostree-system-generator.c
Commit aa72caffb540114a0e8635ab2990b9c8b0b8f9db
regressed the `ostree-system-generator` on non-ostree systems. If there's no `ostree=` karg, we need to just exit 0.
Closes: https://github.com/ostreedev/ostree/issues/2909
Fixes: aa72caffb540114a0e8635ab2990b9c8b0b8f9db
> Fix return value of generator on non-ostree systems

- Makefile-switchroot.am
- src/switchroot/ostree-prepare-root-static.c
- src/switchroot/ostree-prepare-root.c
Separate prepare-root static path
We should have done this a long time ago.  We don't have any test
coverage for the no-initramfs path, and I think it's not long
term supportable as we want to add more features like composefs.
Particularly now that there's good support for embedding an
initramfs in a kernel image, I see little value in a path for
having custom static linking for this prepare root flow.
That said, we will continue to make a best-effort "it compiles"
attempt to support it.
Fork the "pid 1" prepare root code into a new
`ostree-prepare-root-static.c` file, and drop the runtime conditionals.
We can drop the composefs logic from `-static.c` which ends up
keeping that file much smaller.
A further next step here will be to actually fold the
`prepare-root.c` logic into the main …
> Separate prepare-root static path + link to glib

- Makefile-man.am
- Makefile-ostree.am
- Makefile-tests.am
- configure.ac
- src/ostree/main.c
- tests/libtest.sh
See https://github.com/ostreedev/ostree/issues/1593
Basically this makes it easier for people packaging, as the trivial-httpd
is only for tests, and this way the binary will live with the tests.
Also at this point nothing should depend on `ostree trivial-httpd`.
> Drop "ostree trivial-httpd" CLI, move to tests directory

- tests/inst/src/destructive.rs
- tests/inst/src/insttestmain.rs
- tests/inst/src/repobin.rs
- tests/inst/src/test.rs
tests/transactionality: Port a bit to xshell
This will give us more useful error messages which should
help debug a flake.
---
tests: Drop unused alias
---
tests: Enable mtime test
I think this just accidentally was never enabled.
While looking at the code, add a sleep here to be resilient to
filesystems with only second mtime granularity.
---
> tests/inst: A few small patches

- src/libostree/ostree-fetcher-curl.c
- src/libostree/ostree-fetcher-soup.c
- src/libostree/ostree-fetcher-soup3.c
- src/libostree/ostree-fetcher-util.h
- src/libostree/ostree-fetcher.h
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
This reverts commit 4e61e6f7d0d6aebd6abcdc455ec53164afe39e8d and re-instates the fix for ensuring that we download temporary files into the repository location.
However in order to ensure we don't re-introduce
https://github.com/ostreedev/ostree/issues/2900
we detect the case where we're writing to a FUSE mount and keep the prior behavior.
I've verified that this works with flatpak.
Note a downside of this is the change needs to be triplicated across the 3 http backends.
This then again
Closes: https://github.com/ostreedev/ostree/issues/2571
> fetcher: Always open tmpfiles in repo (except on FUSE)

- .github/workflows/tests.yml
- Makefile-otutil.am
- configure.ac
- src/libostree/ostree-sign-ed25519.c
- src/libostree/ostree-sign.c
- src/ostree/ot-builtin-sign.c
- src/ostree/ot-builtin-static-delta.c
This adds an openssl-based implementation to ostree-sign-ed25519.c which is used if libsodium was not manually configured.
The target usedcase for this is: https://github.com/ostreedev/ostree/pull/2921
> Implement ed255519 using openssl too

- src/libostree/ostree-repo-composefs.c
- src/libostree/ostree-sysroot-deploy.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
Add an internal constant for the composefs image name
Just a minor cleanup.
---
prepare-root: Use otutil and g_print
Now that we link to libotutil (and glib) we don't need separate
handling for conditionalizing on the presence of systemd.
Further, there's no value in `sd_journal_send(MESSAGE=)` over
just printing to stdout.
---
prepare-root: Drop unused verity flag querying
This logic got pushed down into libcomposefs.
---
> prepare-root: A few cleanups

- src/switchroot/ostree-mount-util.h
If the karg wasn't present, we'd do a NULL deref which is undefined behavior.
> mount: Fix gcc -fanalyzer warning for parsing androidboot.slot_suffix

- Makefile-switchroot.am
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
- src/switchroot/ostree-remount.c
- tests/inst/src/composefs.rs
prepare-root: Use constant for ed25519 signature
Minor cleanup.
---
prepare-root: Add metadata for composefs to `/run/ostree-booted`
Particularly for the signature case, having this metadata
acts as a reliable "proof of execution" of the signature verification
code (as opposed to parsing a log file or so).
Besides that, this is also just a stronger check for "we're using
composefs" instead of checking for "overlayfs on /".
---
remount: Don't overwrite /run/ostree-booted
Since it should always be written in the initramfs.
---
remount: Use new metadata in `/run/ostree-booted` for composefs
Since we now have a generalized more structured way of serializing
state in the initramfs instead of "stamp files", use it for
passing the composefs state.
---
Use /run/ostree-booted metadata for …
> More prepare-root cleanups

- .github/workflows/tests.yml
- ci/prow/Dockerfile
- configure.ac
There's no additional dependencies, and it's a small amount of new code.
The riskiest thing is the changes to ostree-prepare-root, but I believe that things are in a good state now there.
Again, this just enables it at *build time* - it's still off at runtime by default.
> build-sys: Enable composefs at *build time* by default

- src/libostree/ostree-sysroot.c
This came up in https://issues.redhat.com/browse/OCPBUGS-15955 and I'm 90% sure it's this readlink failing, but let's make it extra clear.
> sysroot: Add some error prefixing for bootversion

- src/switchroot/ostree-prepare-root.c
I think this was only ever used in the "static pid1" path which is now split out into a separate file.
We always expect that e.g. systemd does the switchroot in the initramfs, so drop this dead code.
> prepare-root: Drop dead `pivot_root` code

- Makefile-man.am
- man/index.xml
- man/ostree-prepare-root.xml
Add an overdue man page that describes this.  Prep for also documenting composefs things here.
> man: Add ostree-prepare-root

- man/ostree-commit.xml
- src/ostree/ot-builtin-commit.c
- tests/test-signed-pull.sh
Passing the private key via a direct command line argument is just a bad idea because it's highly likely to get logged or appear in `ps`.
Spotted in review of work for composefs signatures.
> commit: Add `--sign-from-file`

- src/switchroot/ostree-mount-util.h
Given the kernel argument androidboot.slot_suffix= is required in Android AB updates [1] there is no need to check for ostree= or ostree=aboot at all in the aboot case. This also ensures if the dependancy on ostree= is removed, the android-boot technique will work regardless.
[1]: https://source.android.com/docs/core/ota/ab/ab_implement
> android-boot: Remove dependency on ostree= karg, use androidboot.slot_suffix=

- src/switchroot/ostree-mount-util.h
Most of this was used for the old composefs signature model.  We now reuse the core signature code and link to glib, so we don't need reimplementations of hex strings and reading files.
> prepare-root: Drop more dead code

- configure.ac
As I (and others) will be backporting the fix in
https://github.com/ostreedev/ostree/pull/2874/commits/de6fddc6adee09a93901243dc7074090828a1912 pretty far, I want a way for sysadmins and OS builders to be able to reliably see when their version of ostree has this fix (Because comparing version numbers isn't portable).
> Add an always-on `inode64` feature

- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root-static.c
- src/switchroot/ostree-prepare-root.c
- src/switchroot/ostree-system-generator.c
Now that we use androidboot.slot_suffix karg to determine whether we
boot into /ostree/root.a or /ostree/root.b, we can use ostree= karg
simply for parsing the stateroot, although we will still boot into
what's pointed to by /ostree/root.a or /ostree/root.b.
> bootloader: fold all Android Bootloader specific logic into prepare-root

- Makefile-libostree.am
- src/libostree/ostree-kernel-args-private.h
- src/libostree/ostree-kernel-args.c
- src/libostree/ostree-kernel-args.h
- tests/test-kargs.c
External users can't call `_` prefixed APIs, so move them
to a `-private.h`.
---
> kernel-args: Move private functions out of public header

- src/libostree/ostree-sysroot-deploy.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
- tests/inst/src/composefs.rs
I just noticed that this was another constant string duplicated between prepare-root.c and libostree-1.so, and I went to make it a common `#define` in libotcore.la.
But then I thought "it's ugly to have this directory mixed into the deployment namespace" because in some theoretical world it could also be in the ostree commit, which would cause weird behavior.
I think this is transient state that is better in `/run`, so move it there.
> composefs: Use lowerdir in /run

- src/libostree/ostree-repo-pull.c
- src/libostree/ostree-repo.c
Coverity warns when we're checking the return value in most-but-not-all instances.  The code is correct in these instances; we're initializing the values to defaults.  So add a `(void)` cast like we are doing in many other places.
> tree-wide: Consistently `(void)g_variant_lookup()`

- man/ostree-prepare-root.xml
- src/boot/dracut/module-setup.sh
- src/switchroot/ostree-prepare-root.c
prepare-root: Introduce `ostree/prepare-root.conf`
Using the repository configuration for configuration of this
program was always a bit hacky.
But actually with composefs, we really must validate
the target root *before* we parse anything in it.
Let's add a config file for `ostree-prepare-root` that can live
in the initramfs, which will already have been verified.
In the future we'll also add configuration for composefs here.
We expect OS builders to drop this in `/usr/lib/ostree/prepare-root.conf`,
but system local configuration can live in `/etc`.
---
prepare-root: Default sysroot.readonly=true if composefs
Not because it's logically required or anything, but because
it's just a good idea.
---
prepare-root: Don't parse target root when composefs enabled
We shouldn't load anything from …
> prepare-root: Introduce ostree/prepare-root.conf && sysroot.readonly improvements

- src/libostree/ostree-core.c
- src/libotutil/ot-checksum-utils.c
- src/libotutil/ot-variant-utils.c
- src/libotutil/ot-variant-utils.h
- src/switchroot/ostree-prepare-root.c
core, switchroot: Harden a bit against `g_variant_get_data() == NULL`
I'm not totally sure this is the cause of
https://bugzilla.redhat.com/show_bug.cgi?id=2217401
but analyzing the code a bit it seems the most likely.
---
checksum-utils: Add an assertion that `buf != NULL`
Another hardening against https://bugzilla.redhat.com/show_bug.cgi?id=2217401
---
> Harden gvariant get data

- src/libostree/ostree-sysroot-deploy.c
This will help us debug bugs like https://issues.redhat.com/browse/OCPBUGS-15917 in the future.
> deploy: Be way more verbose about what we're doing

- tests/inst/src/destructive.rs
Let's verify that things work with that off, as they should.
Previously:
https://github.com/ostreedev/ostree/pull/2519/commits/cb731294837736e957ee595ce11ab115277dbb36 "deploy: Add a 5s max timeout on global filesystem sync()"
But we may still have problems even with that, see https://issues.redhat.com/browse/OCPBUGS-15917
where it might be that even a thread doesn't work because we're locked in the kernel.
> tests/destructive: Turn off global sync()

- src/libostree/ostree-repo-composefs.c
This fixes a warning from newer glib that we're now seeing in the Debian testing CI runs.
> composefs: Only call `_get_symlink_target()` on symlinks

- src/ostree/ot-admin-builtin-os-init.c
- tests/inst/src/insttestmain.rs
- tests/inst/src/sysroot.rs
Today on anything using readonly sysroot `os-init` fails, because we don't create a mount namespace if the `UNLOCKED` flag is specified because we assume it's a readonly operation.
Since technically this is a mutation, let's just lock the sysroot and use the tested path.
> os-init: Create a mount namespace

- Makefile-tests.am
- src/libostree/ostree-sysroot-deploy.c
- tests/test-admin-deploy-emptyetc.sh
In preparation for support for a transient `/etc`: https://github.com/ostreedev/ostree/issues/2868
particularly in combination with composefs.
Basically it's just much more elegant if we can directly mount an overlayfs on the *empty* `etc` directory, using `usr/etc` as the lower.
In the composefs case, we'd have to mount the composefs overlayfs itself writable (and call `mkdir`) *just* so we can make that empty `etc` directory which is ugly.
> deploy: Support an empty `/etc` and populated `/usr/etc`

- Makefile-man.am
- Makefile-ostree.am
- man/ostree-admin-set-default.xml
- src/ostree/ot-admin-builtin-set-default.c
- src/ostree/ot-admin-builtins.h
- src/ostree/ot-builtin-admin.c
- tests/admin-test.sh
A core underlying primitive in the C library is the ability to arbitrarily reorder bootloader entries.
Let's expose the basic functionality here with the ability to pick an arbitrarily deployment for the next boot.
Closes: https://github.com/ostreedev/ostree/issues/2965
> Add `admin set-default`

- docs/composefs.md
- man/ostree-prepare-root.xml
- src/boot/dracut/module-setup.sh
- src/switchroot/ostree-prepare-root.c
This drops the `ot-composefs` kernel commandline in favour of a `[composefs]` section in the `prepare-rootfs.conf` file.
You can set `composefs.enabled` to `yes`, `no` or `maybe`, with `maybe` being the default.
You can also set `composefs.keyfile` to point to an ed25519 key, which the commit must be signed with, or boot fails.
NOTE: This drop the option to define a digest in the commandline. However, that was currently unused (i.e. ComposefsConfig.expected_digest was never read).
Additionally it very hard to actually store the composefs digest in the initrd, as the initrd is typically part of the commit and thus the composefs. It may be possible to handle this, but lets add it back when we know exactly how that will work.
> Read composefs configuration from initrd instead of commandline

- README.md
While I resisted taking the next step in binding ourselves more to GH with discussions...it's way, way better than answering questions out of band in private (also proprietary) chats.
We haven't been successful in using the GNOME discussion forums.
> README.md: Drop dead mailing list, link to GH discussions

- src/libostree/ostree-impl-system-generator.c
- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root-static.c
- src/switchroot/ostree-prepare-root.c
Change the helper function to parse an existing cmdline instead of potentially reading `/proc/cmdline` multiple times.
> switchroot,generator: Only read /proc/cmdline once

- src/libostree/ostree-sysroot-deploy.c
We saw a bare
`Txn Rebase on <osname> failed: Failed to find kernel in /usr/lib/modules, /usr/lib/ostree-boot or /boot` which isn't bad, but it'd be better to be a bit more specific.
> deploy: Add some error prefixing

- man/ostree.repo-config.xml
- src/libostree/ostree-repo.c
And update the doc text to talk about having a timeout at all by default being a mistake.
Timeouts are really best handled at a higher level; if two processes are contending for the ostree lock and one is actually frozen, resolving this is something an admin may want to handle and introspect/debug instead of having the waiter error out.
Most people using ostree are doing it in a way in which they have higher level timeouts (e.g. on a container pod).
> repo: Bump lock timeout to 5 minutes

- Makefile-man.am
- man/ostree-admin-deploy.xml
- man/ostree-admin-stateroot-init.xml
- src/ostree/ot-admin-builtin-deploy.c
- src/ostree/ot-admin-builtin-os-init.c
- src/ostree/ot-builtin-admin.c
- tests/admin-test.sh
- tests/libtest.sh
Add `ostree admin stateroot-init` as alias for `os-init`
To further help deprecate the confusing "osname" terminology.
---
admin-deploy: Add `--stateroot` as alias for `--os`
To further help deprecate the confusing "osname" terminology.
---
> Two s/osname/stateroot/ patches

- src/libostree/ostree-lzma-compressor.c
- src/ostree/ot-builtin-checkout.c
lzma: Port to C99 style
Just keeping up momentum.
---
checkout: Port to C99 style
Just keeping up momentum.
---
> Misc c99 style 2

- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root.c
Sometimes android bootloaders boot in a nonab way:
https://source.android.com/docs/core/ota/nonab
In this case, "androidboot." kargs are present but not "androidboot.slot_suffix" specifically.
In this case, rather than getting stuck in a partially booted environment, boot system slot a.
> prepare-root: On a non-A/B androidboot system, boot system slot a

- configure.ac
This should fix the build with Google OSS-fuzz which currently uses an old Ubuntu.
> build-sys: Disable composefs on too-old Linux headers

- tests/inst/Cargo.toml
- tests/inst/src/destructive.rs
- tests/inst/src/sysroot.rs
> tests/inst: Update to latest ostree-ext

- Makefile-otcore.am
- src/libostree/ostree-impl-system-generator.c
- src/libotcore/otcore-prepare-root.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
- tests/test-otcore.c
Add long overdue unit testing coverage for this, which at least slightly closes out the android boot CI gap.
Actually, this *copies* the karg parsing code into otcore because it now uses glib, which we're not yet using in the static prepare-root.  It's pretty tempting to drop support for the static prepare root entirely.  But for now we'll live with some code duplication.
> Move prepare-root karg helpers into otcore, add unit tests

- src/switchroot/ostree-prepare-root.c
If composefs is configured as "maybe", we should continue even if composefs support is not built in.
> prepare-root: If composefs is configured as "maybe" don't fail

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/inst/src/destructive.rs
I've verified that this fixes compatibility with GRUB, which parses the filename:
https://github.com/ostreedev/ostree/issues/2961
However, out of a large degree of conservatism I've made this an opt-in behavior for now.
My plan is to test it out in the FCOS development streams first.
> deploy: Add bootloader-naming-2 opt-in

- .github/workflows/tests.yml
- configure.ac
ci: Add c9s build
Since it's an active target of this project.
---
build-sys: Look for both linux/mount.h and sys/mount.h
Since that's what composefs uses.
---
> C9s CI && composefs build detection fix

- configure.ac
The ordering of the includes apparently matters...and I didn't actually check that the previous change enables composefs on c9s. But I did now.  For reals.
While we have the patient open, I switched to `AC_LANG_PROGRAM` because I originally thought the bug had something to do with that. As far as I understand, more cleanly separating the includes from the injected body text is a useful thing in `AC_LANG_PROGRAM`.
> build-sys: Really fix composefs check

- src/ostree/ot-builtin-export.c
- src/ostree/ot-builtin-log.c
- src/ostree/ot-remote-builtin-show-url.c
cmd/export: Port to C99 style
Just keeping up momentum.
---
cmd/export: Fold libarchive error handling
The helper function here doesn't quite carry its weight; this
brings us inline with having single line (no braces) error
return paths.
---
cmd/log: Port to C99 style
Just keeping up momentum.
---
cmd/show-remote-url: Port to C99 style
Just keeping up momentum.
---
> Misc c99 style 5

- Makefile-tests.am
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-sign-ed25519.c
- src/libotcore/otcore-prepare-root.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
- tests/test-otcore.c
switchroot: Lower config parser to otcore, add unit tests
Part of the continuation of unit testing coverage.
---
commit: Drop dead code
Coverity points out that since we're now *always* initializing
metadata, the `create_empty_gvariant_dict()` is unreachable.
---
sign/ed25519: Fix two memory leaks
Spotted by coverity.
---
switchroot: Use g_new/g_free consistently
Coverity complains about this, even though they're the same thing.
---
> 2023.6 coverity minor fixes

- src/switchroot/ostree-prepare-root.c
prepare-root: Drop redundant print about signature/digest
We print if we're doing a signature+digest verification; its absence is
sufficient in the other case.  The goal here is to avoid polluting
the logs when signatures are not enabled.
---
prepare-root: Init composefs options earlier
Prep for a later patch.
---
prepare-root: Fold together composefs signature cases
Now that we don't support digest-but-not-signature verification
for composefs, the logic here was unnecessarily complicated.
With a prior prep patch that moved the composefs option
initialization up, we can just have everything related to signature
verification in a single conditonal.
---
composefs: Hard error except on ENOENT even in "optional" case
Since we enabled composefs at build time, the default (non-composefs)
case …
> Refactor composefs warnings

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-finder-mount.c
- src/libostree/ostree-repo-pull.c
lib/repo-finder: Squash memory leak
We want to free this value on each iteration; it's moved below
if the value is used.
---
pull: Add assertions to quiet clang-analyzer
It's warning the value can be NULL, but I don't think that's true.
I believe we're just hitting analysis limit (the path length is 119).
---
commit: Quiet clang-analyzer warning
This is just another instance of the "conditionally owned"
pattern.
---
pull: Quiet clang-analyzer warning
Just used for side-effects.
---
> More analyzer fixes 2

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-static-delta-compilation.c
- src/libostree/ostree-repo.c
- src/ostree/ot-builtin-commit.c
lib/delta: Remove dead code
Found by clang-analyzer.
---
lib/commit: Quiet clang-analyzer warning
Another conditional ownership.
---
commit: Quiet clang-analyzer warning
Another conditional ownership.
---
commit: Quiet clang-analyzer warning
Another conditional ownership.
---
repo: Quiet clang-analyzer warning
Another conditional ownership.
---
> More analyzer fixes 3

- src/libostree/ostree-mutable-tree.c
The warning here was about a use-after-free which is serious, but I don't think it was reachable in practice, because we'd only enter the second conditional if `contents_checksum != self->contents_checksum`, yet we made them the same thing here.
Nevertheless, refactor the code to do a direct return in this case because that's basically what happened before, and doing so is a lot clearer.
> mutable-tree: Quiet clang-analyzer warning

- src/libostree/ostree-repo-commit.c
- src/libotutil/ot-keyfile-utils.c
keyfile-utils: Quiet a clang-analyzer warning
It complains that we could leak memory if the return value
pointer isn't set.  That's actually a nonsensical case, there's
no reason to call this and ignore the return value.
So change things to require it be set, and also change the
`g_return_val_if_fail` to be hard assertions per our new policy.
---
commit: Quiet clang-analyzer warning
Another conditional ownership.
---
> Clang analyzer fixes 5

- src/libostree/ostree-sysroot-deploy.c
Our previous change here was not actually sufficient for the ceph case, because what (I think) is happening is that our other `syncfs()` invocation is getting blocked on some kernel mutexes that are used in `sync`, and that's causing the process to fully block.
We should not be dependent on a full filesystem `sync`, only on the sync of the sysroot and boot filesystems.
Anyone who *does* want this behavior could inject an override for `ostree-finalize-staged.service` that overrides `ExecStop` to add a run of `sync`.
> deploy: Remove global `sync` by default

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/kolainst/destructive/auto-prune.sh
I think we have enough testing for this, let's default it to on, and change the variable to allow opt-out in case it does introduce a regression.
> sysroot: Promote the "early prune" behavior to default

- .github/workflows/rust.yml
- Cargo.toml
- rust-bindings/src/lib.rs
- rust-bindings/src/repo.rs
- rust-bindings/tests/repo/mod.rs
- rust-bindings/tests/util/mod.rs
Since it bumped semver (when I didn't expect it to; xref https://github.com/bytecodealliance/cap-std/commit/963eebf3ab52b04a2e8b9ba88ce6308bbed5cbd0#r121651362
It's not load-bearing enough here to matter versus just passing an untyped file descriptor.
This mainly means that it will be the `glib` ecosystem which forces transitive semver bumps for us, not both.
> Drop cap-std from our public APIs

- Cargo.toml
- rust-bindings/sys/Cargo.toml
Since we bumped the glib major.
> rust/sys: Also bump semver for this

- Cargo.toml
This greatly reduces the size.  TODO: switch to using `include`.
> rust: Drop composefs from crate

- .cci.jenkinsfile
- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull.c
- src/ostree/ot-builtin-pull-local.c
- tests/test-delta.sh
- tests/test-pull-localcache.sh
When we're fetching a commit via static delta, we already take care of
fetching the full commit, so there's no need to also scan it using the
regular object workflow.
Closes: #2053
> lib/pull: Don't scan commit objects we fetch via deltas

- Cargo.toml
This way we don't randomly pick up bits from the C library unintentionally as things change on that side.
I think the support for `!` in `include` may be relatively new and that's why the original author here chose to do things via `exclude`.  But using `include` with a few specific exclusions is just way better.
> rust: Switch to using `include`

- .gitmodules
gitlab.gnome.org is down right now, but it's been somewhat flaky in the past.  Our CI uptime becomes an *intersection* of all systems it depends on, and by cutting out gitlab.gnome.org we increase its reliability.
> gitmodules: Use github GNOME mirror

- src/boot/dracut/module-setup.sh
These kernel modules are required for composefs usage in the initramfs.
The composefs use-case as of today uses an overlayfs on top of a erofs.
> boot/dracut: Add erofs and overlayfs kernel modules

- tests/inst/src/composefs.rs
- tests/inst/src/test.rs
Ensure we have some automated test coverage for this.
> tests: Add an integration test for composefs signatures

- docs/authenticated-repos.md
Document options for accessing repositories that require authentication.
> docs: Add authenticated-repos.md

- src/libostree/ostree-bootloader-zipl.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
This will allow us to drop code like
https://github.com/coreos/coreos-assembler/blob/87fc693c115eae1e7ff0e1621ce26c9167af6e84/src/create_disk.sh#L503 which is really just unnecessary since there aren't any other bootloaders we care about on this architecture.
> repo: Default bootloader to zipl on s390x

- .cci.jenkinsfile
This reverts commit 2fe88f80fae83e206f811003a072c73ceebcea59.
This shouldn't be necessary now with the workaround built in cosa:
https://github.com/coreos/coreos-assembler/pull/3625
> Revert "ci: Run cosa unprivileged"

- src/libostree/ostree-repo-libarchive.c
- tests/archive-test.sh
- tests/libtest.sh
- tests/test-composefs.sh
- tests/test-export.sh
For ostree_repo_export_tree_to_archive(), and 'ostree export', when the exported tree contains multiple files with the same checksum, write an archive with hard links.
Without this, importing a tree, then exporting it again breaks hardlinks.
As an example of savings: this reduces the (compressed) size of the Fedora Flatpak Runtime image from 1345MiB to 712MiB.
Resolves: #2925
As noted in #2925, if this is considered insufficiently compatible, it could be put behind an option. If someone is untarring an 'ostree export'  tarball and then using it read-write, then hardlinking coincidentally the same files (like all empty files) could be quite surprising. For typical usage of ostree, however, using hardlinks in the exported tar is less surprising.
There's a fair bit of memory usage during …
> When exporting, use hardlinks for duplicated files

- ci/build.sh
- ci/libbuild.sh
- ci/prow/fcos-e2e.sh
- tests/inst/src/composefs.rs
- tests/inst/src/insttestmain.rs
For some reason we're not picking this up in the Prow build, which breaks things because now rpm-ostree hard requires it.
Let's make this a fatal build time error for more clear debugging.
> ci: Ensure composefs is enabled on Fedora

- man/ostree-commit.xml
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo.h
- src/ostree/ot-builtin-commit.c
- tests/kolainst/destructive/itest-label-selinux.sh
This will be very useful for enabling a "transient /etc" option because we won't have to do hacks relabling in the initramfs, or forcing it on just for composefs.
> repo: Add an option to label /usr/etc as /etc

- Makefile-switchroot.am
- man/ostree-prepare-root.xml
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
- src/switchroot/ostree-remount.c
This is a new version of https://github.com/ostreedev/ostree/pull/2972
There was a lot of complexities, so this is essentially a clean restart. So, rather than reusing that PR I created a new one.
This PR does multiple things:
*  Adds a `etc.transient=true` option to `prepare-root.conf`, which causes /etc to be and overlayfs mount with a tmpfs-based upper.
* Relabels /usr/etc as if it was /etc in the generated composefs image, allowing the use of usr/etc as the lower for the above /etc overlayfs mount.
* Since we're changing the composefs image format anyway (due to the relabeling), we're copying the mkcomposefs change that inlines files at 64 bytes or smaller to avoid overhead.
The actual transient etc overlay mount details are quite complex due to selinux interactions between tmpfs, …
> Support transient /etc

- src/libostree/ostree-sysroot-deploy.c
- tests/admin-test.sh
Came up on an internal chat; previously we were only erroring out when trying to do the SELinux labeling for `/var` which was really misleading.
Add some other error prefixing while we have the patient open.
> deploy: Improve error message for nonexistent stateroot

- src/libostree/ostree-repo-composefs.c
To help debug https://github.com/coreos/rpm-ostree/issues/4649
> composefs: Add more error prefixing

- src/libostree/ostree-sysroot-deploy.c
- tests/kolainst/destructive/staged-deploy.sh
This closes the biggest foot-gun when doing e.g.
`rpm-ostree rebase` when zincati is running on a FCOS system.
Previously if zincati happened to have staged + locked a deployment, we'd keep around the lock which is definitely not what is desired.
> deploy: Remove lock when re-staging

- man/ostree-admin-deploy.xml
- src/ostree/ot-admin-builtin-deploy.c
- tests/test-admin-deploy-karg.sh
Fix https://github.com/ostreedev/ostree/pull/2612#issuecomment-1764412141
> karg-delete: support multiple times

- man/ostree-pull.xml
- src/libostree/ostree-fetcher-curl.c
- src/libostree/ostree-fetcher-soup.c
- src/libostree/ostree-fetcher-soup3.c
- src/libostree/ostree-fetcher.h
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-pull-private.h
- src/libostree/ostree-repo-pull.c
- src/ostree/ot-builtin-pull.c
This introduces the retry-all-network-errors option which
is enabled by default. This is a behavior change as now
ostree will retry on requests that fail except when
they fail with NOT_FOUND. It also introduces the options
low-speed-limit-bytes and low-speed-time-seconds these
map to CURL options only at the moment. Which have defaults
set following librepo:
https://github.com/rpm-software-management/librepo/blob/7c9af219abd49f8961542b7622fc82cfdaa572e3/librepo/handle.h#L90
https://github.com/rpm-software-management/librepo/blob/7c9af219abd49f8961542b7622fc82cfdaa572e3/librepo/handle.h#L96
Currently this changes only apply when using libcurl.
Closes: https://github.com/ostreedev/ostree/issues/2570
> ostree-fetcher-curl: handle non 404 errors as G_IO_ERROR_TIMED_OUT

- src/libostree/ostree-sysroot-deploy.c
I have a suspicion that the `semodule -N --refresh` we do here is involved in https://github.com/coreos/fedora-coreos-tracker/issues/1597. Let's log when we execute it and include its time.
While we're here, also log the time it takes to `syncfs()` and the fsfreeze/thaw cycling. It's logged in a structured journal entry, but that's less accessible than just having it in the journal message field.
> lib/deploy: Log SELinux policy refresh

- src/libostree/ostree-bootloader-zipl.c
Closes: https://github.com/ostreedev/ostree/issues/3084
Not the most elegant fix but should get the job done.
> bootloader/zipl: No-op if run as non-root

- src/libostree/ostree-bootloader-zipl.c
Starting with z/VM Version 7 Release 3.0, service level 2301 we can run Linux with Secure Boot enabled
> lib/bootloader-zipl: Check for Secure Boot before zipl

- src/ostree/ot-admin-builtin-undeploy.c
- tests/admin-test.sh
`atoi` doesn't offer any error checking.
Closes: https://github.com/ostreedev/ostree/issues/3088
> undeploy: Parse integer more properly

- rust-bindings/src/deployment.rs
- rust-bindings/src/lib.rs
Easy to do here, super annoying in C.
> rust: Add a `stateroot()` alias in the Rust bindings

- Makefile-libostree.am
- Makefile-man.am
- Makefile-ostree.am
- apidoc/ostree-sections.txt
- man/index.xml
- man/ostree-admin-post-copy.xml
- man/ostree-admin.xml
- src/libostree/libostree-devel.sym
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo-verity.c
- src/libostree/ostree-sysroot-cleanup.c
- src/libostree/ostree-sysroot.h
- src/ostree/ot-admin-builtin-post-copy.c
- src/ostree/ot-admin-builtins.h
- src/ostree/ot-builtin-admin.c
This command will apply fs-verity on all objects that need it and needs to be called when an ostree deployment has been copied on a file-by-file basis, which would loose information such as fs-verity.
This is needed by osbuild which works by creating the final image in a rootfs, and then separately copying that rootfs file-by-file to a loopback mounted filesystem image.
This comes from https://github.com/osbuild/osbuild/pull/1343
> Add `ostree admin post-copy` command

- src/libostree/ostree-repo-verity.c
The code to enable fs-verity on an object file was failing with ENOENT for symlink objects.
> Fix admin post-copy handling of symlinks

- man/ostree-prepare-root.xml
- man/ostree.repo-config.xml
The explanation of `sysroot.readonly` is a little confusing - we say that "everything else is mounted read-only" but it's perhaps clearer to say `/sysroot` is mounted read-only.
Also note that read-only is the default with composefs.
Finally, document the option in ostree.repo-config even though it is now considered legacy - as of commit 22b8e4f9 (#2930) - it is still commonly seen in repo configs, so users will look to understand what it means.
> man: improve sysroot.readonly docs

- man/ostree-admin-deploy.xml
- man/ostree-admin-lock-finalization.xml
- tests/kolainst/destructive/finalization.sh
man: Two finalization fixes
From PR review.
---
tests: Add a dedicated finalization test
This one covers `admin lock-finalization --unlock`.
---
> Misc finalization

- src/libostree/ostree-sysroot-deploy.c
deploy: Use NULL terminated strv
This makes the code simpler and avoids the need
to keep the string array and length in sync.  Prep for
further callers.
---
sysroot/deploy: Drop unnecessary g_ptr_array_free
We can just reference the pdata, and autoptr the array.
---
> Deploy cleanup run

- src/boot/ostree-tmpfiles.conf
- src/libostree/ostree-sysroot-deploy.c
- tests/kolainst/destructive/var-tmpfiles.sh
This is a pattern we want to encourage.  It's honestly just way simpler than what rpm-ostree is doing today in auto-synthesizing individual tmpfiles.d snippets.
> tmpfiles: Copy `/usr/share/factory/var` to `/var`

- src/libostree/ostree-bootloader-zipl.c
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
sysroot: Expose deployment container executor internally
Prep for using this for zipl.
---
bootloader/zipl: Run in target deployment as container if needed
xref https://issues.redhat.com/browse/MGMT-16303
Basically the OCP Assisted installer has now grown code
to try to do OS updates offline post-install, and this means
we need to handle the case of running zipl from the target
root.
---
> bootloader/zipl: Run in target deployment as container if needed

- rust-bindings/src/sysroot.rs
For the same reason we have this method on `Repo`.
> sysroot: Add a method to borrow sysroot fd

- docs/adapting-existing.md
- docs/var.md
- man/ostree-prepare-root.xml
man: Document `root.transient`
This one warrants some explanation.
---
docs: Add `var.md`
This one overlaps a bit with some other sections...the docs
need a bigger rework, but this is better than we had before.
---
> Doc root transient

- README.md
This repo is the outcome of a PoC on how an existing debian-based distro could be adapted to be used with OSTree.
> Link to gardenlinux/ostree-image-builder in README

- src/libostree/ostree-sysroot-deploy.c
To aid debugging issues like https://github.com/coreos/fedora-coreos-tracker/issues/1637
If we're hitting this path where we think we have enough space, let's log what we calculated here to aid in diagnosing why we may later fail with ENOSPC.
> deploy: Log calculated needed space

- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root-static.c
- src/switchroot/ostree-prepare-root.c
If you don't have rw in the kernel cmdline or have ro in it, often you hit this issue. This is just to be really explicit about that in the error messages so people can check.
> switchroot: Be explicit about what could cause /sysroot to be ro

- src/libostree/ostree-bootloader-zipl.c
zipl: Use O_CLOEXEC
On general principle.
---
zipl: Fix error handling for read
The return value is not errno.
---
zipl: NUL terminate buffer we're searching
Found by a static analyzer.
---
zipl: Convert to a data input stream
This high level reader API avoids all the bugs that were
found in prevoius patches.
---
> zipl: A few fixes

- docs/composefs.md
Just thinking about trying to land this, I think some people may hit this one.
> docs/composefs: Add note about toplevel dirs

- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
So it's easier to link the two bits of code.
> switchroot: use shared constant for unlock --hotfix

- src/switchroot/ostree-prepare-root.c
There's a test case for `ostree admin unlock --hotfix` that runs in FCOS, not here; it breaks when enabling composefs.
The reason is because the composefs is mounted readonly, and we tried to remount it writable.  Instead of trying to remount the rootfs writable at this point forcibly, honor the *real* sysroot readonly state flag from the underlying FS before we mounted the composefs.
Note that in FCOS derivatives we always have the root mounted writable via `rw` on the kernel cmdline and this is the default general expectation now with ostree usage.
> prepare-root: Fix composefs + ostree admin unlock --hotfix compat

- src/libostree/ostree-sysroot-deploy.c
- src/libotutil/ot-fs-utils.c
- src/libotutil/ot-fs-utils.h
- tests/kolainst/destructive/auto-prune.sh
When we estimate how much space a new bootcsum dir will use, we
weren't accounting for the space overhead from files not using the
last filesystem block completely. This doesn't matter much if counting
a few files, but e.g. on FCOS aarch64, we include lots of small
devicetree blobs in the bootfs. That loss can add up to enough for the
`fallocate()` check to pass but copying still hitting `ENOSPC` later on.
I think a better fix here is to change approach entirely and instead
refactor `install_deployment_kernel()` so that we can call just the
copying bits of it as part of the early prune logic. We'll get a more
accurate assessment and it's not lost work since we won't need to
recopy later on. Also this would not require having to keep in sync the
estimator and the install bits.
That said, …
> lib/deploy: Round to block size in early prune space check

- src/ostree/ot-admin-builtin-status.c
The default `ostree admin status` tries to do signature verification, but doesn't error out if that fails.
However, an extremely longstanding bug here is that we passed the "osname" aka stateroot instead of the remote name.  This happens to work for e.g. Fedora Silverblue today, where they are the same.  It doesn't work on FCOS (remote = fedora, stateroot = fedora-coreos).
> status: Pass correct remote name when verifying

- src/ostree/ot-admin-builtin-status.c
If OSTREE_DISABLE_GPGME is not built in set remote to NULL.
The ostree_repo_signature_verify_commit_data path is irrelevant in the
no gpg case anyway. Having this set as NULL ensures an error gets
thrown early.
> status: Fix build without GPGME

- src/boot/ostree-boot-complete.service
systemd/ostree-boot-complete: Add `ConditionKernelCommandLine=ostree`
In practice we don't enable this unit except via our generator,
but let's do this on general principle.
---
systemd/ostree-boot-complete: Start earlier
Prep for changing this service to perform state computations
such as "is this boot the default, or did we get rolled back"
that can be used by higher level tools.
---
> systemd/ostree-boot-complete: Start earlier

- man/ostree-admin-status.xml
- src/ostree/ot-admin-builtin-status.c
Generally in ostree based systems you would expect to boot into deployment 0, in rollback conditions triggered by greenboot-related rollbacks this might not be the case. This is a tool to detect this.
> status: Introduce tool to quickly check if we are booted as default

- man/ostree-admin-status.xml
- src/ostree/ot-admin-builtin-status.c
This is a tool to check if we are booted as default or not, just a rename before it becomes widely used. We also shortened the '-h' output for this.
> status: Rename query-booted to is-default

- Makefile-boot.am
- Makefile-man.am
- Makefile-ostree.am
- man/ostree-state-overlay@.service.xml
- src/boot/ostree-state-overlay@.service
- src/ostree/ot-admin-builtin-state-overlay.c
- src/ostree/ot-admin-builtins.h
- src/ostree/ot-builtin-admin.c
- tests/kolainst/destructive/state-overlay.sh
In the OSTree model, executables go in `/usr`, state in `/var` and configuration in `/etc`. Software that lives in `/opt` however messes this up because it often mixes code *and* state, making it harder to manage.
More generally, it's sometimes useful to have the OSTree commit contain code under a certain path, but still allow that path to be writable by software and the sysadmin at runtime (`/usr/local` is another instance).
Add the concept of state overlays. A state overlay is an overlayfs mount whose upper directory, which contains unmanaged state, is carried forward on top of a lower directory, containing OSTree-managed files.
In the example of `/usr/local`, OSTree commits can ship content there, all while allowing users to e.g. add scripts in `/usr/local/bin` when booted into that …
> Add concept of state overlays

- docs/bootloaders.md
Android Bootloader is a standard of how Android devices should implement their bootloaders, we also use it in CentOS Automotive Stream Distribution for some ARM boards. Here is some documentation on how ostree works with this.
> doc: Add section about ostree and aboot

- configure.ac
There are two major new APIs around configuring mutability and persistence of the root filesystem.
First, OSTree gained support for a new `root.transient` flag that makes `/` an `overlayfs` that is persistent across reboots but *not* across upgrades.  This makes the system behave a bit more similarly to e.g. Docker and following tools such as podman and Kubernetes.  
* prepare-root: Add support for root.transient by @cgwalters in https://github.com/ostreedev/ostree/pull/3114
* Doc root transient by @cgwalters in https://github.com/ostreedev/ostree/pull/3117
There is a different approach in the (still classified as experimental) `ostree-state-overlay@.service` unit:
* Add concept of state overlays by @jlebon in https://github.com/ostreedev/ostree/pull/3120
This approach instead allows …
> Release 2024.1 

- src/libostree/ostree-sysroot-deploy.c
It's a followup of commit e6a560b40797324aa8b90e7100c6d50bff91f14d. We should also ignore sockets and fifos in the subdir of /etc.
> deploy: Ignore sockets, fifos in /etc/<subdir> during merge

- tests/test-composefs.sh
Otherwise, this test fails on Debian 12 (Linux 6.1) kernels if /var/tmp is a tmpfs. Some autobuilders put the entire build chroot on a tmpfs, to speed up builds.
> tests: Skip composefs test if /var/tmp does not support user xattrs

- src/libostree/ostree-impl-system-generator.c
Currently if run in a container image under systemd, we will incorrectly synthesize a `var.mount` unit even if `ostree-prepare-root` hasn't run.
The comment here said why we didn't do that before, but that's for the really legacy embedded-only "ostree-prepare-root-static" path, and even then I'm pretty sure it was wrong because the generator here only runs in the *real* root, and we should have `/run/ostree` at that point.
> generator: Exit if there's no `/run/ostree`

- man/ostree-admin-pin.xml
- src/ostree/ot-admin-builtin-pin.c
- src/ostree/ot-builtin-admin.c
Add new commands to pin the current, staged and previous deployment for
use in automation and scripting. Right now, it's difficult to pin the
current deployment without needing to look into the output of some other
tooling (like rpm-ostree) to get the index of each deployment. This
index also is not consistent - the current deployment could be 0 when
you first boot the system then 1 shortly after. This change makes it
easy to pin the current or future deployment.
Co-authored-by: Robert Sturla <robertsturla@outlook.com>
Signed-off-by: Eric Curtin <ecurtin@redhat.com>
> admin/pin: Add commands to pin booted, pending and rollbacks deployments

- configure.ac
- src/libostree/ostree-repo-composefs.c
This generates the new format for whiteout markers which was added in  6.8 (and which will be backported to 6.7). Without this whiteouts  will not work anymore.
This is a slight format change, but will only affect ostree commits that already were broken (i.e that had whiteouts), and since the composefs code is still marked experimental I think it is fine to do this without introducing another format version on the ostree side.
> composefs: Bump composefs max version to 1

- .github/workflows/bootc.yaml
- .github/workflows/tests.yml
- ci/Containerfile.c9s
- ci/libbuild.sh
This obsoletes the "just build" on c9s flow, and actually runs though a bootc install, which exercises more of things.
> ci: Add a bootc/c9s workflow

- src/boot/grub2/grub2-15_ostree
grub2-15_ostree: Graceful exit if /etc/default/grub doesn't exist
With the new bootupd installation path in Anaconda, the
`/etc/default/grub` config file is not written anymore as we are only
using BLS configs with new enough bootloaders.
We thus don't need to generate (duplicated) legacy boot entries.
We still need to keep this logic in place in Atomic Desktops
(Silverblue, etc.) until we've actually landed bootupd there and forced
a bootloader update for everybody.
See: https://github.com/fedora-silverblue/issue-tracker/issues/530
See: https://github.com/fedora-silverblue/issue-tracker/issues/120
See: https://fedoraproject.org/wiki/Changes/FedoraSilverblueBootupd
---
grub2-15_ostree: Fix whitespace
> grub2-15_ostree: Graceful exit if /etc/default/grub doesn't exist

- src/libostree/ostree-bootloader-syslinux.c
This backend always explicitly emitted a `/boot` - but if the global `sysroot.bootprefix` is enabled, then we can rely on the outer code doing it.
Luckily this was caught by the unit tests here failing when enabling `sysroot.bootprefix` by default.
> syslinux: Avoid double `/boot` if bootprefix is enabled

- src/libostree/ostree-impl-system-generator.c
- src/ostree/ot-admin-builtin-state-overlay.c
Not required for anything in particular, but it's good to use the right flags here anyway.
> admin/state-overlay: Require root and don't lock sysroot

- src/libostree/ostree-repo.c
- tests/test-admin-deploy-bootprefix.sh
I've been testing this in various places and not seen any fallout, so let's finally enable this by default and have the situation where `/boot` is on the root `/` filesystem work out of the box.
> Enable `sysroot.bootprefix` by default

- src/libostree/ostree-repo.c
- tests/test-admin-deploy-bootprefix.sh
This reverts commit 8627c8afa15fa0b2dc2dc261a217dd043a991a7d.
See discussion in https://github.com/ostreedev/ostree/pull/3156 ; we think this breaks s390x in some cases at least, and that warrants further investigation.
> Revert "Enable `sysroot.bootprefix` by default"

- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
When we added composefs, it broke the logic for detecting the booted
deployment which was previously a direct (device, inode) comparison.
So the code there started looking at `etc`.  However, that in
turns breaks with `etc.transient = true` enabled.
Fix all of this by tracking the real deployment directory's
(device,inode) that we found in `ostree-prepare-root`, and inject
it into the extensible metadata we have in `/run/ostree-booted`
which is designed exactly to pass state between the initramfs
and the real root.
---
> Track deployment root/inode from prepare root

- .github/workflows/bootc.yaml
- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-sepolicy.c
- src/libostree/ostree-sepolicy.h
Currently when writing data for selinux systems on a non-selinux system there will be no labels. This is because
`ostree_sepolicy_setfscreatecon()` just returns TRUE on non-selinux systems and xattr writing for `security.seliux` is filtered out.
This patches uses the suggestion of Colin Walters (thanks!) from https://github.com/ostreedev/ostree/issues/2804 and detects if the host has selinux enabled and if not just skips filtering the xattrs for selinux.
[draft as this will need a test (and validation of the basic approach by someone experienced) and I will need a hint how to best test this]
> libostree: write selinux xattr when on non-selinux systems

- Makefile-tests.am
- src/libostree/ostree-sysroot-deploy.c
- src/libotcore/otcore-prepare-root.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
- tests/admin-test.sh
- tests/test-admin-deploy-composefs.sh
lib: Move parsing of composefs config into otcore
So it can be shared with the deployment path.  Prep for dropping
`ex-integrity.composefs`.
---
prepare-root: Fix crash if no keys were found
Handle a NULL pointer.
---
switchroot: Move a define into library too
---
deploy: Honor prepare-root.conf at deploy time
I want to try to get away from the "repository global" configuration
in the repo config.
A major problem is that there's not an obvious way to configure
it as part of an ostree commit/container build - it needs
to be managed "out of band".
With this change, we parse the `usr/lib/ostree/prepare-root.conf`
in the deployment root, and if composefs is enabled there,
then we honor it.
We do still honor `ex-integrity.composefs` but that I think
we can schedule to remove.
---
> deploy: Honor prepare-root.conf at deploy time for composefs

- Makefile-tests.am
- configure.ac
- docs/var.md
- src/boot/ostree-tmpfiles.conf
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/kolainst/destructive/deployment-lint
- tests/test-admin-deploy-var.sh
We've long struggled with semantics for `/var`.  Our stance of "/var should start out empty and be managed by the OS" is a strict one, that pushes things closer to the original systemd upstream ideal of the "OS state is in /usr".
However...well, a few things.  First, we had some legacy bits here which were always populating the deployment `/var`.  I don't think we need that if systemd is in use, so detect if the tree has `usr/lib/tmpfiles.d`, and don't create that stuff at `ostree admin stateroot-init` time if so.
Building on that then, we have the stateroot `var` starting out actually empty.
When we do a deployment, if the stateroot `var` is empty, make a copy (reflink if possible of course) of the commit's `/var` into it.
This matches the semantics that Docker created with volumes, and …
> sysroot: Rework /var handling to act like Docker `VOLUME /var`

- configure.ac
This is a follow up to https://github.com/containers/composefs/pull/253.
> Expose MOUNT_ATTR_IDMAP detection result to C code

- src/switchroot/ostree-prepare-root.c
prepare-root: Add missing newline
This is ugly in the output.
---
prepare-root: Unify root.transient with composefs
First, I was totally wrong and composefs handles being passed
an upperdir itself, we don't need to stack overlayfs.
Next, there's really no reason to support `root.transient`
*without* a backing composefs.  The legacy ostree bind mount
and readonly `/usr` is just that - legacy.
Finally, we actually *must* do this to enable both composefs
and transient root, because the prepare-root flow assumes
that it just needs to `MS_MOVE` a *single* mount for the root,
not a stack.
---
>  prepare-root: Unify root.transient with composefs

- docs/CONTRIBUTING.md
- docs/README-historical.md
- docs/adapting-existing.md
- docs/atomic-rollbacks.md
- docs/atomic-upgrades.md
- docs/authenticated-repos.md
- docs/bootloaders.md
- docs/buildsystem-and-repos.md
- docs/composefs.md
- docs/contributing-tutorial.md
- docs/deployment.md
- docs/formats.md
- docs/ima.md
- docs/index.md
- docs/introduction.md
- docs/related-projects.md
- docs/repo.md
- docs/repository-management.md
- docs/var.md
Describing how different types of rollbacks work.
> docs/atomic-rollbacks: Add a section on rollbacks

- src/switchroot/ostree-prepare-root.c
We're debating this over in https://github.com/CentOS/centos-bootc-dev/pull/27 and I have come to the conclusion that having changes to `/` persist across reboot by default was a bad idea.
- It conflicts with any kind of secure boot scenario
- Having things only go away on upgrades is in some ways even *more* surprising
- The term `transient` implies this
There may be a use case in the future for having something like `root.transient = persistent`, but this is just a better default.
> prepare-root: Switch to a tmpfs for transient root

- configure.ac
Release 2024.3
---
Post-release version bump
---
> Release 2024.3

- ci/gh-install.sh
- ci/installdeps.sh
- src/rofiles-fuse/main.c
- tests/test-rofiles-fuse.sh
rofiles-fuse: Port to statx
This allows us to query fsverity efficiently.
---
rofiles-fuse: Check fsverity flag for copyup
We need to do a copyup if fsverity is enabled.
Sadly to do this we can't just use ostree_break_hardlink
as is.
---
> rofiles-fuse: Check fsverity flag for copyup

- tests/test-admin-gpg.sh
- tests/test-commit-sign.sh
Short key IDs are not secure, and may be rejected by OpenPGP implementations.  See https://evil32.com/
> tests: Use long key IDs

- docs/Gemfile
This mimics the GitHub Pages environment so that you can build and serve the site locally for testing. It requires webrick these days.
> docs: Add webrick dependancy for building site locally

- tests/test-gpg-verify-result.c
Short key IDs are not secure, and may be rejected by OpenPGP implementations.  See https://evil32.com/
Sorry that I missed that before.
> tests: Use long key IDs, I found another one

- README.md
RHIVOS is a derivative of CentOS Automotive Stream Distribution that uses OSTree, it's closest Fedora derivative is Fedora IoT although it was created as it's own distribution.
> README: Add Red Hat In-Vehicle Operating System

- .github/dependabot.yml
- .github/workflows/docs.yml
workflow/docs: Update to actions/checkout@v4
---
dependabot: Update github-actions weekly
> workflow/docs: Update to actions/checkout@v4 & dependabot: Update github-actions weekly

- tests/libtest.sh
- tests/pull-test.sh
- tests/test-admin-deploy-var.sh
- tests/test-commit-sign.sh
- tests/test-composefs.sh
- tests/test-create-usb.sh
- tests/test-delta-ed25519.sh
- tests/test-export.sh
- tests/test-find-remotes.sh
- tests/test-gpg-signed-commit.sh
- tests/test-libarchive.sh
- tests/test-local-pull.sh
- tests/test-parent.sh
- tests/test-pre-signed-pull.sh
- tests/test-pull-collections.sh
- tests/test-pull-contenturl.sh
- tests/test-pull-mirror-summary.sh
- tests/test-pull-repeated.sh
- tests/test-pull-summary-caching.sh
- tests/test-pull-summary-sigs.sh
- tests/test-signed-commit.sh
- tests/test-signed-pull-summary.sh
- tests/test-signed-pull.sh
- tests/test-summary-update.sh
- tests/test-summary-view.sh
* tests: Generalize has_gpgme, has_sign_ed25519 into has_ostree_feature
* tests: Use skip_without_ostree_feature to detect libarchive, composefs
This avoids false negatives from `ostree --version | grep -q ...` exiting with failure under `set -o pipefail` because `grep -q` can exit as soon as it sees the desired string, leaving `ostree --version` to be terminated by `SIGPIPE` next time it writes to stdout.
* test-admin-deploy-var: Don't rely on OSTREE_FEATURES
This is set during build-time testing, but unset during "as-installed" tests.
Resolves: https://github.com/ostreedev/ostree/issues/3183
> test-admin-deploy-var: Don't rely on OSTREE_FEATURES

- src/switchroot/ostree-prepare-root-static.c
- src/switchroot/ostree-prepare-root.c
This fixes a comment mentioning a kernel bug which is not really a bug but expected behavior.
> ostree-prepare-root: Amend comment about shared mounts

- README.md
- docs/CONTRIBUTING.md
- docs/README-historical.md
- docs/README.md
- docs/adapting-existing.md
- docs/atomic-rollbacks.md
- docs/atomic-upgrades.md
- docs/authenticated-repos.md
- docs/bootloaders.md
- docs/buildsystem-and-repos.md
- docs/composefs.md
- docs/contributing-tutorial.md
- docs/deployment.md
- docs/formats.md
- docs/ima.md
- docs/index.md
- docs/introduction.md
- docs/related-projects.md
- docs/repo.md
- docs/repository-management.md
- docs/var.md
docs: Consistently use SPDX identifiers
Standardize on a single SPDX identifier in a comment at the top.
---
docs: Misc whitespace fixes
---
README & docs: Sync README and docs index page
> Docs fixes & SPDX identifiers uniformisation

- src/switchroot/ostree-prepare-root.c
As mentioned in https://github.com/ostreedev/ostree/issues/3187, we can't allow a hotfix overlay of /usr when using signed composefs images as that would allow an attacker to persist something used across boots.
> prepare-root: Disallow hotfixes if using signed composefs images

- src/libostree/ostree-impl-system-generator.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- src/libotcore/otcore-prepare-root.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
- tests/test-otcore.c
In Android Boot environment we do not parse ostree= karg to determine
what directory to boot into, alternatively we do this based on the
androidboot.slot_suffix= karg. But we do set ostree=true karg to denote
that we are indeed booting an ostree environment (required for some
systemd unit files). This change accounts for this approach in the
systemd generator. In this case androidboot.slot_suffix= points you to
/ostree/root.[a|b] and then that points you to the directory to boot
into in /ostree/deploy... Here is what a cmdline may look like in this
type of environment:
androidboot.slot_suffix=_a androidboot.bootdevice=*.ufshc root=PARTLABEL=system_a root=UUID=76a22bf4-f153-4541-b6c7-0332c0dfaeac rw ostree=true loglevel=4 acpi=off console=ttyAMA0 systemd.show_status=auto …
> generator: Fixes for Android Boot environment

- src/libostree/ostree-impl-system-generator.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- src/libotcore/otcore-prepare-root.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
- tests/test-otcore.c
Be more explicit in the comment, and use gboolean over bool. Less header
inclusions when we use gboolean. Although bool is used in some places.
Write a separate _ostree_sysroot_parse_bootlink_aboot function for
aboot. Make is_aboot optional. Handle invalid androidboot karg and no
ostree and androidboot kargs differently.
Co-authored-by: Jonathan Lebon <jonathan@jlebon.com>
Signed-off-by: Eric Curtin <ecurtin@redhat.com>
> sysroot: Reword comment and use gboolean over bool, error handling

- docs/CONTRIBUTING.md
- docs/README-historical.md
- docs/adapting-existing.md
- docs/atomic-rollbacks.md
- docs/atomic-upgrades.md
- docs/authenticated-repos.md
- docs/bootloaders.md
- docs/buildsystem-and-repos.md
- docs/composefs.md
- docs/contributing-tutorial.md
- docs/deployment.md
- docs/formats.md
- docs/ima.md
- docs/index.md
- docs/introduction.md
- docs/related-projects.md
- docs/repo.md
- docs/repository-management.md
- docs/var.md
docs: Move SPDX identifiers under first title
Having a comment right before the first title apparently confuses
Jekyll.
Fixes: https://github.com/ostreedev/ostree/pull/3185
---
docs: Cleanup title for historical OSTree README
> docs: Move SPDX identifiers under first title

- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-sepolicy-private.h
- src/libostree/ostree-sepolicy.c
- src/libostree/ostree-sepolicy.h
As this is only used by internal code, just drop the `_OSTREE_PUBLIC` marker for now.  If we have a reason to export it we can do that later.
Closes: https://github.com/ostreedev/ostree/issues/3182
> sepolicy: Fix publicity mismatch for ostree_sepolicy_host_enabled

- src/ostree/ot-main.c
In order to do a runtime feature check, `ostree --version` can be piped to `grep` or similar. However, if the read end of the pipe doesn't read all of the output, `ostree` will receive `SIGPIPE` when trying to write output. Ignore it so that `ostree` still exits successfully in that case.
> main: Ignore SIGPIPE when printing version

- src/libotcore/otcore-prepare-root.c
Now that we're using `otcore_load_config` from the deploy path we end up printing to stdout even for API callers (e.g. our own CLI tools, and rpm-ostree/bootc/etc) which is wrong.
We don't need this print, so just drop it.
> otcore: Drop config load print

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/admin-test.sh
- tests/inst/src/destructive.rs
- tests/test-admin-deploy-2.sh
- tests/test-admin-deploy-bootprefix.sh
- tests/test-admin-deploy-karg.sh
- tests/test-admin-deploy-nomerge.sh
- tests/test-admin-deploy-none.sh
- tests/test-admin-deploy-syslinux.sh
- tests/test-admin-instutil-set-kargs.sh
- tests/test-admin-kargs.sh
- tests/test-admin-pull-deploy-split.sh
- tests/test-admin-upgrade-endoflife.sh
- tests/test-no-initramfs.sh
I think it's about time we flipped this on by default; like the bootprefix I was a bit too chicken.  We still have a `bootloader-naming-1` that can be flipped on in case of some regression.
Closes: https://github.com/ostreedev/ostree/issues/2961
> sysroot: Turn on bootloader-naming-2 by default

- src/libostree/ostree-kernel-args.c
- src/ostree/ot-admin-builtin-deploy.c
- tests/test-admin-deploy-karg.sh
- tests/test-kargs.c
According to Jonathan's suggestion, should fix the code from
ostree repo.
With this patch:
- kargs input like "init_on_alloc=1 init_on_free=1", will be
parsed as 2 seperated args `init_on_alloc=1` and `init_on_free=1`,
instead of whole;
- According to https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html,
need to keep spaces in double-quotes, like `param="spaces in here"`
will be parsed as whole instead of 3.
Fixes https://github.com/coreos/rpm-ostree/issues/4821
> kargs: parse spaces in kargs input and keep quotes

- src/libostree/ostree-sysroot-deploy.c
I found an issue while testing [Aktualizr](https://github.com/uptane/aktualizr) (an update client that supports OSTree) with the latest libostree version: basically, the program failed when deploying an update, something that didn't happen with older libostree versions. Through code bisection I found the program stopped working after the commit c561e6179e965d11bba7e1d80ca35b7ad6fc7bc5 on the ostree project repository:
```
$ git log -1 c561e6179e965d11bba7e1d80ca35b7ad6fc7bc5
commit c561e6179e965d11bba7e1d80ca35b7ad6fc7bc5
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Thu Apr 13 17:22:43 2023 -0400
lib/sysroot-deploy: Add experimental support for automatic early prune
During the early design of FCOS and RHCOS, we chose a value of 384M
for the boot partition. This turned out to be …
```
> Ensure boot directory is open before accessing it for early pruning

- src/libostree/ostree-fetcher-curl.c
- src/libostree/ostree-fetcher-soup.c
- src/libostree/ostree-fetcher-soup3.c
- src/libostree/ostree-fetcher-util.c
- src/libostree/ostree-fetcher-util.h
When we added the retry logic, the intention here was definitely to do it not just for network errors but also e.g. HTTP 500s and the like.
xref https://pagure.io/releng/issue/11439
where we rather painfully debugged that this was missing.
> curl: Also map HTTP errors for retries

- src/libostree/ostree-sepolicy.c
This can return NULL if there's no real policy.
Now obviously we need to update the Rust bindings too but... I am having trouble doing that, we're pretty out of date with upstream.
> sepolicy: Add missing `(nullable)`

- src/boot/ostree-prepare-root.service
This is stronger than the default (`replace`) because it tells systemd to *stop everything* and go to `emergency.target`. In other codebases, this has definitely helped me with the problem of "systemd keeps going even after a failure".
Likely addresses #3219.
See also e.g. https://github.com/coreos/ignition-dracut/commit/3d2e165f97f30c1e62577357f27f32e60e6add18.
> ostree-prepare-root.service: add OnFailureJobMode=isolate

- README.md
- docs/index.md
Remove the unofficial acronym RHIVOS from both the README and docs
files. The acronym is associated with Red Hat In-Vehicle Operating
System but isn't officially recognized.
> README & docs: Remove "RHIVOS" acronym

- man/ostree-admin-init-fs.xml
- src/ostree/ot-admin-builtin-init-fs.c
- tests/admin-test.sh
I want to add another variant here, and `--modern` is now old.  Let's acknowledge that we may want to make even more changes in the future.  So `--modern == --epoch=1` but I will add `--epoch=2` after this.
> init-fs: Add --epoch

- .cci.jenkinsfile
- .gitmodules
- Makefile-libostree.am
- Makefile-switchroot.am
- Makefile.am
- autogen.sh
- ci/installdeps.sh
- configure.ac
- tests/test-admin-deploy-composefs.sh
Since there's now a stable shared library, let's use it.
> Switch to external composefs

- man/ostree-admin-init-fs.xml
- src/ostree/ot-admin-builtin-init-fs.c
- tests/admin-test.sh
We want to start switching things so that the toplevel `/ostree` repository is mode 0700, to close off unprivileged code from being able to access it.  Previous deployment roots may have setuid binaries, etc.  The `/var/lib/containers/storage` directory is mode 0700 for this reason I believe.
Closes: https://github.com/ostreedev/ostree/issues/3211
> init-fs: Add --epoch=2

- src/libotcore/otcore-prepare-root.c
otcore_get_ostree_target() should set is_aboot for android boot systems, but currently it only does this on A/B boot systems, not single-boot-partition systems. Fix this by setting it in the second case.
> prepare-root: Handle non-AB aboot properly

- src/libostree/ostree-repo.c
- tests/test-rofiles-fuse.sh
- tests/test-summary-update.sh
I was looking into an HTTP caching issue in a different project and it occurred to me that there's no reason the `summary` and `summary.sig` files can't have synchronized mtimes since they're now created in a temporary directory. The first commit is unrelated and I can split it out if preferred.
> Sync summary times

- docs/bootloaders.md
The android bootloader is also split into two partitions, previously that wasn't represented in the diagram.
> docs: More accurate diagram in bootloaders documentation for aboot

- .github/workflows/tests.yml
- ci/clang-format.sh
- ci/codestyle.sh
- src/libostree/ostree-sysroot.c
Previously we were running clang-format across multiple operating system versions and hence clang versions, and it turns out clang has changed the preferred formatting multiple times.
We could *probably* dig in and try to pin things more strongly but eh...for now let's arbitrarily just use whatever's in the default GH Action ubuntu-latest runner as that should be equally painful for everyone.
> ci: Only run clang-format on ubuntu-stable GH runner

- Makefile-tests.am
- src/libostree/ostree-sysroot-deploy.c
- tests/test-admin-stateroot.sh
Our code currently does not check for stateroot as a differentiator between deployments, however given that we allow multiple stateroots, we should see them as different deployments in the same way we check for kargs for example.
> ostree-sysroot-deploy: check if deployments are in the same stateroot.

- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/admin-test.sh
Ironically we break if the timestamp there is zero.
Closes: https://github.com/ostreedev/ostree/issues/3022
> sysroot: Handle `/ostree/deploy` having epoch 0

- src/libostree/ostree-repo-verity.c
If supported_out is passed to _ostree_ensure_fsverity and we successfully exit early, for example because the file is a symlink, then *supported_out is not initialized.
This is problematic in the case of ostree_sysroot_update_post_copy(), because it passes in an uninitialized supported, and on successfull return of _ostree_ensure_fsverity() it assumes that it is iniialized.
In case supported happened to be initialized to non-zero it will take this branch:
if (!supported)
break; /* If not supported, skip rest */
Which means *all* further objects will not get fs-verity enabled.
> Fix _ostree_ensure_fsverity reporting of supports in early exit

- docs/copying-deltas.md
This one isn't immediately obvious that it's possible.
> docs: Describe offline updates with static deltas

- configure.ac
```
Alexander Larsson (3):
_ostree_ensure_fsverity: Properly check for errors
prepare-root: Handle non-AB aboot properly
Fix _ostree_ensure_fsverity reporting of supports in early exit
Colin Walters (12):
curl: Also map HTTP errors for retries
sepolicy: Add missing `(nullable)`
init-fs: Add --epoch
init-fs: Add --epoch=2
tests: Skip composefs tests without the feature
ci: Drop `SKIP_INSTALLDEPS=1`
Switch to external composefs
ci: Only run clang-format on ubuntu-stable GH runner
ci: Also skip if we detect /run/.containerenv
sysroot: Handle `/ostree/deploy` having epoch 0
docs: Describe offline updates with static deltas
Dan Nicholson (2):
tests: Correctly skip single fsverity test
repo: Make summary and signature mtime match
Eric Curtin (3):
README & …
```
> Release 2024.6

- README.md
Updated the README.md to include information about webOS, an OS for smart devices such as smart TVs, which from version 2.0.0 supports Firmware-Over-the-Air (FOTA) based on libostree. Added relevant links for further details on webOS and FOTA setup.
> docs: add webOS as users of libostree

- Makefile-libostree.am
- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-repo-composefs.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.h
- src/libostree/ostree-sysroot-deploy.c
- src/ostree/ot-builtin-checkout.c
- tests/test-composefs.sh
We were missing the simple, obvious API and CLI to go from ostree commit -> composefs.
Internally, we had `ostree_repo_checkout_composefs` with the right "shape" mostly, except it had more code in the deploy path to turn that into a composefs.
Add a straightforward public API that does what
the deploy code did before, and then the old
API becomes an explicitly internal helper with an `_` prefix.
Goals:
- Lead towards a composefs-oriented future
- This makes the composefs logic more testable directly
> checkout: Add API to directly checkout composefs

- src/switchroot/ostree-prepare-root.c
Mainly we can now drop the TODO for mounting `/` readonly - that's handled by composefs.  Add a few other comments, typo fixes while we're here.
> prepare-root: Cleanup comments

- docs/atomic-upgrades.md
People get confused by the sha256 here being different from the ostree commit hash.
> docs: Describe `/boot/ostree`

- ci/Containerfile.c9s
- ci/c9s-buildroot.repo
Because composefs-devel isn't shipped in RHEL.
> ci: Add buildroot to c9s build

- src/libostree/ostree-core-private.h
- src/libostree/ostree-core.c
- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-repo-commit.c
- tests/test-basic-c.c
In the ostree-ext codebase the test fixture was generating xattrs without the trailing NUL byte.  This caused confusing errors later.  Change the dirmeta validator to catch this.
The way GVariant represents bytestrings, the trailing NUL is there on wire/disk so it can be there in memory too, but `g_variant_get_bytestring()` will just return an empty `""` string if actually the value has a missing NUL.
> core: Validate that xattr names aren't empty

- src/boot/ostree-remount.service
- src/switchroot/ostree-remount.c
Ignore ENOENT error in selinux_restorecon to avoid failures when temporary files created by systemd-sysusers in /etc are missing during relabeling. This prevents errors such as:
"Failed to relabel /etc/.#gshadowJzu4Rx: No such file or directory"
and allows the process to continue.
> remount: ignore ENOENT error during SELinux relabeling

- docs/composefs.md
- src/libostree/ostree-repo-verity.c
This fixes `ostree sign` command line in the doc, and removes no longer used OpenSSL includes .
> Minor cleanup related to composefs

- .github/workflows/bootc.yaml
As newer docker refuses to talk to ancient skopeo. Update this to use podman directly, also add the missing `-v /dev:/dev`.
> ci: Bump bootc e2e to latest ubuntu, drop docker

- src/boot/ostree-remount.service
This created an ordering cycle, and I merged over red CI for bad reasons.
> remount: Drop `Before=systemd-sysusers.service`

- src/libostree/ostree-mutable-tree.c
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-static-delta-core.c
- src/switchroot/ostree-prepare-root.c
tree: Fix `name` memory leak
Coverity points out that we have a memory leak from `g_strdup(name)`.
`insert_child_mtree()` takes a const char * and duplicates it.
`name` can be passed directly to `insert_child_mtree()`.
---
commit: Null terminate `target_buf` var
Coverity points out that we are passing an unterminated string to
sprintf().
---
repo: Fix `dir_or_file_path` memory leak
Coverity points out that we have a memory leak from
`g_strdup(dir_or_file_path)`. We use `g_path_get_dirname()` which
modifies the string in place, to which coverity should understand.
---
prepare: Create global var for tmp_sysroot_etc
Coverity points out that ""/sysroot.tmp/etc"" could be a copy-paste
error. This is mistake from coverity, but to supress the warning,
we create a global var, tmp_sysroot_etc, …
> 2023.8-3 coverity scan

- src/libostree/ostree-sysroot-cleanup.c
Fix the TODO here; this was making some bootc output ugly.
> sysroot: Use journal rather than printf()

- src/libostree/ostree-autocleanups.h
- src/libostree/ostree-repo-finder-avahi.h
- src/libostree/ostree-repo-finder-config.h
- src/libostree/ostree-repo-finder-mount.h
- src/libostree/ostree-repo-finder-override.h
- src/libostree/ostree-repo-finder.h
- src/libostree/ostree-sign-dummy.c
- src/libostree/ostree-sign-dummy.h
- src/libostree/ostree-sign-ed25519.c
- src/libostree/ostree-sign-ed25519.h
- src/libostree/ostree-sign.h
- tests/test-mock-gio.h
As the build system has required GLib 2.44 since commit eb09207e1abd7499bd92866cce1de6148d659a4a, the manual expansion of G_DECLARE_INTERFACE and G_DECLARE_FINAL_TYPE is no longer necessary.
> libostree: Remove compatibility code with GLib < 2.44

- src/libotutil/ot-keyfile-utils.c
- src/libotutil/ot-keyfile-utils.h
- tests/test-keyfile-utils.c
Prep for using this in multiple places. Add unit tests.
> keyfile-utils: Add API to parse tristate strings

- man/ostree-prepare-root.xml
- src/libostree/ostree-sysroot-deploy.c
- src/libotcore/otcore-prepare-root.c
- src/libotcore/otcore.h
- src/libotutil/ot-keyfile-utils.c
- src/libotutil/ot-keyfile-utils.h
- src/switchroot/ostree-prepare-root.c
- tests/inst/src/composefs.rs
- tests/test-keyfile-utils.c
We have a use case for overriding the composefs state via
the kernel commandline; see e.g.
https://gitlab.com/fedora/bootc/tracker/-/issues/27
Signed-off-by: Colin Walters <walters@verbum.org>
> prepare-root: Add ostree.prepare-root.composefs

- Makefile-tests.am
- src/libostree/ostree-repo-commit.c
- tests/test-payload-link.sh
Coverity was correctly complaining about this.
> repo: NUL terminate readlinkat result

- src/libostree/ostree-sysroot-deploy.c
- src/switchroot/ostree-prepare-root.c
bootc doesn't run as a systemd unit, and this pollutes stderr.
> deploy: Log to journal for boot space, not stderr

- src/libostree/ostree-repo-commit.c
This is another warning from recently changed code from Coverity:
```
1. Defect type: OVERRUN
16. libostree-2024.7/src/libostree/ostree-repo-commit.c:823:7: overrun-buffer-arg: Overrunning array "target_checksum" of 65 bytes by passing it to a function which accesses it at byte offset 258 using argument "size" (which evaluates to 259). [Note: The source code implementation of the function has been overridden by a builtin model.]
```
I think this can only happen if the repository is corrupt; the data shouldn't be that long. But fix this by passing the max length we expect; this will ignore the rest currently.
> commit/payload-link: Ensure we don't overrun target_checksum size

- src/libostree/ostree-sysroot.c
Similar to d528083cae3492f9b9424f3c9830869af7b4cbd0 - I don't believe we actually had a leak here because `dirname` always returns the same start pointer, but this makes Coverity happy.
> sysroot: Make coverity happy with dirname+strdup

- src/libostree/ostree-sysroot-deploy.c
- src/switchroot/ostree-prepare-root.c
- tests/kolainst/destructive/auto-prune.sh
We need to look in the journal since
https://github.com/ostreedev/ostree/pull/3282/commits/3d07a808ce9a764c98560279fc444d2e4fb901db
> tests: Attempt to update auto-prune test

- .github/workflows/tests.yml
See: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
See: https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/
> github/workflows/tests: Update actions/upload-artifact to v4

- .copr/Makefile
Fix copr build error:
`line 11: Possible unexpanded macro in: Release: %autorelease`
> spec: %autorelease can't be resolved by COPR

- src/libostree/ostree-bootloader-grub2.c
- tests/kolainst/destructive/bootupd-static.sh
In #3205, we introduced a check to skip re-generating the GRUB config if we detect that static configs are in used by looking at bootupd's state.
Unfortunately this check is incomplete and does not account for present but null entries in the JSON state file.
A proper fix would be to parse the JSON but this requires a larger code change.
Fixes: https://github.com/ostreedev/ostree/issues/3295
Fixes: https://github.com/ostreedev/ostree/pull/3205
> bootloader/grub2: Handle empty static configs

- .github/workflows/docs.yml
A couple fixes to make PRs and non-PRs work correctly:
* In a conditional expression, `true` or `false` are returned unless you terminate both sides in a ternary. That was causing 2 strings to be suffixed with `false` instead of an empty string.
* For a PR, we do actually want to cancel in progress runs since there's no danger of breaking an in progress deployment.
* For PRs, just use the same `github-pages-pr` name for the artifact. The important part is that it's not called `github-pages` where an in progress deployment could pick it up. Otherwise it can use the same name all the time.
I've tested this now in my repo in all 3 triggers:
* [PR](https://github.com/dbnicholson/ostree/actions/runs/10873928054)
* [Push](https://github.com/dbnicholson/ostree/actions/runs/10873968648)
* …
> workflow/docs: Fix deployments

- src/libostree/ostree-fetcher-curl.c
ref https://github.com/ostreedev/ostree/issues/3299
This won't fix that issue, but *if* this assertion triggers it should give us a better idea of the possible codepaths where it is happening.
> curl: Assert that curl_multi_assign worked

- src/libostree/ostree-fetcher-curl.c
Because curl_multi_cleanup may invoke callbacks, we effectively have
some circular references going on here. See discussion in
https://github.com/curl/curl/issues/14860
Basically what we do is the socket callback libcurl may invoke into a no-op when
we detect we're finalizing. The data structures are owned by this object and
not by the callbacks, and will be destroyed below. Note that
e.g. g_hash_table_unref() may itself invoke callbacks, which is where
some data is cleaned up.
Signed-off-by: Colin Walters <walters@verbum.org>
---
> curl: Make socket callback during cleanup into no-op

- rust-bindings/README.md
- rust-bindings/src/lib.rs
It should now point at GH pages.
Closes: https://github.com/ostreedev/ostree/issues/3312
> rust-bindings: Fix readthedocs.io link

- src/libostree/ostree-fetcher-curl.c
Followup to the previous curl fixes; if we'd had an assertion earlier debugging the failure would have been more obvious.
All of these are "should not fail" cases so asserting is right.
> curl: Add more assertions for curl return values

- src/libostree/ostree-repo-commit.c
xref https://github.com/ostreedev/ostree/issues/3319
It'd be useful to know what file type is being hit here; I believe this code path should be unreachable.
> commit: Give a better error message for unhandled file type

- src/switchroot/ostree-mount-util.h
- src/switchroot/ostree-prepare-root-static.c
- src/switchroot/ostree-prepare-root.c
> prepare-root: allow `sysroot.readonly=true` with kernel cmdline `ro`

- src/libostree/ostree-sysroot-deploy.c
xref: https://github.com/coreos/fedora-coreos-tracker/issues/1808
For the kernel/initramfs that we copy to `/boot`
we use an explicit relabeling today, ignoring the source SELinux
context.
When we added handling for devicetree it reuse the `copy_dir_recurse`
we have for `etc` handling, and that copied the source xattrs.
Let's ensure that the devicetree is also `boot_t` by *not* copying
xattrs and relying on the default labeling.
> deploy: Don't copy xattrs for devicetree

- man/ostree-checkout.xml
- src/libostree/ostree-repo-checkout.c
- src/libostree/ostree-repo-composefs.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-sysroot-deploy.c
- src/libotutil/ot-gio-utils.c
- src/libotutil/ot-gio-utils.h
- src/ostree/ot-builtin-checkout.c
- tests/test-composefs.sh
- tests/test-ot-unix-utils.c
This fixes a truly horrific performance bug when
composefs is enabled, but fsverity is not supported by the filesystem. We'd fall back to doing *userspace* checksumming of all files at deployment time which was absolutely not expected or required.
There's really an immense amount of technical debt here, such as the confusion between `ex-integity.composefs` vs the prepare-root config, how we handle "torn" states where some objects don't have verity enabled but some do, etc.
The ostree composefs state has two modes:
- signed: We need to enforce fsverity
- unsigned: Best effort resilience
So we fix this by making the deploy path to make verity "opportunistic" - if the ioctl gives us the data, then we add it to the composefs.
However, this code path is also invoked when we're computing the …
> deploy: Don't recompute verity checksums if not enabled

- tests/inst/src/sysroot.rs
Needed changing after FCOS switch.
> tests: Skip checking for immutable bit on composefs

- man/ostree-prepare-root.xml
In practice in ostree-sysroot-deploy.c we only react to having `composefs = yes`; the docs mention `maybe` but that never did anything.
The value is wrong in the code too, but I'm not touching that here to avoid conflating changes - the main thing to fix is the docs because here `maybe == no`.
> prepare-root: Fix composefs docs

- src/libostree/ostree-repo-composefs.c
struct fsverity_digest starts with a __u16, so it will normally require 16-bit alignment, which is not guaranteed for a char array.
Resolves: https://github.com/ostreedev/ostree/issues/3339
---
This is untested: sorry, I don't currently have any filesystems with fsverity enabled.
> composefs: Ensure buffer is suitably aligned for struct fsverity_digest

- src/libostree/ostree-core.c
- tests/test-basic-c.c
When recomputing selinux attrs during commit, we weren't sorting, which could cause various issues like fsck failures.
This is a big hammer; change things so we always canonicalize (i.e. sort) the incoming xattrs when creating a file header.
I think almost all places in the code were already keeping things sorted, but it's better to ensure correctness first. If we ever have some performance issue (I'm doubtful) we could add something like `_ostree_file_header_known_canonicalized` or so.
Closes: https://github.com/ostreedev/ostree/issues/3343
> core: Always sort incoming xattrs

- src/rofiles-fuse/main.c
rofiles-fuse: Fixed the problem that when fuse execution fails, the command returns a status code of 0
testcase:
`$ sudo rofiles-fuse a b`
fuse: bad mount point `b': No such file or directory 
`$ echo $?`
0
> rofiles-fuse: when fuse execution fails, rofiles-fuse still returns exit code 0

- docs/composefs.md
- man/ostree-prepare-root.xml
- src/libostree/ostree-sysroot-deploy.c
- src/libotcore/otcore-prepare-root.c
- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
In the current implementation, a composefs deploy is either:
- signed by key and verified by fs-verity, or
- not signed and not verified.
This PR adds a new supported value `verity` to `composefs.enabled`, which:
- requires the composefs to be verified by fs-verity;
- does not require it to be signed.
The idea is that:
- If we do not specify `LCFS_MOUNT_FLAGS_REQUIRE_VERITY` (the underlying of which is `verity=require` when mounting overlayfs), overlayfs does not verify file data even if fs-verity digests are present in the image.
- It is difficult and troublesome to have the ostree commit signed in some circumstances. For example, when deploying with custom layering.
- In some cases, the integrity of the composefs image is already protected by other mechanisms, for example EVM. It is not …
> prepare-root: Add composefs.enabled=verity

- src/libostree/ostree-sysroot-deploy.c
- tests/admin-test.sh
- tests/test-admin-deploy-composefs.sh
The composefs libostree integration has been supported for a while now
and is actively in use in various ostree/bootc-based systems. Let's
turn it on by default.
This has no effect if composefs support is not compiled in. Note also
that this does not change the default value of the `composefs.enabled`
tristate to `true`. The default is still `maybe`, but the deploy API
will now also create composefs images for `maybe`.
The reason for doing it this way is so that systems upgrading from
old libostree versions (which may either not have composefs support or
may have composefs-related bugs) will still be able to upgrade and not
trip `ostree-prepare-root` in the new deployment (which allows missing
composefs images for `maybe`).
We may in the future change the default value to `true`.
See …
> libostree/deploy: enable composefs by default

- man/ostree-prepare-root.xml
It's all quite confusing having to reason about both the pre-composefs ostree and the composefs version. But hopefully soon we more firmly leave behind that first legacy.
> man: Note semantics combining `root.transient` with `composefs.enabled`

- src/libostree/ostree-bootloader-zipl.c
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-sysroot.c
- src/libotutil/ot-unix-utils.c
- src/libotutil/ot-unix-utils.h
- src/ostree/ot-main.c
I believe the correct way is to check `geteuid() == 0`, not `getuid() == 0`.
> chore: Use geteuid() instead of getuid() to check privilege

- Makefile-libostree.am
- configure.ac
- src/libostree/libostree-devel.sym
- src/libostree/libostree-released.sym
- tests/test-symbols.sh
This Release adds one new feature introduced on: https://github.com/ostreedev/ostree/pull/3362 which adds a new `--kexec` flag to `ostree admin upgrade` which will cause the deployment to be loaded into kexec after the upgrade completes.
Other than that it mostly a bugfix and small improement release with the more significant change being https://github.com/ostreedev/ostree/pull/3366 which relates to composefs and notably does:
- If composefs is enabled at build time, we always generate a composefs blob at deplyment time
- Configuring the prepare-root config now mostly only affects the runtime state.
```
Colin Walters (2):
tree-wide: Rerun clang-format, update ci
Always generate composefs blob, don't enable runtime by default
Joseph Marrero Corchado (1):
Release 2025.1
Mary Strodl (1): …
```
> Release 2025.1

- docs/contributing-tutorial.md
Fix issues in Dockerfile:
1. Update Fedora image to the latest version 41, otherwise docker build fails with an error:
```
Step 1/7 : FROM registry.fedoraproject.org/fedora:28
manifest for registry.fedoraproject.org/fedora:28 not found: manifest unknown: manifest unknown
```
2. Force install python3-yaml package, as it's required for running some tests. For example, tests/test-remote-headers.sh will fail without it:
```
V=$($CMD_PREFIX ostree --version | \ python3 -c 'import sys, yaml; print(yaml.safe_load(sys.stdin)["libostree"]["Version"])') 
Traceback (most recent call last): 
File "<string>", line 1, in <module> 
import sys, yaml; print(yaml.safe_load(sys.stdin)["libostree"]["Version"])
^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'yaml'
```
With these fixes `make check` …
> docs: update Dockerfile

- src/libotutil/ot-unix-utils.c
sys/prctl.h already provides prctl.h and adding both imports fails on musl libc:
/usr/include/sys/prctl.h:88:8: error: redefinition of 'struct prctl_mm_map'
88 | struct prctl_mm_map {
|        ^~~~~~~~~~~~
In file included from src/libotutil/ot-unix-utils.c:33:
/usr/include/linux/prctl.h:134:8: note: originally defined here
134 | struct prctl_mm_map {
|        ^~~~~~~~~~~~
> libotutil: Remove redundant import of prctl.h

- src/libostree/ostree-bootloader-zipl.c
Since s390-tools commit [f4cf4ae6ebb1](https://github.com/ibm-s390-linux/s390-tools/commit/195579cf0bcff320ed9ebe2cab6b59c9cc817f6e) (Remove genprotimg-C and switch to genprotimg-Rust implementation)
`genprotimg` is just a symlink to `pvimg create`, which by default doesn't overwrite the output image,
but introduces the `--overwrite` flag for this. Let's silently remove the file to support both tools.
Issue: https://github.com/openshift/os/issues/1731
> zipl: remove 'sdboot' image before generating new one

- src/libotcore/otcore.h
- src/switchroot/ostree-prepare-root.c
On general principle, but specifically as I wanted to cross-check this when debugging something else.
> prepare-root: Log when we're mounting with verity required

- Makefile-libostree.am
- apidoc/ostree-sections.txt
- src/libostree/libostree-devel.sym
- src/libostree/ostree-sepolicy.c
- src/libostree/ostree-sepolicy.h
- src/ostree/ot-main.c
Let's quiet the output of libselinux by default, all we get is the pointless "regex version mismatch" warnings. This is what e.g. systemd does.
This is exposed via the library; our binary opts in, then we expect higher level tools like e.g. bootc to do this too.
> sepolicy: Add ostree_sepolicy_set_null_log

- configure.ac
- src/libostree/ostree-1.pc.in
This makes it possible to use pkg-config to link against libostree as a static library.  Unlike shared libraries, static libraries don't encode their dependencies in the library file, so we have to communicate them via pkg-config.
> libostree: add private dependencies to pkg-config

- src/libostree/ostree-core-private.h
- src/libostree/ostree-core.c
- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo.c
- tests/basic-test.sh
core: Print which xattrs are not sorted
I hit this in the rpm-ostree rechunker flow somehow
and with this change I now get:
`error: Generating commit from rootfs: Processing dir var: Writing content object: Incorrectly sorted xattr name (prev=user.Librepo.checksum.mtime, cur=security.selinux), index=2`
which is more useful, although I still need to figure out
and fix why that's happening (again?).
Signed-off-by: Colin Walters <walters@verbum.org>
---
commit: Add errprefix for bareuser metadata
To aid debugging.
Signed-off-by: Colin Walters <walters@verbum.org>
---
tests/basic: Add lots of user. xattrs
This exercises our requirement for xattr sorting.
Signed-off-by: Colin Walters <walters@verbum.org>
---
core: canonicalize bare-user xattrs
Previously we were erroring out if xattrs were …
> core: Fix bare-user xattr canonicalization

- src/libostree/ostree-repo-commit.c
We saw this in an error message:
```
error: Generating commit from rootfs: syncfs: Not a directory
```
I'm pretty sure it's this function call but let's be a bit more sure by adding a bit more context.
> commit: Clarify that syncfs is of repo/tmp

- src/libotcore/otcore.h
While libotcore can be configured with those options individually, the latter is always required for OpenSSL's EVP functions. This splits the ifdefs to accommodate that.
Fixes: #3399
> Fix build error with --with-ed25519-libsodium and --with-openssl

- Makefile-tests.am
- tests/test-backcompat-fsck.sh
We don't have a lot in the way here of formal upgrade/compat tests, but we definitely should.
Most of our tests just test the built ostree.
I believe this would have caught compatibility issues with https://github.com/ostreedev/ostree/pull/3346
> tests: Add backcompat-fsck test

- man/ostree-remote.xml
Looking at the implementation [here](https://github.com/ostreedev/ostree/blob/main/src/ostree/ot-remote-builtin-delete-cookie.c#L48) we can see the $VALUE is not used. 
It would also be weird to have to supply a VALUE to a delete operation
> docs: removed unused argument

- man/ostree-prepare-root.xml
Closes: https://github.com/ostreedev/ostree/issues/3409
> prepare-root: Document that /var is unaffected by root.transient

- Makefile-libostree.am
- src/libostree/ostree-impl-system-generator.c
Ref https://github.com/ostreedev/ostree/pull/3406
There's a combination of two commits here that broke the static prepareroot path:
ec1109c7a93a2ed07503b12ffecf7048cf7cc0d0
"generator: Stop creating `/run/ostree-booted`"
and more recently
b9ce0e89801bbc92d50473d3620b3f41f1dbef9f
generator: Exit if there's no `/run/ostree`
Basically when run via a non-static prepareroot we create `/run/ostree-booted` consistently in the initramfs, using the kernel argument presence as source of truth.
But for the static prepareroot, the generator checked the kernel argument, and had a fallback of creating it.
Except that's busted in the case of running in a
container, where with many runtimes we still
default to seeing the host's commandline (which
is basically wrong...but fixing that requires a
userspace …
> generator: Still create /run/ostree in static prepareroot path

- src/libostree/ostree-sysroot-deploy.c
Bootloader entry should only have aboot and abootcfg configuration entries when aboot.img is found on the system (e.g. /usr/lib/modules/$kver).
Otherwise it will be always set, won't be used during boot and systemd-boot will complain about unknown lines.
> deploy: only set aboot/abootcfg when found

- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot-private.h
- src/libostree/ostree-sysroot.c
- tests/kolainst/nondestructive/itest-alt-sysroot.sh
We do want to support this (as part of supporing the Boot Loader Spec) but because we use symlinks in `/boot`, can't yet.
Error out very early on consistently if we detect
vfat for /boot, but also add a member variable to keep track of this in preparation for supporting it.
> sysroot: Detect early on when /boot is on vfat

- .cci.jenkinsfile
This got dropped apparently with the osbuild rewrite.
> ci: Drop --fast from buildextend-live

- .github/workflows/rust.yml
- deny.toml
It looks like the v1 action due to a crate bump
started hard requiring a newer rust?
> ci: Update deny to v2

- tests/inst/src/test.rs
Fixes:
warning: unused import: `with_procspawn_tempdir::with_procspawn_tempdir`
--> src/test.rs:11:9
|
11 | pub use with_procspawn_tempdir::with_procspawn_tempdir;
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
help: if this is a test module, consider adding a `#[cfg(test)]` to the containing module
--> src/insttestmain.rs:9:1
|
9  | mod test;
| ^^^^^^^^^
= note: `#[warn(unused_imports)]` on by default
> tests: remove unused import

- .cci.jenkinsfile
- .dockerignore
- .gemini/config.yaml
- .github/workflows/rust.yml
- .github/workflows/tests.yml
- apidoc/ostree-docs.xml
- ci/installdeps.sh
- ci/libbuild.sh
- ci/prow/Dockerfile
- tests/libtest.sh
apidoc: Quiet many warnings
Should have done this long ago, this greatly reduces the spam
in the terminal logs from builds.
---
dockerignore: Add
This ensures we don't pick up things we shouldn't from the source.
---
ci: Updates for centos builds
- Do the modern way to enable the buildroot with crb and epel
---
tests/libtest: Just use python as a webserver if no libsoup
We only have a very few tests that actually need what
we have in ostree-trivial-httpd that supports things like serving
random 500 errors etc.
If we don't have libsoup, then just use a python webserver.
---
> A few buildsystem fixes

- src/libotcore/otcore-prepare-root.c
An AI code review tool spotted incorrect usage of GError. Awesome.
> prepare-root: Fix error overwrite

- src/libostree/ostree-sysroot.c
We fixed the bug that caused soft reboot to trip the assertion here, so revert back to a hard check.
> sysroot: Remove now-spurious assertion change from soft reboot changes

- .github/workflows/bootc.yaml
Because it's an active development target.
> ci: Expand bootc testing to cover c10s

- Makefile-libostree.am
- configure.ac
- src/libostree/libostree-devel.sym
- src/libostree/libostree-released.sym
- tests/test-symbols.sh
Release 2025.3
```
Christoffer N (1):
docs: removed unused argument
Colin Walters (58):
Post-release version bump
tests: Add backcompat-fsck test
rust: Add support for `locked` option for `SysrootDeployTreeOpts`
unlock: Use deployment backing dir
sysroot: Load bootloader configs via boot_fd
generator: Still create /run/ostree in static prepareroot path
prepare-root: Document that /var is unaffected by root.transient
bin/set-origin: Don't crash if origin has no refspec
tests: Don't mutate usr/sbin separately
tests: Drop use of host_refspec
tests/auto-prune: Add logging for steps
tests/prune: Minor refactor and logging
tests/prune: Ensure /boot is big enough for 3 bootdata
sysroot: Detect early on when /boot is on vfat
rust: Update to 2025.2
ci: Drop --fast from buildextend-live
ci: Update …
```
> Release 2025.3

- Makefile-tests.am
Fixes the case of doing `make dist` without some
build features enabled.
Closes: https://github.com/ostreedev/ostree/issues/3469
> build-sys: Always EXTRA_DIST test scripts

- src/libotcore/otcore-prepare-root.c
Only create the transient etc directory once to prevent failures due to directory existence.
Fixes #3476.
> ostree-prepare-root: remove duplicate transient directory

- src/libostree/ostree-sysroot-deploy.c
The code in get_kernel_from_tree_usrlib_modules() that checks for an "aboot.cfg" does nothing with it (and in fact may leak the fd in case its there). In practice, /usr/lib/modules never has an aboot.cfg, so this is just completely dead code.
> deploy: Remove some dead aboot code

- src/libotcore/otcore-prepare-root.c
Since this can now be used as part of the shared library for soft reboots, we shouldn't have a library write to stdout. I noticed this in bootc. Use the journal instead.
> prepare-root: Log to journal, not stdout

- src/libostree/ostree-repo-commit.c
- src/libostree/ostree-repo-private.h
- src/libostree/ostree-repo.c
- src/libostree/ostree-sysroot-deploy.c
- src/libostree/ostree-sysroot.c
- tests/kolainst/destructive/staged-deploy.sh
This is a followup to https://github.com/ostreedev/ostree/pull/3504/commits/6e5a27a29d33d50a2a4380c406405435d919b6b4
which I believe is correct as is. However, we already have a file
descriptor open for the ostree repo, which *must* be on
the same filesystem as `/sysroot/ostree` (the deployment
code forces hardlinking today).
It's hence cleaner to reuse that extant fd instead of opening
a new one - we know we did writes to that fd.
But going farther here, there already is logic to use syncfs
for the repo when downloading objects (in a common case
we actually syncfs twice).
Since these are really the same operation, unify them:
- Add journaling to the repo one syncfs case
- Change the sysroot case to just call it
- Since we log consistently to the journal for all syncfs/fsfreeze
operations …
> Deduplicate repo+sysroot syncfs logic

- src/boot/ostree-finalize-staged.service
I've seen in some cases systemd try to unmount /etc quite early and then fail because it's in use.
It's confusing because I don't see this in all scenarios. But regardless, in the situations where it does occur, this fixes it.
> ostree-finalize-staged.service: RequiresMountsFor=/etc

- Makefile-boot.am
- src/boot/ostree-shutdown.service
- src/libostree/ostree-impl-system-generator.c
- src/switchroot/ostree-remount.c
We have a lot of bind mounts; these are usually set up in the initramfs.
So far during shutdown we've let systemd just try to sort things out
via auto-generated mount units i.e. `sysroot.mount` and `etc.mount`
and so on.
systemd has some special casing for `-.mount` (i.e. `/`) and `etc.mount`
https://github.com/systemd/systemd/blob/e91bfad241799b449df73efc30d833b9c5937001/src/shared/fstab-util.c#L72
However it doesn't special case `/sysroot` - which is currently
an ostree-specific invention (when used in the real root).
We cannot actually unmount `/sysroot` while it's in use, and it
is because `/etc` is a bind mount into it. And we can't tear
down `/etc` because it's just expected that e.g. pid 1 and other
things hold open references to it - until things finally
transition into …
> Add ostree-shutdown.service: hide /sysroot and make /etc read-only

- src/libotcore/otcore-prepare-root.c
When using bootc, if you convert a signed ostree commit into an OCI image `rpm-ostree compose container-encapsulate` you end up with a new commit that isn't signed. However, the base commit object, and its commitmeta are still in the image and will end up the repo.
The base commit id is available in the container image config as a Label. So, we change ostree-prepare-root to fall back to using this base commit+commitmeta to find the expected composefs digest if the main commit is not signed.
> Support using composefs signatures also with bootc commits

- src/ostree/ot-admin-builtin-status.c
Very, very small change. Whilst you can derive the deployment index from the offset in the JSON object array, including the deployment index directly in the JSON output makes scripting just that _tiny bit_ nicer to work with. I tested it locally, and everything works fine. If this change isn't suitable, please feel free to close the merge request - cheers!
```shell
$ ./ostree admin status -J | jq -r '.[][] | "\(.booted) \(.index) \(.checksum)"'
true 0 6ecb0b27b7fc107076b8f1155ca7a3505207d244802f15dbb240483bb8d38a84
false 1 ca6b6a42071e0bdc50aed2cfab2ca94671446f255f54943e191ce4d10173a642
false 2 b3adb220dbc32851fee801645b845399aaca45fa2879602ee14aaa380bd4bf38
false 3 032383b10f1e0866e2533f40ebeb937bb50577f71de836a5fac2285b7f7f1031
false 4 …
```
> status: Include deployment index in JSON output
